### ISSUE TITLE
Make use of wp_date instead of date_i18n on Twentytwnety

### ISSUE THREAD

**Issue by sachyya** [WordPress/twentytwenty#1013]
As per the new update, it is not recommended to localize time based on WP timestamp: `date_i18n( DATE_RFC3339, $timestamp + $offset` 

Rather use new `wp_date` based on Unix timestamp on Twentytwnety theme `footer.php L23`

**Comment by nielslange** [comment]
From this point on any new issues should be opened on the core trac instead of at GitHub to save them needing to be transitioned over there manually at a later point.

Please prefix tickets with Twenty Twenty: so that they are easy to find over there.

https://core.trac.wordpress.org
