### ISSUE TITLE
Not compatible with WooCommerce (?)

### ISSUE THREAD

**Issue by BusinessBloomer** [WordPress/twentytwenty#1015]
I'm copying https://wordpress.org/support/topic/not-compatible-with-woocommerce-10/ here because I believe it's too important:

I love the new theme… but I’m quite surprised about these WooCommerce-related issues:

- single product page looks like a blog post – author, published date and comments should not be there
- single product page doesn’t take the full width (same applies to product archive pages)
- single product page shows comments and “Leave a reply” but no WooCommerce reviews and “Leave a review” form
- would be nice to have a cart menu icon
- cart page & checkout page: shipping rate prices have a different format than the totals
- checkout is missing the “shipping details” title

Hope this helps

**Comment by nielslange** [comment]
Thanks for reporting this issue, @BusinessBloomer! Please note that this repo is no longer active for the development of the Twenty Twenty theme. Therefore, I moved your issue over to https://core.trac.wordpress.org/ticket/48762 and will close this issue here.
