### ISSUE TITLE
hr class="post-separator" broken by hide categories

### ISSUE THREAD

**Issue by RickorDD** [WordPress/twentytwenty#1016]
i add this CSS **.entry-categories { display: none; }** in Additional CSS.

the last or a other Line change to

![Bildschirmfoto 2019-11-28 um 15 14 49](https://user-images.githubusercontent.com/6922544/69813121-da91cc00-11f1-11ea-9b15-b6ac757f3eb0.png)

and not to

![Bildschirmfoto 2019-11-28 um 15 10 37](https://user-images.githubusercontent.com/6922544/69813060-bcc46700-11f1-11ea-8611-8bda8e098e3a.png)

**Comment by nielslange** [comment]
@RickorDD As mentioned in https://github.com/WordPress/twentytwenty/issues/991, please report this issue in Trac instead of here. This repo had been closed almost 3 weeks ago.
