### ISSUE TITLE
Html has an unnecessary top margin when the menu button is clicked on small screens

### ISSUE THREAD

**Issue by imranhsayed** [WordPress/twentytwenty#105]
**Issue:**
When the user is logged in:
The html has an unnecessary top margin when the menu button is clicked on small screens( front-end )

**Resolution**
Will be resolved with PR: https://github.com/WordPress/twentytwenty/pull/104

![image](https://user-images.githubusercontent.com/11497423/64488312-14db7500-d264-11e9-99f4-0efb75c37128.png)

![image](https://user-images.githubusercontent.com/11497423/64488323-2cb2f900-d264-11e9-9bd4-a229336fe6bb.png)

**Comment by carolinan** [comment]
This is partially fixed, there is still a problem when you use Chrome and resize the browser window without refreshing it.

**Comment by ianbelanger79** [comment]
This appears to be completely fixed. Feel free to reopen if it's not.
