### ISSUE TITLE
Template files should not be slug specific: page-header.php

### ISSUE THREAD

**Issue by hareesh-pillai** [WordPress/twentytwenty#111]
Error reported by Theme Sniffer: Template files should not be slug specific. The file name used for this template will be interpreted by WP as `page-header` and only applied when a page with the slug `header` is loaded.

**Comment by joyously** [comment]
While this is true that `page-header.php` would not be good in the main folder of the theme, apparently it's not an issue when it is in a subfolder.
I think it should probably be changed anyway, though.

![test-for-page-header-file](https://user-images.githubusercontent.com/7957680/64494580-61b74f80-d254-11e9-86cb-75df46d66acd.jpg)

**Comment by ernilambar** [comment]
> Error reported by Theme Sniffer: Template files should not be slug specific. The file name used for this template will be interpreted by WP as `page-header` and only applied when a page with the slug `header` is loaded.

This looks like bug in sniffer. When file is within subfolder, there should be no ERROR. I have created issue in the repo. https://github.com/WPTRT/WPThemeReview/issues/233

**Comment by carolinan** [comment]
This file has been renamed to entry-header.php.
