### ISSUE TITLE
Support for non-latin font fallbacks

### ISSUE THREAD

**Issue by andersnoren** [WordPress/twentytwenty#118]
Following in the tradition of [this issue](https://github.com/WordPress/twentynineteen/issues/29) for Twenty Nineteen and [this one](https://github.com/WordPress/twentyseventeen/issues/59) for Twenty Seventeen, we’d love to get some help from all of the polyglots and i18n folks out there to make sure that Twenty Twenty has awesome support for non-latin alphabets. To start with, we need help with finding good non-latin fallbacks. Later on, we'll need lots and lots of help with testing. 

Kudos to @nielslange for this handy table from last year, which I'm stealing outright. This is the list of alphabets supported in `twentyseventeen` and `twentynineteen`. I'll update with font stacks, testers and PRs for Twenty Twenty as we go.

| Language | ISO Codes | Fonts | Tester | Status |
| :--- |:--- |:--- |:--- |:--- |
| Arabic | ar, ary, azb, ckb, fa-IR, haz, ps | Tahoma, Arial, sans_serif; | @elazzabi | [✅](https://github.com/WordPress/twentytwenty/issues/118#issuecomment-536925675) |
| Chinese Simplified (China) | zh_CN | "PingFang SC", "Helvetica Neue", "Microsoft YaHei New", "STHeiti Light", sans-serif   | @yuliyang | — |
| Chinese Traditional (Taiwan) | zh_TW | "PingFang TC", "Helvetica Neue", "Microsoft YaHei New", "STHeiti Light", sans-serif;  | @yuliyang | — |
| Chinese (Hong Kong) | zh_HK | "PingFang HK", "Helvetica Neue", "Microsoft YaHei New", "STHeiti Light", sans-serif;  | @yuliyang | — |
| Cyrillic | bel, bg-BG, kk, mk_MK, mn, ru-RU, sah, sr_RS, tt_RU, uk | "Helvetica Neue", Helvetica, "Segoe UI", Arial, sans_serif; | — | — |
| Devanagari | bn_BD, hi_IN, mr, ne_NP | Arial, sans_serif; | — | — |
| Greek | el | "Helvetica Neue", Helvetica, Arial, sans_serif; | — | — |
| Gujarati | gu | Arial, sans_serif; | — | — |
| Hebrew | he-IL | "Arial Hebrew", Arial, sans_serif; | — | — |
| Japanese | ja | sans-serif; | @nukaga, @miminari | — |
| Korean | ko-KR | "Apple SD Gothic Neo", "Malgun Gothic", "Nanum Gothic", Dotum, sans-serif; | @donpark | — |
| Thai | th | "Sukhumvit Set", "Helvetica Neue", Helvetica, Arial, sans-serif; | — | — |
| Vietnamese | vi | "Libre Franklin", sans-serif; | @philiparthurmoore, @dinhtungdu | — |

**Comment by kjellr** [comment]
A quick note from an implementation perspective: If possible, it would be great to get these loaded as individual stylesheets, and call them only if they're needed. In Twenty Nineteen, each of these additional styles are included in the main stylesheet by default, and [add quite a bit of filesize](https://core.trac.wordpress.org/ticket/47925).

**Comment by andersnoren** [comment]
@kjellr Thanks for the note! Yes, finding a good way to avoid that would be great. Getting a discussion going about the performance impact of using alphabet specific stylesheets and only loading the one that is needed would be awesome.

**Comment by kjellr** [comment]
This was [touched upon in Slack](https://wordpress.slack.com/archives/C02RP4VMP/p1568056174122900) today, but just making note here: The most difficult aspect of this is separate from the development hurdle: it's finding appropriate font substitutes that carry the same feel as the primary latin fonts. Ideally designers familiar with each non-latin language would help making these fallback stack decisions, since many of us aren't familiar designing in languages other than our own.

**Comment by nukaga** [comment]
For Japanese, I think the title (h1-h6) choose to be Noto Sans JP and the text use be "Hiragino Kaku Gothic ProN" or "sans_serif" only.
Web fonts in Japanese fonts are heavy and are not suitable for setting all posts. And since the environment of Japanese fonts is various, I thought it would be good to make use of the fonts of each device.

**Comment by westonruter** [comment]
> it would be great to get these loaded as individual stylesheets, and call them only if they're needed.

This it would be great to use `wp_add_inline_style()` for this. The mappings of languages to fonts can be stored in PHP and then it can call `wp_add_inline_style()` to just output what is required. This would avoid the frontend overhead of another render-blocking stylesheet.

**Comment by nielslange** [comment]
@andersnoren I've collected the following potential non-latin fallback fonts on Google Fonts. Would you mind going through the list to take a look which fonts would be suitable for:
1. Titles
2. Other texts

**Potential fonts**

- Arabic: https://fonts.google.com/?subset=arabic
- Chinese: https://fonts.google.com/?subset=chinese-simplified
- Cyrillic: https://fonts.google.com/?subset=cyrillic
- Devanagari: https://fonts.google.com/?subset=devanagari 
- Greek: https://fonts.google.com/?subset=greek
- Gujarati: https://fonts.google.com/?subset=gujarati
- Hebrew: https://fonts.google.com/?subset=hebrew
- Japanese: https://fonts.google.com/?subset=japanese
- Korean: https://fonts.google.com/?subset=korean
- Thai: https://fonts.google.com/?subset=thai
- Vietnamese: https://fonts.google.com/?subset=vietnamese

ℹ️ _Noto Sans_ might be a good fit as it supports most of the locals listed above.

**Comment by andersnoren** [comment]
@nukaga Thank you for the reply, and sorry that I'm late in getting back to you. I've added `'Noto Sans JP', 'Hiragino Kaku Gothic ProN', sans-serif` to the Japanese row.

@nielslange Noto Sans looks like it would substitute well for Inter in terms of x-height and overall letterform width, so that seems like a strong candidate at least. I don't feel comfortable making suggestions for most of the specific alphabets listed though, since I have no idea if the fonts I would propose would be at all readable.

**Comment by nielslange** [comment]
@andersnoren Thanks for your reply! In that case, I start by finding folks that can test this issue and can suggest readable fonts. How does that sound to you?

**Comment by andersnoren** [comment]
@nielslange Sounds good!

**Comment by nielslange** [comment]
Potential testers:

- **Arabic**: @elazzabi and @youknowriad Would you mind assisting me in finding and testing fonts for Arabic?
- **Chinese**: @yuliyang Would you mind assisting me in finding and testing fonts for Chinese?
- **Cyrillic**: @slaFFik Would you mind assisting me in finding and testing fonts for Cyrillic?
- **Devanagari**: TBD
- **Greek**: @chriskmnds Would you mind assisting me in finding and testing fonts for Greek?
- **Gujarati**: @galakhyati
- **Hebrew**: @danieldanilov and @yoavf Would you mind assisting me in finding and testing fonts for Hebrew?
- **Japanese**: @nukaga and @miminari Would you mind assisting me in finding and testing fonts for Japanese?
- **Korean**: @donpark: Would you mind assisting me in finding and testing fonts for Korean?
- **Thai**: @imnok Would you mind assisting me in finding and testing fonts for Thai?
- **Vietnamese**: @dinhtungdu and @philiparthurmoore: Would you mind assisting me in finding and testing fonts for Vietnamese?

**Comment by dinhtungdu** [comment]
@nielslange  Yes, sure :)

**Comment by nielslange** [comment]
Thanks, @dinhtungdu! 😀

**Comment by philiparthurmoore** [comment]
> Vietnamese: @dinhtungdu and @philiparthurmoore: Would you mind assisting me in finding and testing fonts for Vietnamese?

@dinhtungdu Let me know if you need me to test also - happy to help. :)

**Comment by yuliyang** [comment]
Chinese Simplified (China) - Noto Sans SC
https://fonts.google.com/specimen/Noto+Sans+SC

Chinese Traditional (Taiwan) - Noto Sans TC
https://fonts.google.com/specimen/Noto+Sans+TC

Chinese (Hong Kong) - Noto Sans HK
https://fonts.google.com/specimen/Noto+Sans+HK

I can help with testing. 😄

**Comment by elazzabi** [comment]
Happy to help test Arabic <3

**Comment by nukaga** [comment]
I will be happy to help you!

**Comment by nielslange** [comment]
Thanks, @philiparthurmoore, @yuliyang, @elazzabi and @nukaga for helping out!

@philiparthurmoore Would https://fonts.google.com/specimen/Noto+Sans work for Vietnamese?

@yuliyang Thanks for suggesting the fonts for Chinese! 

@elazzabi Would https://fonts.google.com/specimen/Cairo work for Arabic?

@nukaga Would https://fonts.google.com/specimen/Noto+Sans+JP work for Japanese?

**Comment by nielslange** [comment]
@yuliyang Based on https://github.com/WordPress/twentytwenty/issues/118#issuecomment-532572678 I created the PR https://github.com/nielslange/twentytwenty/commit/e95fce6c70c0d516ac5d5be9be12108e996da2af. Feel free to start testing and let me know if something needs to be adjusted. Also, is it common to format text bold and italic in Chinese or is that rather uncommon?

**Comment by donpark** [comment]
@andersnoren it'd be nice to have some basic info on what "finding and testing fonts" means and how one should go about doing it.

1. "Twenty Twenty" theme is not listed and WP.org theme pages under https://wordpress.org/themes/twentytwenty/ 404s so I had to git clone, zip and upload to an Atomic test site to see the theme.
2. Should I be switching site language to target language or set it to some known problematic language?
3. Should I be overriding site font via `* {font-family:"Foobar"}` Custom CSS to simulate fallback?
4. Are there specific pages/posts/widgets/blocks/etc that cause non-latin fallback font problems?
5. Do we have a single test page with all problematic parts and controls to switch site language and fonts?

As a developer, I think I'm missing some really basic info here.

**Comment by yuliyang** [comment]
> @yuliyang Based on [#118 (comment)](https://github.com/WordPress/twentytwenty/issues/118#issuecomment-532572678) I created the PR [nielslange@e95fce6](https://github.com/nielslange/twentytwenty/commit/e95fce6c70c0d516ac5d5be9be12108e996da2af). Feel free to start testing and let me know if something needs to be adjusted. Also, is it common to format text bold and italic in Chinese or is that rather uncommon?

Chinese characters do not have italic. It's very uncommon unless the font itself has italic character designed. I double-checked Noto Sans for Chinese and none of them has italic. So ideally, no italic, please. :)

**Comment by andersnoren** [comment]
@yuliyang Thanks, updated! Do you have any suggestions on suitable fallbacks for Noto Sans for the Chinese fonts? The following were used for Twenty Nineteen:

```
'PingFang TC', 'Helvetica Neue', Helvetica, STHeitiTC-Light, Arial, sans-serif;
```

@donpark Sorry for the confusion. At this point, we're mostly looking for suggestions on fonts we can include for each alphabet. None of them are currently included in the theme. Once we have pull requests created for including the fonts for the respective alphabets, we would appreciate any help we can get with testing the pull requests by setting the site language to the language the PR includes fonts and styles for.

I'm afraid I'm not the best person to speak to point 4 and 5 (common issues and font problems). I wanted to get the ball rolling on non-latin fallbacks early, but I don't have much experience in this area personally.

**Comment by miminari** [comment]
@nielslange I’d love to do it.

**Comment by nielslange** [comment]
> Chinese characters do not have italic. It's very uncommon unless the font itself has italic character designed. I double-checked Noto Sans for Chinese and none of them has italic. So ideally, no italic, please. :)

Thanks for your reply, @yuliyang! 

> @nielslange I’d love to do it.

Great to hear that, @miminari! In https://github.com/WordPress/twentytwenty/issues/118#issuecomment-532778653 I've already asked @nukaga if https://fonts.google.com/specimen/Noto+Sans+JP would work for Japanese? Do you think that font will work?

**Comment by donpark** [comment]
> At this point, we're mostly looking for suggestions on fonts we can include for each alphabet. None of them are currently included in the theme.

OK. Korean alphabet is simple but presentation is combinatorial which Unicode handles by mapping each combination as a Unicode character. That balloons Korean font files to typically 15~20 times larger than latin fonts so I don't recommend including whole Korean font files. That said, I've just learned most browsers support [CSS3 `unicode-range` subsetting](https://caniuse.com/#feat=font-unicode-range) which looks useful. More info on how Google supports it in context of Korean fonts can be found [here](https://developers.googleblog.com/2018/04/google-fonts-launches-korean-support.html).

**Comment by nielslange** [comment]
@donpark Would it be an option to add [Noto Sans KR](https://fonts.google.com/specimen/Noto+Sans+KR) using `@font-face`?

**Comment by nielslange** [comment]
@fierevere Thanks for suggesting the fonts. Would you be able to test the implementation for Russian?

**Comment by fierevere** [comment]
> @fierevere Thanks for suggesting the fonts. Would you be able to test the implementation for Russian?

Its not a suggestion, its test results. I've suggested Noto on Slack #polyglots channel some time ago, along with some Inter screenshots, showing some problems with cyrillic.
ref:
https://wordpress.slack.com/archives/C02RP50LK/p1567866351156100
and below.

**Comment by nielslange** [comment]
I see. Thus, `Noto Sans` it is for Cyrillic languages.

**Comment by nielslange** [comment]
@andersnoren Can you update the table in https://github.com/WordPress/twentytwenty/issues/118#issue-490793199 as follows:

- Arabic → Tester: @elazzabi 
- Chinese Simplified (China) → Tester: @yuliyang 
- Chinese Traditional (Taiwan) → Tester: @yuliyang 
- Chinese (Hong Kong) → Tester: @yuliyang 
- Japanese → Tester: @nukaga & @miminari 
- Korean → Tester: @donpark 
- Vietnamese → @philiparthurmoore

**Comment by andersnoren** [comment]
@nielslange Updated!

**Comment by nielslange** [comment]
Thanks, @andersnoren!

**Comment by donpark** [comment]
> @donpark Would it be an option to add [Noto Sans KR](https://fonts.google.com/specimen/Noto+Sans+KR) using `@font-face`?

"Noto Sans KR" looks remarkably good. Here is a partial view (covernig ㄱ,ㄴ, and ㄷ) of a collection of oddball Hangul characters that often breaks, aka 뷁어 using the font:

<img width="1149" alt="screenshot_920" src="https://user-images.githubusercontent.com/127594/65282700-63053980-daea-11e9-9797-2f7aaec2e42f.png">

[breaking-bad-kr.html.zip](https://github.com/WordPress/twentytwenty/files/3633279/breaking-bad-kr.html.zip)

**Comment by nielslange** [comment]
> For Japanese, I think the title (h1-h6) choose to be Noto Sans JP and the text use be "Hiragino Kaku Gothic ProN" or "sans_serif" only.
> Web fonts in Japanese fonts are heavy and are not suitable for setting all posts. And since the environment of Japanese fonts is various, I thought it would be good to make use of the fonts of each device.

@nukaga You suggested using `Hiragino Kaku Gothic ProN` for the regular texts. It seems that this is a paid [premium font. Is that correct?

**Comment by nielslange** [comment]
> Yes! "Noto Sans KR" looks remarkably good. Here is a partial view (starring ㄱ,ㄴ, and ㄷ) of a collection of Hangul characters, including those that often breaks, aka 뷁어, using the font:

@donpark Thanks for confirming that `Noto Sans KR` would be a great match!

> Disclaimer: I'm just a casual user of Korean language who happens to be a developer, not an expert on Hangul nor Korean language.

I'll reach out to more Korean folks to test the implementation of the Korean fallback font.

> UPDATE: Screenshot above is not a stereogram so you won't be able to see the hidden spaceship no matter how hard you squint.

Damn it! I was trying to hard to see the spaceship. I should have read your entire message first! 😂

**Comment by nukaga** [comment]
@nielslange 
I'm sorry. My writing was not good.
I thought it would be good to specify only sans_serif for regular text (use the default Gothic font for each device).

Because some people set “the default font easy to read”, and the fonts are set for each device for ease of viewing. 

If we need to set the font, I think "Hiragino Kaku Gothic ProN" and "Meiryo" are good. 
Hiragino is a bundled font Mac OS X later. Meiryo has been bundled Windows vista later.

What do you think? @miminari

**Comment by nielslange** [comment]
@nukaga Don't worry about your writing and thanks for your quick reply! 😀 If I understand you correctly, you would use `Noto Sans JP`  for the title and `Hiragino Kaku Gothic ProN` and `Meiryo` for the regular texts, correct?

**Comment by nukaga** [comment]
@nielslange 
> you would use Noto Sans JP for the title and Hiragino Kaku Gothic ProN and Meiryo for the regular texts, correct?

Yes, Thanks!

**Comment by nielslange** [comment]
Thank you, @nukaga! 🙏

**Comment by nielslange** [comment]
@alssong, @jsnmoon & @taggon Would you mind assisting me in testing fallback fonts for Korean?

**Comment by nielslange** [comment]
@dinhtungdu & @philiparthurmoore According to https://fonts.google.com/?subset=vietnamese `Noto Sans` supports Vietnamese. Do you have any objections using this font?

**Comment by dinhtungdu** [comment]
@nielslange No. Noto Sans is great for Vietnamese also :)

**Comment by nielslange** [comment]
Thanks, @dinhtungdu!

**Comment by nielslange** [comment]
@andersnoren Can you update the table in #118 (comment) as follows:

- Japanese → Fonts: `Noto Sans JP, Hiragino Kaku Gothic ProN, Meiryo`
- Korean → Font: `Noto Sans KR`
- Vietnamese → Font: `Noto Sans`
- Vietnamese → Tester: @dinhtungdu

**Comment by yuliyang** [comment]
> @yuliyang Thanks, updated! Do you have any suggestions on suitable fallbacks for Noto Sans for the Chinese fonts? The following were used for Twenty Nineteen:
> 
> ```
> 'PingFang TC', 'Helvetica Neue', Helvetica, STHeitiTC-Light, Arial, sans-serif;
> ```
> 

Different languages will have different fallbacks.

Chinese Simplified (China)
```
'PingFang SC', 'Helvetica Neue', "Microsoft YaHei New", STHeiti Light, sans-serif
```

Chinese Traditional (Taiwan)
```
'PingFang TC', 'Helvetica Neue', "Microsoft YaHei New", STHeiti Light, sans-serif;
```

Chinese Hong Kong
```
'PingFang HK', 'Helvetica Neue', "Microsoft YaHei New", STHeiti Light, sans-serif;
```

Please correct me if anything doesn't look right. I'm not sure if different language devices have different default fonts. I'm using MacOS English system, not native Chinese system. I know 'PingFang xx' font for sure but not 100% sure anything after that.

**Comment by andersnoren** [comment]
@nielslange Updated!
@yuliyang Awesome, big thanks for the help! Updated.

**Comment by nielslange** [comment]
Thanks, @yuliyang and @andersnoren! 🙏

**Comment by elazzabi** [comment]
@andersnoren @nielslange the Cairo font looks good for Arabic. I played with some sentences on the Google Fonts site and it looks good.

Any instructions on how to use the theme on a site so I can look around and see if everything looks good?

**Comment by nielslange** [comment]
@elazzabi Thanks for confirming the font. Can you tell me if it's common in Arabic to format texts bold and italic? Regarding testing, you can download the Twenty Twenty theme, including the non-latin font fallback, via https://github.com/nielslange/twentytwenty/archive/try/%23118.zip and install it on a test site. Once you've done that, you need to change the site language to Arabic.

@andersnoren Can you update the table in #118 (comment) as follows:

- Arabic → Font: `Cairo`

**Comment by taggon** [comment]
@nielslange In addition to `Noto Sans KR`, I'd recommend to add few more fonts which I suggested for the Twenty Seventeen([#](https://github.com/WordPress/twentyseventeen/pull/286)).
```
"Noto Sans KR", "Apple SD Gothic Neo", "Malgun Gothic", "Nanum Gothic", Dotum, sans-serif
```

**Comment by elazzabi** [comment]
@nielslange in Arabic, bold is used to highlight stuff etc. Italic is not used in Arabic.

I'll download the theme and try it on a test site

**Comment by andersnoren** [comment]
Hi everyone! After talking to people in the #core-privacy channel, we (in this case meaning me, @ianbelanger79 and @carolinan) have come to the decision that we can’t use fonts hosted on the Google Fonts CDN in Twenty Twenty. **That means that we need to rely on system fonts only for the non-latin fonts.** @garrett-eclipse gave a detailed explanation of the various issues in relying on Google Fonts in Twenty Twenty [here](https://github.com/WordPress/twentytwenty/issues/542#issuecomment-535595983).

I have updated the table in the first comment to remove all Google Fonts, but I have left the fallback font stacks you’ve recommended as-is. Some of the alphabets didn't have any recommended font stacks yet. I have updated those with the font stacks used for the respective alphabet in Twenty Nineteen, just to give us a starting point to use in the implementation.

I’m really sorry that we didn’t make this clear up front. We wanted to get the ball rolling on this issue as quickly as possible, but in the process, failed to do our due diligence before asking you for your input. I hope you will still be willing to help out with suggestions and testing in the weeks to come, to make sure our non-latin support is as solid as it can be.

**Comment by nielslange** [comment]
That's very sad to hear, Anders, but very understandable due to the GDPR. Thanks for updating the table with the fallback fonts. That's really helpful for implementing the fallback fonts.

**Comment by nielslange** [comment]
@elazzabi, @yuliyang, @nukaga, @miminari, @donpark, @philiparthurmoore, @dinhtungdu: Based on https://github.com/WordPress/twentytwenty/issues/542#issuecomment-535595983 and https://github.com/WordPress/twentytwenty/issues/118#issuecomment-536072038 we're not using Google Fonts but only system fonts as non-latin fallback fonts. I'm implemented this feature. 

Would you mind running some tests is the implementation works as expected? You can download the theme, which includes this feature, via https://github.com/nielslange/twentytwenty/archive/try/%23118.zip. 

Please also let me know if you have any questions regarding the fonts or the testing or if you have any other questions or suggestions. Thank you very much in advance for offering to assist with testing this PR! 😀

**Comment by elazzabi** [comment]
@nielslange I added twentytwenty to a test site. In general, title and content looks good. Here are some things to fix however:

1.
<img width="348" alt="Screen Shot 2019-09-30 at 7 07 40 PM" src="https://user-images.githubusercontent.com/12542046/65904208-e4e04700-e3b5-11e9-992b-227c8f2ee035.png">

The date should be transformed from: `سبتمبر 30, 2019` to 'YEAR MONTH DAY', no commas (I can't write it as GH is giving me a hard time with Arabic :/)

2.
<img width="734" alt="Screen Shot 2019-09-30 at 7 07 57 PM" src="https://user-images.githubusercontent.com/12542046/65904546-941d1e00-e3b6-11e9-898e-97088a586940.png">
<img width="215" alt="Screen Shot 2019-09-30 at 7 07 02 PM" src="https://user-images.githubusercontent.com/12542046/65904558-9aab9580-e3b6-11e9-9913-a4b1ebc91f00.png">
<img width="692" alt="Screen Shot 2019-09-30 at 7 05 12 PM" src="https://user-images.githubusercontent.com/12542046/65904575-a4cd9400-e3b6-11e9-9f30-f3d9aaf733b6.png">
<img width="205" alt="Screen Shot 2019-09-30 at 7 16 05 PM" src="https://user-images.githubusercontent.com/12542046/65904648-c7f84380-e3b6-11e9-9141-53f2c91a31a0.png">

Search, sorting, notification settings and 'To the top' aren't translated.

**Comment by joyously** [comment]
> The date should be transformed from: سبتمبر 30, 2019 to YEAR MONTH DAY,

Is that how you have your test site's date format set?

> Search, sorting, notification settings and 'To the top' aren't translated.

The theme isn't translated yet, but those Notify options are from a plugin.

**Comment by nielslange** [comment]
@elazzabi Thanks for testing! 🤗 Similar to what @joyously already mentioned, I also assume that the date format might come from your site settings> Can you double-check this? And the strings that you mentioned have indeed not been translated yet. This should happen within the next couple of days/weeks.

**Comment by elazzabi** [comment]
> Is that how you have your test site's date format set?
Oh forgot about that. All good then 👍

**Comment by nukaga** [comment]
Hello. I found two problems during the test.
・ The page title is too large in Japanese.
・ In our language, the align centered page title is strange.

1. Change the size of characters according to language
2. For Japanese, left justify
Is this possible?

<img width="1385" alt="スクリーンショット 2019-09-25 15 23 02" src="https://user-images.githubusercontent.com/3480985/65952661-44edf080-e47d-11e9-82a5-ad9bb4ccbbf4.png">

**Comment by nielslange** [comment]
Thanks for testing this PR, @nukaga. If I understand you correctly, the page title should be left-aligned and the font size should be decreased. All other elements, e.g. tagline, meta information, body text, etc. remain untouched, correct?

**Comment by nukaga** [comment]
@nielslange Thank you for understanding!

> the page title should be left-aligned and the font size should be decreased

Yes. That's right. 
Is adjustment possible?

For other elements, I will check.

**Comment by donpark** [comment]
It'd be really nice to have something like _headstart_ that populates a site with content that pushes non-latin support in themes to reasonable extremes for testing purpose. Hmm. _troublestart_?

**Comment by nielslange** [comment]
@donpark That's a great idea. The theme review team has a [theme unit test](https://codex.wordpress.org/Theme_Unit_Test) which covers pretty much all cases. It might be good to have that theme unit test file also available in other languages for testing purposes.

cc: @carolinan, @pattonwebz, @ianbelanger79

**Comment by joyously** [comment]
There's actually an issue on the unit test about [international content](https://github.com/WPTRT/theme-unit-test/issues/6).

**Comment by yuliyang** [comment]
Same with Japanese, the page title is probably too large for all Chinese (simplified and traditional).
Other than that, everything looks good!

Tested: Chinese Simplified (China), Chinese Traditional (Taiwan), Chinese (Hong Kong)

**Comment by nukaga** [comment]
We did a Japanese test today. ( with @atachibana @miminari @shinyabw )

First, please use only the title and text `sans-serif`.
The situation of Japanese devices varies, and some people use universal fonts. We thought that sans-serif only designations were the easiest to read.

title
・ The font size is large.
・ Character feed is clogged
・ Center alignment is strange

Text
・ We want the font to be `sans-serif`
・ Narrow line spacing

So we suggest the following.

title:
```
font-family: sans-serif;
font-size: 6.4;
letter-spacing: normal;
```

p:
```
font-family: sans-serif;
line-height 1.6;
```
