### ISSUE TITLE
Search results. Align the search form in center

### ISSUE THREAD

**Issue by vbaimas** [WordPress/twentytwenty#119]
The search form in search results page, align in the left side. It will be more useful if this search fom align in the center of page. Τhe user's eye scans and reads in a logical order.

![search-results](https://user-images.githubusercontent.com/5068068/64493145-0e112a00-d285-11e9-92d4-5cdc53e41ddf.png)

**Comment by mukeshpanchal27** [comment]
@vbaimas Below CSS fixed the center alignment for search form. Check it then I will submit PR for same

`
.no-search-results-form {
	width: 100%;
	max-width: 37rem;
	margin: 0 auto;
}
`

**Comment by vbaimas** [comment]
@mukeshpanchal27, thanks for the reply.

 Instead of : 
`.no-search-results-form { width: 100%; max-width: 37rem; margin: 0 auto; }`

We can use flex : 

`.no-search-results-form  { display: flex; align-items: center; justify-content: center;}`

I see in action that the result is the same. What do you think?

**Comment by mukeshpanchal27** [comment]
@vbaimas It's working fine for me.

Can we use below CSS so it will support in other browsers also?

<pre>
.no-search-results-form {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
        -ms-flex-align: center;
            align-items: center;
    -webkit-box-pack: center;
        -ms-flex-pack: center;
            justify-content: center;
}
</pre>

**Comment by andersnoren** [comment]
@vbaimas @mukeshpanchal27 If you add the following classes to the `.no-search-results-form` container, it will match the outer margins with the rest of the site on all screen sizes: `section-inner thin`.

So the wrapping element looks like this:

`<div class="no-search-results-form section-inner thin">`

Ideally, this should be combined with adding `width: 100%;` to the `.search-form label` label element, so the search form fills out the width of the container.
