### ISSUE TITLE
Can we remove jQuery dependency?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#12]
Would it be possible to rewrite the script in vanilla JS?

https://github.com/WordPress/twentytwenty/blob/81b787b65c3e1a19c7e230cf4b49729ebd970760/functions.php#L159

**Comment by carolinan** [comment]
The plan is to remove jQuery yes.

**Comment by LittleBigThing** [comment]
This seems to be a fair amount of work, but of course needed.

Is there a plan on how to do this? Maybe we can start summarising the JS driven stuff in this issue and split them out in separate tasks?

- [ ] Mobile menu toggle
- [ ] Search toggle
- [ ] Smooth scroll if needed
- [ ] ...

Also, we could start the modifications based on the _s theme's [vanilla JS files](https://github.com/Automattic/_s/tree/master/js).

**Comment by LittleBigThing** [comment]
Some related issues:

- #27 
- #66 
- #68 
- #80 
- #81
