### ISSUE TITLE
Indicate dropdown functionality on <select> HTML

### ISSUE THREAD

**Issue by jarretc** [WordPress/twentytwenty#120]
Currently, there isn't any indication that a dropdown menu is something you click on to see further options. 

![2020dropdown](https://user-images.githubusercontent.com/1584764/64494064-16457700-d23d-11e9-8038-d114aa2b9c18.png)

While it can be coded to mention that it is indeed a dropdown, having some type of icon (arrow pointing down) on the far right or similar would help.

**Comment by andersnoren** [comment]
@jarretc Thanks for posting this. Which browser and OS are you using?

**Comment by andersnoren** [comment]
We should probably follow Twenty Nineteens lead on this one and omit custom `select` styling entirely. I've added an PR for this here: #121.

**Comment by jarretc** [comment]
@andersnoren ah, this was on Chrome using MacOS 10.14.6
