### ISSUE TITLE
Main menu overlay does not constraint focus

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentytwenty#123]
As the main menu has been implemented as an overlay, it needs represent and act like one to people using assistive technologies and keyboards. This means you have to do a lot more work with keyboard interactions like constraining the focus and moving it around when opening and closing the modal.

Can we re-think this implementation? Mobile menus implemented as modal windows are unnecessarily difficult to implement accessibly.

**Comment by andersnoren** [comment]
@afercia has created an issue that touches on this here: #80

**Comment by carolinan** [comment]
This has been partially fixed.

I now noticed that if the last menu item has submenu items, and you close the submenu, then the focus is on the main page if you tab _forwards._ 
Tabbing backwards still keeps the focus within the menu.

@c4rl0sbr4v0 do you have time to look at this again? :)

**Comment by c4rl0sbr4v0** [comment]
> I now noticed that if the last menu item has submenu items, and you close the submenu, then the focus is on the main page if you tab _forwards._

So I have to fix this. Anything else? Should we wait for that "close button" on the mobile then?

**Comment by carolinan** [comment]
The close button has been added.

**Comment by ianbelanger79** [comment]
Fixed by #755
