### ISSUE TITLE
Some SVG buttons appear to have 3 tabindexes

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentytwenty#124]
I've been tabbing around and I'm not sure if it's just me on Chrome 76, but I seem to tab 3 times into some buttons represented with an icon.

I've seen this on the search close modal button and the menu dropdown buttons that show children menu items.

**Comment by andersnoren** [comment]
@anevins12 I can't replicate this in Chrome on my machine (76 here as well). Can you give it another look and see if it still happend for you?

**Comment by anevins12** [comment]
Yeah I pulled master just can still see it. I'll upload a video just to make sure we're talking about the same thing.

**Comment by anevins12** [comment]
![ezgif-4-3348314e0e14](https://user-images.githubusercontent.com/2318561/64726715-22486780-d4cf-11e9-93f6-ca5fb3eeb5e5.gif)
![ezgif-4-834de5264ee1](https://user-images.githubusercontent.com/2318561/64726831-5885e700-d4cf-11e9-8b0c-b809a12cb3f0.gif)

**Comment by anevins12** [comment]
I don't know what happened to that second gif, it went super quick! I meant to demonstrate that the "X" button in the search modal has 3 stops.

**Comment by andersnoren** [comment]
Sorry @anevins12, you're completely right. There's a big PR underway (#163) for rewriting the current jQuery code to JavaScript. Once that is done, the code managing focus in the modals should be rewritten as well.

**Comment by carolinan** [comment]
This has been fixed, closing the issue. Thank you.
