### ISSUE TITLE
page links don't line up

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#125]
These links look very strange. 
![page-links-vertical](https://user-images.githubusercontent.com/7957680/64495108-2ec48a00-d25b-11e9-889f-1e093ce6192b.jpg)

**Comment by nielslange** [comment]
@joyously It's actually looking good on my end: 
<img width="776" alt="Screenshot 2019-09-09 at 16 32 22" src="https://user-images.githubusercontent.com/3323310/64539819-76ace500-d31f-11e9-9d32-6002108c2e75.png">

Have you created a page with several paragraphs divided by page breaks?

**Comment by joyously** [comment]
No, nothing special. It was using the Theme Unit Test data, on the gallery post.
 It could be the version you tested differs by now from what I was testing.

**Comment by nielslange** [comment]
I'm also using the Theme Unit Test data and just looked up the post _Post Format: Gallery_ in both Chrome, Firefox, Opera and Safari in Mac and the result looks like the one I posted above. What browser and OS are you using?

**Comment by joyously** [comment]
I just now downloaded the zip again, and see the same thing (I did a reload on it) using Firefox 69 on Ubuntu Studio 16.04 and WordPress 4.9.11. When I tried it on WP 5.2.3 though, it looks right.

**Comment by nielslange** [comment]
Oh, that means this issue might be related to different WordPress versions? I'll investigate this issue in detail them.

**Comment by joyously** [comment]
I think it's just the GB styles being loaded in 5.2.3 versus no additional styles in 4.9.11.

**Comment by joyously** [comment]
Looking again (using new master, last commit 8e28522), it appears to be this CSS rule
`.post-nav-links > * { padding: 1em 0.75em; }`
on this HTML
```
<nav class="post-nav-links bg-light-background" aria-label="Page">
  <span class="label">Pages:</span>
 1 
  <a href="http://localhost/review/post-format-gallery/2/">2</a>
</nav>
```
So, the 1 isn't affected because it doesn't match * in the selector since it has no tag.
