### ISSUE TITLE
Use core functionality for custom logo

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#128]
Themes should use core functionality if it exists, so these two functions for custom logo should be removed. Adjusting the generated HTML should be accomplished with a filter.

https://github.com/WordPress/twentytwenty/blob/37d7eddf5817f15b67e9707841c889a78d2b29de/functions.php#L277-L286

Core functions: https://developer.wordpress.org/?s=custom_logo
https://developer.wordpress.org/reference/functions/add_theme_support/#custom-logo

**Comment by byalextran** [comment]
is this as straightforward as it seems? here's what i'm thinking would change: 

1. replace existing custom logo code from `functions.php` with `add_theme_support( 'custom-logo' )`. 
2. update `header.php` to use core functions for custom logos. 

if it is that simple, i'd like to take a stab at a PR.
