### ISSUE TITLE
remove checks for hook functions

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#129]
Most of the functions in functions.php are either filters or actions. These should not have an if statement for a function definition, making them pluggable. If other code (child theme or plugin) wants to change one of these hooks, they can remove the theme hook, and write a hook of their own with their own prefix. 

https://github.com/WordPress/twentytwenty/blob/37d7eddf5817f15b67e9707841c889a78d2b29de/functions.php#L12

**Comment by ianbelanger79** [comment]
We will be removing the function_exists checks
