### ISSUE TITLE
Can we please add a sidebar?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#13]
One of the worst parts about Twenty Nineteen is that there is no sidebar.
This is especially bad for users with custom widgets that have to switch to the default theme to troubleshoot their site. Because of the way that core reassigns widgets, those widgets end up inactive when the theme is switched back.

And it's time for the default theme to show how to use a sidebar with full width blocks.

**Comment by carolinan** [comment]
I don't think the theme should have a sidebar, but the id's of the widget areas could be renamed
to sidebar-1 and sidebar-2 that are more commonly used, to avoid (but not guarantee) that widgets end up inactive.

**Comment by joyously** [comment]
I prefer pages with sidebars. They feel dead-end to me without one. 
And I don't think it makes sense to name them sidebar if they are in the footer. There are matches for that also, in the core code.

**Comment by ZebulanStanphill** [comment]
Yeah, a page template with a sidebar is good for things like showing latest posts, post archive links, and tags while reading a blog post. It shouldn't be the default, in my opinion, but it should definitely be an option to set a template with a sidebar as the default for blog posts (and/or pages if desired).

**Comment by joyously** [comment]
I just switched a test site from Twenty Nineteen to Twenty Twenty, and the footer widgets did not even carry over to the footer. What's up with that? Is it the naming?

**Comment by pattonwebz** [comment]
@joyously You are probably right about it being a naming thing. Here we have `footer-one` and `footer-two` and in Twenty Nineteen there is only 1 sidebar with the name `sidebar-1`. I would have though that this would carry over anyway since it's a single sidebar that could be placed in any one of the two in this theme. Curious why it did not do that though :thinking:

**Comment by joyously** [comment]
Read the core code. "footer-one" matches "footer", not "sidebar".

**Comment by ianbelanger79** [comment]
At this point @andersnoren and I do not feel that we have the time to implement a sidebar. Closing the issue.
