### ISSUE TITLE
Theme mods don't need to be prefixed

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#137]
As the title says, they don't need to be prefixed. It's a waste of db space and it makes them more readable if removed.

**Comment by pattonwebz** [comment]
Indeed the theme_mods are already inside an array option keyed with the slug. Not necessary to prefix the inner keys as well.

**Comment by ernilambar** [comment]
I agree. We just need to make sure that theme options does not conflict with those coming from core (Custom Background and Custom Header) like `background_color`, etc.

**Comment by acosmin** [comment]
I could probably include these changes in #258

**Comment by acosmin** [comment]
@carolinan Should I go ahead and do this?

**Comment by pattonwebz** [comment]
@acosmin looks like you did resolve this one with commits in #258, right?

**Comment by acosmin** [comment]
Yep, I'll close this 👍
