### ISSUE TITLE
add_post_type_support is for plugins, not themes

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#14]
This seems like plugin territory to me. All it does is enable a place to write an excerpt, which the theme should not be influencing.

https://github.com/WordPress/twentytwenty/blob/81b787b65c3e1a19c7e230cf4b49729ebd970760/functions.php#L371

**Comment by pattonwebz** [comment]
Are there places where page excerpts might be shown in the theme? Normally pages do not show in archives or anywhere like that so I can't think of places they would output an excerpt over a full content.

The `<!--more-->` tag may be a more suitable way to have custom picked excerpt (granted not eh same as an excerpt but I think preferable).

**Comment by joyously** [comment]
Page excerpts can be seen on a search. It does not require calling `add_post_type_support` to generate an excerpt. Being able to write an excerpt is a plugin thing, not a theme thing.

The more tag is not for Pages, since it only is handled on archive pages showing full content, where there is a link to the single post page to show the rest.

**Comment by carolinan** [comment]
I don't agree, if a theme does display excerpts of pages, the users needs to be able write that excerpt
and not need to rely on an auto generated excerpt.

**Comment by joyously** [comment]
Where does this theme display excerpts of pages?

**Comment by carolinan** [comment]
In the search result, currently:
https://github.com/WordPress/twentytwenty/blob/master/content.php#L105

**Comment by knutsp** [comment]
Agree. post_type support is needed only to add a manually written excerpt. When not, the generated excerpt is shown/returned.

If a user switches to another theme, whithout this manual excerpt support, the ability to edit these manually written excerpts will be lost. If page content then is rewritten, the excerpt may totally misrepresent the content.

It's quite common, nowadays, for themes to recommend plugin(s) to get an even better experience.

**Comment by ernilambar** [comment]
TRT have been allowing this since years.

**Comment by ianbelanger79** [comment]
I think that we should probably remove the post_type_support for excerpts from pages.

I am in agreement with @knutsp 

> If a user switches to another theme, whithout this manual excerpt support, the ability to edit these manually written excerpts will be lost. If page content then is rewritten, the excerpt may totally misrepresent the content.
> 
> It's quite common, nowadays, for themes to recommend plugin(s) to get an even better experience.

**Comment by ianbelanger79** [comment]
Sorry didn't mean to close it

**Comment by carolinan** [comment]
I did not consider what @knutsp shared. I think you are right.

_And apparently this code has been removed from functions.php already._

**Comment by andersnoren** [comment]
Aye from me as well.


— Anders

**Comment by ernilambar** [comment]
If a user switches to another theme, whithout this manual excerpt support, the ability to edit these manually written excerpts will be lost. If page content then is rewritten, the excerpt may totally misrepresent the content.

Woh, did not consider that till now. Seems valid.

**Comment by carolinan** [comment]
Lets close this, since we are in agreement and the code has been removed.  Thank you.
