### ISSUE TITLE
Unnecessary use of escaping functions

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#147]
https://github.com/WordPress/twentytwenty/blob/c3fd9652e30fb489d83c493b4451ac361f81d75d/functions.php#L301-L303

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/footer.php#L17

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/parts/modal-search.php#L7

For `$cover_header_classes`:
https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/content.php#L45

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/content.php#L74

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/content.php#L142

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/comments.php#L57

https://github.com/WordPress/twentytwenty/blob/35b5d240fcbf283d753f95b9b107be4200fdfee4/parts/classes/class-comment-walker.php#L26

**Comment by ianbelanger79** [comment]
Can we get a PR for this one @pattonwebz? I would like to close it out. Thanks

**Comment by acosmin** [comment]
I could probably take a crack at it :)
