### ISSUE TITLE
Use throttle and debounce

### ISSUE THREAD

**Issue by dingo-d** [WordPress/twentytwenty#15]
https://github.com/WordPress/twentytwenty/blob/81b787b65c3e1a19c7e230cf4b49729ebd970760/assets/js/construct.js#L42-L67

https://github.com/WordPress/twentytwenty/blob/81b787b65c3e1a19c7e230cf4b49729ebd970760/assets/js/construct.js#L74-L95

While we can use underscore.js throttle and debounce functions, a simple vanilla JS alternative could be used. This implementation seems a bit odd.

**Comment by joyously** [comment]
See #12

**Comment by dingo-d** [comment]
That was my inspiration 😉

**Comment by ianbelanger79** [comment]
Is this still relevant after the jQuery removal?
