### ISSUE TITLE
Missing theme description and screenshot make the tests fail

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#158]
Right now, running the tests on my local VVV environment with Twenty Twenty cloned from this repo returns a couple tests failing.

Missing theme description:
the stylesheet header should be wrapped in proper comments and _not_ have an empty description.

Missing screenshot:
I do realize it's a bit early but the missing screenshot makes a test fail :)

Please add a description and a screenshot, even temporary ones.

**Comment by afercia** [comment]
To reproduce:
- clone the theme in the `src` directory
- run `grunt build`
- run the themes tests group with `phpunit --group themes`

**Comment by carolinan** [comment]
A temporary description has been added.

**Comment by ianbelanger79** [comment]
We also have a screenshot now, closing
