### ISSUE TITLE
Header order not consistent between mobile and desktop

### ISSUE THREAD

**Issue by anevins12** [WordPress/twentytwenty#166]
The order of content in the Header is not consistent between Mobile and Desktop. This can be a jarring experience for sighted users that navigate the page using simple input like a keyboard user, as   things can look like they're in a different tab order than they are.

Taking this screenshot from another ticket that Anders raised, and assuming that we're going with a mobile-first approach, I've highlighted the inconsistencies of the order between mobile and desktop by numbering the focus order.

![6f6fe2e7-1da7-4be2-bd4e-8e4f753d5672](https://user-images.githubusercontent.com/2318561/64571525-08d2de80-d35c-11e9-9630-04becbdac62e.png)

**Comment by andersnoren** [comment]
@anevins12 The focus order was updated to match the visual order on all screen sizes in #71. 

There's a discussion to be had about switching places of the menu toggle and search toggle from mobile to desktop, though. The rationale for their positioning on both screen sizes is that the menu toggle is the most important of the two, and having it to the right on mobile makes it easier to reach, and on the left on desktop makes it more noticeable.

**Comment by joyously** [comment]
>  having it to the right on mobile makes it easier to reach

Is this for LTR only? and the other side for RTL?

**Comment by andersnoren** [comment]
For both. The rationale for having it on the right on mobile is to make easier to reach for right-handed users.

**Comment by ianbelanger79** [comment]
Closing this as a `wontfix`
