### ISSUE TITLE
Split the contents of functions.php

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#168]
The functions.php file is over 980 lines long, it needs to be split into smaller, more manageable files.

- [ ] Solve / merge any current open PR's that affects functions.php.

- [x] Create new folder

- [ ] Split the content into new files.

**Suggested structure**

It does not feel right to put these into the _parts_ folder,
so an _inc_ folder would be created.

This list is an overview and and I probably forgot something:
functions.php:
- Theme support
- Register styles
- Register script
- Enqueue Editor styles
- Sidebars

inc/template-tags.php
- Post meta
- Menu
- Comments
- Body classes

inc/custom-css.php
-Generate and get CSS

**Comment by ianbelanger79** [comment]
I believe this is done
