### ISSUE TITLE
Parts Folder Question

### ISSUE THREAD

**Issue by emiluzelac** [WordPress/twentytwenty#170]
For consistency reasons, i.e. [previous default themes](https://github.com/WordPress/twentynineteen/tree/master/template-parts), is it possible to move the [content](https://github.com/WordPress/twentytwenty/blob/master/content.php) within the [parts](https://github.com/WordPress/twentytwenty/tree/master/parts) folder? Folder name doesn't necessarily need to be changed.

**Comment by ernilambar** [comment]
Partially related to https://github.com/WordPress/twentytwenty/issues/168

Looks like we need a bigger rearrangement of files and folders as currently `functions.php` and `content.php` is pretty huge.

**Comment by emiluzelac** [comment]
Agreed!

**Comment by pattonwebz** [comment]
For this we now have a `templates` and a `template-parts` folder as well as `inc` and `classes` for other parts of the refactor. I think that is fine however if there are other changes wanted then let's open new issues for them.

Closing this now as I think it's answers/resolved.
