### ISSUE TITLE
Don't escape translations when not necessary.

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwenty#176]
Just like core, default themes don't escape translations when not necessary as those are trusted.

See these links for background.

- https://core.trac.wordpress.org/ticket/30724 
- https://github.com/WordPress/twentynineteen/pull/285#issuecomment-432855498

**Comment by ernilambar** [comment]
Although default theme does not follow this, I still think it is good to escape translation strings in all places, not only in HTML attributes.

**Comment by mafzal9** [comment]
@nielslange please assign this issue to me.

**Comment by nielslange** [comment]
> @nielslange please assign this issue to me.

Also, feel free just to say that you're working on it, so others know and won't interfere. 😀

**Comment by mafzal9** [comment]
from now onward that's my issue, :) and i will try my best to contribute very well in WordPress community. :)

**Comment by mafzal9** [comment]
@juanfra @ernilambar still i am confused did i need to remove escape translation from theme or add the escape translation in remaining tags  ?

**Comment by juanfra** [comment]
Hello guys,

I hope you're all doing well. These issue was addressed in: https://github.com/WordPress/twentytwenty/pull/177 and https://github.com/WordPress/twentytwenty/pull/441

This one should be closed.

Best,
J.

**Comment by mafzal9** [comment]
Thanks @juanfra for immediate response.
