### ISSUE TITLE
Single title font size is too big for long title

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#183]
Imho the font-size: 9.6rem for the page & post single title is too big for long title. It's difficult to read and I think the user shouldn't have to scroll to read a long title. 
In my example "Basketball Tournament" takes 2 lines. On a cover template, a long title makes the banner higher than full-height.
![post](https://user-images.githubusercontent.com/54663751/64618507-aec82c80-d3e0-11e9-9ad8-80d87ca97c59.png)
![banner](https://user-images.githubusercontent.com/54663751/64618508-af60c300-d3e0-11e9-8712-25eb3c3282d0.png)

**Comment by andersnoren** [comment]
@yannickiki I think I agree with you on this one. Reducing it to somewhere between `8.4rem` to `9.2rem` should be in keeping with the feeling it has now, but make it more useable for more people. I'm going to test a bit and see where it ends up. Thanks for posting the issue.

**Comment by joyously** [comment]
Thanks for writing this issue. I was thinking the difference between the largest and the normal copy size is too much.

**Comment by carolinan** [comment]
@yannickiki What is your wordpress.org username?

**Comment by yannickiki** [comment]
@carolinan  Sorry I didn't see your message. My wordpress.org username is @collet . Thank you!
