### ISSUE TITLE
Comment styling with hidden avatar.

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#184]
WordPress has a setting to hide avatars. Currently when the avatars are hidden, it leaves an unecessary left padding.

![gravatar](https://user-images.githubusercontent.com/54663751/64619999-5b0b1280-d3e3-11e9-9fc0-ff21e509ac1d.png)

**Comment by ianbelanger79** [comment]
It appears that this was fixed in #186, so I am closing the issue
