### ISSUE TITLE
What is the use of the Full Width Template?

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#185]
I don't see any difference between Default Template and Full Width Template. Is it a leftover from Chaplin?

**Comment by andersnoren** [comment]
@yannickiki Thanks for posting the issue! I think there's an expectation for a full width template still (even if the block editor now allows for a lot of the modifications they've often been used for), so we probably want to include one. It seems like no styles are being applied to it currently though, like you say.

The full-width template should:

* Remove the `.thin` class from the wrapping `.post-inner` element, so the content container extends to the width of the layout.
* Remove the max-width values from `.entry-content` and `.entry-content p`, so they extend to the width of the container.
* When we implement the `.alignleft` and `.alignright` classes with negative horizontal margins, positioning them outside the main content column (the pull quote in [this image](https://make.wordpress.org/core/files/2019/09/twenty-twenty-single-post.jpg)), we'll need to adjust those classes to make sure they don't extend outside the main content column on the full width template.

**Comment by LittleBigThing** [comment]
I have asked a similar question here: https://github.com/WordPress/twentytwenty/issues/497#issuecomment-534942966

Also, do these styles still have to be applied?
Could we make the differences or the benefits using the template clear in some way?

**Comment by byalextran** [comment]
does https://github.com/WordPress/twentytwenty/pull/527 address `.alignleft` and `.alignright` as you described above?. 

if so, and assuming my PR is valid, i think additional styling tweaks are needed.

![Screen Shot 2019-09-25 at 22 23 03 PM](https://user-images.githubusercontent.com/455406/65655889-70875b80-dfe3-11e9-9abe-feedb947b2a7.png)

![Screen Shot 2019-09-25 at 22 23 13 PM](https://user-images.githubusercontent.com/455406/65655925-8bf26680-dfe3-11e9-922b-c36a78745aec.png)
