### ISSUE TITLE
Consider adding config for linting tools to ensure consistency

### ISSUE THREAD

**Issue by mor10** [WordPress/twentytwenty#19]
Add config for ESLint, stylelint, PHPCS aligned to WordPress Coding Standards to ensure code consistency during development.

**Comment by pattonwebz** [comment]
I agree consistence between all of us during dev will save headaches nearing commit time.

Related PR: https://github.com/WordPress/twentytwenty/pull/11

**Comment by afercia** [comment]
Remarkable work on https://github.com/WordPress/twentytwenty/pull/163 🎉 

Worth noting the current `index.js` files doesn't pass the `grunt jshint:themes` linting though. If merged in core as is, the build will fail. /Cc @ianbelanger79 

Worth also noting `grunt jshint:themes` does only some partial linting. All [the WordPress JavaScript coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/) need to be met.

As a source of inspiration I wouldn't recommend Twenty Nineteen, which generally has some misalignments with the coding standards. I'd recommend to have a look at Twenty Seventeen instead.

**Comment by ianbelanger79** [comment]
Thanks for the heads up @afercia. I will look into this asap.

**Comment by ianbelanger79** [comment]
The theme is now passing `grunt jshint:themes` closing this issue
