### ISSUE TITLE
Add option to use excerpts on posts page

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/twentytwenty#2]
The Chaplin theme has an option to use excerpts on the default posts page. This option is currently absent from Twenty Twenty. I think it would be a good idea to bring back this option from Chaplin. In fact, I'd prefer if excerpts were used by default. The inability to change this has been a major missing feature in previous default themes, in my opinion.

**Comment by andersnoren** [comment]
@ZebulanStanphill We've talked this over, and decided to add an option for this in the theme settings. It will allow the user to select whether to display the excerpt or the full content of each post on archive pages, with the full content being default.
```
On archive pages, posts show:
- (*) Full text
- ( ) Summary
```

Exact phrasing could be changed if we find a better way to put it. The phrasing above matches the corresponding setting for feeds on the `Settings → Reading` settings page.

We'll add this to a new `Theme Options` Customizer tab, which will also contain the current setting for whether the header search should be disabled (currently in the `Site Header` section).
