### ISSUE TITLE
Disable Search Button only applies to desktop

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#210]
When the Disable Search Button option is enabled,
it only hides the search on desktop, not on smaller screens.

**Comment by carolinan** [comment]
This has been solved and merged, closing.

**Comment by nielslange** [comment]
> Hi, I'm having trouble finding where the option to Disable Search Button is. :(

@andrewtvuong: You can enable/disable the search button via:

`WP Admin —> Appearance —> Customise —> Theme Options`

as seen in 

![2DA9C363-D883-4610-9F3D-C6D10889F6ED](https://user-images.githubusercontent.com/3323310/69131213-8a758400-0ae4-11ea-9a91-a8709c890c7b.png)

**Comment by andrewtvuong** [comment]
@nielslange thanks, I don't know why I kept missing it. New to CSS but went ahead and nuked the style.css already should anyone become interested in the future using

```
/* Search Toggle ----------------------------- */

.search-toggle {
	position: absolute;
	bottom: 0;
	left: 0;
	top: 0;
	display: none !important;
}

.search-toggle .toggle-icon,
.search-toggle svg {
	height: 2.5rem;
	max-width: 2.3rem;
	width: 2.3rem;
	display: none !important;
}
```

**Comment by nielslange** [comment]
@andrewtvuong While this is also a solution, hiding the search icon via themes options is the better choice as it loads less code. In your solution, which is not bad, by the way, both the HTML code of the search icon and the CSS code to hide the search icon are transferred from the server to the client. While it's not much data that you avoid sending, every byte counts when it comes to performance. 

Hiding the search icon via theme options, simply removes the HTML part for the search icon from the site, while hiding the search icon via CSS will require to load the following code, even though nothing is visible to the visitor:

**HTML part**

```
<div class="header-toggles hide-no-js">
  <div class="toggle-wrapper search-toggle-wrapper">
    <button class="toggle search-toggle desktop-search-toggle" data-toggle-target=".search-modal" data-toggle-body-class="showing-search-modal" data-set-focus=".search-modal .search-field" aria-expanded="false">
      <span class="toggle-inner">
        <svg class="svg-icon" aria-hidden="true" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" width="23" height="23" viewBox="0 0 23 23"><path d="M38.710696,48.0601792 L43,52.3494831 L41.3494831,54 L37.0601792,49.710696 C35.2632422,51.1481185 32.9839107,52.0076499 30.5038249,52.0076499 C24.7027226,52.0076499 20,47.3049272 20,41.5038249 C20,35.7027226 24.7027226,31 30.5038249,31 C36.3049272,31 41.0076499,35.7027226 41.0076499,41.5038249 C41.0076499,43.9839107 40.1481185,46.2632422 38.710696,48.0601792 Z M36.3875844,47.1716785 C37.8030221,45.7026647 38.6734666,43.7048964 38.6734666,41.5038249 C38.6734666,36.9918565 35.0157934,33.3341833 30.5038249,33.3341833 C25.9918565,33.3341833 22.3341833,36.9918565 22.3341833,41.5038249 C22.3341833,46.0157934 25.9918565,49.6734666 30.5038249,49.6734666 C32.7048964,49.6734666 34.7026647,48.8030221 36.1716785,47.3875844 C36.2023931,47.347638 36.2360451,47.3092237 36.2726343,47.2726343 C36.3092237,47.2360451 36.347638,47.2023931 36.3875844,47.1716785 Z" transform="translate(-20 -31)"></path></svg>										<span class="toggle-text">Search</span>
      </span>
    </button><!-- .search-toggle -->
  </div>
</div>
```

**CSS part**

```
/* Search Toggle ----------------------------- */

.search-toggle {
	position: absolute;
	bottom: 0;
	left: 0;
	top: 0;
	display: none !important;
}

.search-toggle .toggle-icon,
.search-toggle svg {
	height: 2.5rem;
	max-width: 2.3rem;
	width: 2.3rem;
	display: none !important;
}
```

As less is more, I'd go with hiding via theme options, but, of course, this is your personal choice. 😀

**Comment by andrewtvuong** [comment]
@nielslange very helpful! Will go with theme options then. Just curious if you happen to know how to remove the divider lines between the social media widgets?

**Comment by nielslange** [comment]
> @nielslange very helpful! Will go with theme options then. Just curious if you happen to know how to remove the divider lines between the social media widgets?

I'd say that's something that needs to be addressed using custom CSS. That said, I suggest that you look up https://wordpress.org/support/theme/twentytwenty/ to see if that issue had been reported there already. If not, then please report it there, so that others can benefit from the answer as well. 

This repo is technically retired and should not be used for support purposes. 😉
