### ISSUE TITLE
Not able to close the menu in Tablet and below devices also page is not scrollable

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#211]
As shown in the screenshot below.
Screenshot Url - https://cl.ly/e16eb9acba10
Steps:
1. Check the menu on responsive devices.
2. You can face the issue as shown in the screenshot
3. Screenshot Url - https://cl.ly/2c007072442e

**Comment by ianbelanger79** [comment]
Having a close button in the modal window is necessary IMO. Thanks for reporting this @Swapnildhanrale

**Comment by nielslange** [comment]
According to #246 the close button on tablets and phones should look as follows:

## Tablet:

<img src="https://user-images.githubusercontent.com/8181091/64847365-24b1db00-d60f-11e9-9727-88b3156d8bbd.jpg">

## Phone:

<img src="https://user-images.githubusercontent.com/8181091/64847356-1fed2700-d60f-11e9-907e-c669e1d33a08.png">

**Comment by carolinan** [comment]
Tested on mobile, and I am able to close the menu and able to scroll when the menu
Is too long to fit on screen.

I did feel that perhaps the clickable area for opening and closing is a bit small 
on Firefox. 

*Opera Mini
Chrome
Firefox
Edge
On Android.

**Comment by carolinan** [comment]
Oh and it is still broken when the WordPress admin bar is visible.

**Comment by carolinan** [comment]
> Oh and it is still broken when the WordPress admin bar is visible.

Now fixed
