### ISSUE TITLE
Discussion: Rephrase the Disable Search Button option

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#212]
This is the current text for the search button option in the customizer

----

Settings for the site header.

- [ ] Disable Search Button

_Check to disable the search button in the header._

----

I think it would make more sense for this option to be reversed;
for the search to be enabled by default, with the box checked,
and disabled when unchecked. 

I don't think the word "Button" is needed.

The text could be rephrased to something like:

----

Settings for the site header.

- [x] Enable search

_Uncheck to disable the search in the header._

----

Currently, the Disable Search Button option is in the site header panel.
**-I keep clicking this panel expecting to add a header image.**
And this is is despite knowing very well that the header image panel has a different name :)

**Comment by joyously** [comment]
I suggest the words "Display" or "Show" instead of "Enable", because themes are about showing content, not enabling functionality.
And yes, boolean options should match the logic of "on" means "show" and "off" means "hide", so the code is not convoluted.

**Comment by nielslange** [comment]
Happy to create a PR, in case we want to adjust this behaviour. 😀

**Comment by pattonwebz** [comment]
> I suggest the words "Display" or "Show" instead of "Enable", because themes are about showing content, not enabling functionality.
> And yes, boolean options should match the logic of "on" means "show" and "off" means "hide", so the code is not convoluted.

Agree completely with this. Also what does the option actually save as. Is it truly Boolean `1` and `0` or is it `on` or `off` strings that are stored? What is people preference?

**Comment by nielslange** [comment]
@pattonwebz I've implemented it using `true` as default option.

**Comment by nielslange** [comment]
@carolinan Based on your feedback in https://github.com/WordPress/twentytwenty/pull/227#issuecomment-531202625 I've closed #227 and created an updated PR with #252.
