### ISSUE TITLE
Cover template. Add option to change the color of post-meta

### ISSUE THREAD

**Issue by vbaimas** [WordPress/twentytwenty#218]
We have some issues with accessibility and more specific with color contrast, when the user select the `cover template`, from `single post template`. 

Please, see my example below : 

![add-color-post-meta](https://user-images.githubusercontent.com/5068068/64680050-abd34780-d485-11e9-9507-166a678bae1a.png)

**Comment by andersnoren** [comment]
Yes, the post meta should inherit the white text color of the container on the cover template.

**Comment by carolinan** [comment]
This has been fixed as part of #245, so I am closing the issue. Thank you.
