### ISSUE TITLE
Update structure

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#250]
Things to do:

- [x] Move `template-cover.php` into `templates` folder
- [x] Move `template-full-width.php` into `templates` folder
- [x] Move `twentytwenty-editor-style-block-editor.css` into `assets/css/`
- [x] Move `twentytwenty-editor-style-classic-editor.css` into `assets/css/`
- [x] Rename `twentytwenty-editor-style-block-editor.css` to `editor-style-block.css`
- [x] Rename `twentytwenty-editor-style-classic-editor.css` to `editor-style-classic.css`

I'm currently working on this issue and will create a PR later today.

**Comment by joyously** [comment]
Can you keep the word 'editor' in the names of the css files?
`block-editor.css`
`classic-editor.css`
would be more descriptive.
But maybe switching it around would be better
`editor-style-block.css`
`editor-style-classic.css`

**Comment by nielslange** [comment]
@joyously Sure, let's do that! I really like your second suggestion though! 😀

**Comment by nielslange** [comment]
@carolinan This PR should be good to be merged. 😀
