### ISSUE TITLE
Block: Separator

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#254]
In the design, there are three separators: 

![separators](https://user-images.githubusercontent.com/7422055/64901382-c5001200-d698-11e9-867f-475223447601.png)

These 3 are similar to the default, wide and dots separators and should probably overwrite them.

A second option would be to create these 3 as custom block styles.

Currently, the default style is identical to the wide style, since it is only styled as a hr, not with the class `wp-block-separator`.

**Comment by joyously** [comment]
They are very faint.

**Comment by celloexpressions** [comment]
I agree with @joyously -- let's make sure that these are at least 3:1 (preferably 4.5:1 or more) relative contrast to the (user-selected) background color.

**Comment by andersnoren** [comment]
I've updated the PR to give the separators a contrast of 3:1 with the default background color set. I'm not sure how the implementation of the color contrast relative to background color would work in practice, but there's a related pull request for that here: #249
