### ISSUE TITLE
refactor template files

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#26]
There should not be if statements for template files in content.php. The template files should have the differences.
The header.php shouldn't be checking for search. There should be a search.php that does it differently. (search form doesn't need to be in header, but should be in content area)
The cover overlay should be its own template part, or just the featured image handling should be in one part or one function (easier to filter). Or should the cover overlay be the default instead of a page template?

**Comment by carolinan** [comment]
Having separate template files is also crucial for child themes.
I think this needs to be separated into tasks, where we first identify what templates we need, and the folder structure for it.

search.php is reserved for the search result page and should not be used as a template part for the header search form.

**Comment by joyously** [comment]
I started to do this one, but there are other big PRs that should be merged first.
I propose these steps:
- move pagination.php, content.php, into the parts folder
- split the page-header.php into its two conditions and put it into where it is referenced in content.php
- move the `<article>` and entry-header from content.php to singular.php, index.php, and page templates
- move the featured image to parts/featured-image.php
- move the "single pagination" code from content.php to singular.php, but call it navigation because it's not pagination
- at this point, there's not much left for content.php, so either leave what is left or just copy it to singular.php, index.php, and page templates

Obviously, when moving template parts around, the call to get them needs to be adjusted to match.
This would result in
parts folder with pagination.php, content.php, modal-search.php, modal-menu.php, featured-image.php
theme folder with singular.php, index.php, and page templates, 404.php, header.php, footer.php, comments.php
The code specific to the page templates should be only in the page templates.
It's debatable as to whether a search.php is needed.

**Comment by ianbelanger79** [comment]
This was completed in #168
