### ISSUE TITLE
Consider using arrays for $selector in twentytwenty_generate_css

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentytwenty#267]
`twenty_twenty_generate_css()` currently accepts text strings for the `$selector` parameter. In many of the current uses of this function within the theme, the selector list includes several comma-separated selectors.

Formatting the selector as an array, rather than a string, would make it easier to filter the selectors passed to this function (and reduce the risk of missing or extra commas in this final CSS).  This approach would also improve code readability.

It could also work to accept either a string or an array. I would favor arrays when three or more selectors are used, whereas a string is reasonable for only one or two selectors. `twentytwenty_get_customizer_css()` already has several calls to this function with three or more selectors.

**Comment by acosmin** [comment]
@celloexpressions I tried something 😄  I might have overdone it
