### ISSUE TITLE
Add theme support for responsive embeds

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#269]
Add theme support for responsive embeds.
This would be added to functions.php inside `function twentytwenty_theme_support.`

See
https://developer.wordpress.org/block-editor/developers/themes/theme-support/#responsive-embedded-content

**Comment by joyously** [comment]
If there is some JS for that already, isn't it better to leave it at that so it works in all versions?

**Comment by aristath** [comment]
> If there is some JS for that already, isn't it better to leave it at that so it works in all versions?

It doesn't always work as intended... For my theme I had to write a [custom script](https://github.com/wplemon/gridd/blob/ffea2ca7397cfaa61cccbc086d9d80d894b31834/assets/js/responsive-videos.js) (vanilla JS) to fully support these.

**Comment by joyously** [comment]
Which thing didn't work as intended?

**Comment by carolinan** [comment]
At the moment there is still an issue with the Facebook embed being cut off depending on screen width.

**Comment by ianbelanger79** [comment]
@carolinan can you share a screenshot of a Facebook embed. I can't get Facebook embed's to work on my local install. FWIW I tried adding `add_theme_support( 'responsive-embeds' );` to the functions.php file and it seemed to make embeds less responsive.

**Comment by carolinan** [comment]
![embed](https://user-images.githubusercontent.com/7422055/66097197-c472e100-e59d-11e9-8857-0ea39cec9480.png)

**Comment by pattonwebz** [comment]
I opened a trac issue for this one: https://core.trac.wordpress.org/ticket/48552
