### ISSUE TITLE
Use } instead of endif for consistency reasons

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#270]
The files `header.php` and `index.php` currently contain several `endif` statements instead of closing brackets. While this is fine according to https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style due to consistency reasons, we should go with one style. As the rest of the theme is using `}` I'll change the two files accordingly. PR is on the way. 😁

**Comment by aristath** [comment]
I thought that the alternative syntax was prefered for template files where PHP is mixed with HTML? https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style
Granted it's a little vague there, but traditionally in WP braces are used in PHP-only files and alternative syntax for templates - but with the closing PHP tags on the same line

**Comment by nielslange** [comment]
@aristath Thanks for clarifying this and pointing out https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style. :)
