### ISSUE TITLE
Can the search page show smaller images?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#275]
The featured images overwhelm the search results page. Since the entire use of a search is to find matching posts and pages, it would make more sense if the title and excerpt are not lost among the huge images.
![Search Results for test](https://user-images.githubusercontent.com/7957680/64911407-1636f280-d6e7-11e9-95e5-43ab153a9a2f.jpg)

**Comment by nielslange** [comment]
What about showing title, author and publication date only and removing the rest from the search result page?

![#275](https://user-images.githubusercontent.com/3323310/64912828-c108da00-d702-11e9-8502-72160801a28b.png)

**Comment by joyously** [comment]
I think the excerpt helps to find what to read, without having too much (matches lost in content).
And you can't put dates or authors for Pages.

**Comment by nielslange** [comment]
I see. What about showing the title (with a smaller font) and the excerpt only?

<img src="https://user-images.githubusercontent.com/3323310/64913144-af2a3580-d708-11e9-9032-1d680ac72343.png" width="300px">

**Comment by joyously** [comment]
To me, that looks a lot better. (I think the big titles are overwhelming also.) 
But I'm not the designer.

**Comment by nielslange** [comment]
@andersnoren What are your thoughts on the proposal above? Thus, only showing titles and excerpts, on the search results page, and decreasing the titles font size?

@joyously I'm also not a designer though. 😁

**Comment by andersnoren** [comment]
I think hiding the featured images in the search results is a good idea, but I use the designer veto on the smaller title size :)

**Comment by nielslange** [comment]
Alrighty! Big titles but no featured images it is! 😀
