### ISSUE TITLE
Cover image overlay opacity should use a range control

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentytwenty#276]
The cover image overlay opacity is currently a select control with 11 options at increments of 10%. This would be more appropriate as a range (slider) control, because most users will not care about the numerical value of this option, and the range approach allows for a more-visual interaction. This should also be instant live-previewed in the customizer with `postMessage` for instant feedback.

![image](https://user-images.githubusercontent.com/7875961/64913376-dd514a80-d6f3-11e9-8baa-ab986d13ae33.png)

I'm not set up to create a PR yet, but this is the revised customize control code (someone else can feel free to make this into a PR):

```
/* Overlay Color Opacity --------- */
$wp_customize->add_setting(
	'twentytwenty_cover_template_overlay_opacity',
	array(
		'default'           => 80,
		'sanitize_callback' => 'absint',
	)
);

$wp_customize->add_control(
	'twentytwenty_cover_template_overlay_opacity',
	array(
		'label'       => __( 'Image Overlay Opacity', 'twentytwenty' ),
		'description' => __( 'Make sure that the value is high enough that the text is readable.', 'twentytwenty' ),
		'section'     => 'twentytwenty_cover_template_options',
		'type'        => 'range',
		'input_attrs' => array(
			'min'  => 0,
			'max'  => 100,
			'step' => 10,
		),
	)
)
```

The step of `10` matches the current options; I would suggest using a step of 5 instead for more-granular control. This also transitions the setting to be saved as an integer, and the output should be adjusted accordingly. Also note that the `settings` parameter in the control is not required when the control ID matches the setting ID.

**Comment by joyously** [comment]
I think this is a good idea. Should the min be more than 0? Or max less than 100?

**Comment by acosmin** [comment]
I could probably add this to #258 and also make the necessary changes for `parameter in the control is not required when the control ID matches the setting ID` where it's needed

**Comment by carolinan** [comment]
I think this or some version of it will be part of https://github.com/WordPress/twentytwenty/issues/284 /#249

**Comment by LittleBigThing** [comment]
> I think this is a good idea. Should the min be more than 0? Or max less than 100?

See #470 about this. I would go for 0 as a minimum, but limit it to less than 100%.
