### ISSUE TITLE
Conditional visibility for the cover template customizer section

### ISSUE THREAD

**Issue by celloexpressions** [WordPress/twentytwenty#277]
The cover template settings in the customizer only apply to pages with the cover page template. For best user experience, the recommended practice is to only show settings when the page in the live preview can show the changes. Widgets use this logic in core. Without this functionality, the results of changing these settings are unclear to users.

The customize API includes the `active_callback` parameters in the control, section, and panel objects for this reason. We can add an `active_callback` to the `twentytwenty_cover_template_options` section registration, referencing a new function that detects whether the current page is using the cover page template.

**Comment by joyously** [comment]
I thought it might be better to just make it a global option instead of a page template.

**Comment by carolinan** [comment]
We discussed this very thing yesterday before the issue was opened. 
The decision then was that we should keep it visible but try to make the text clearer.

**Comment by acosmin** [comment]
From my own experience with this, users will open support queries if they don't find this option. It can easily become a support "nightmare". I would leave it as is 😃

**Comment by celloexpressions** [comment]
If this became a broader option that a page template, then we could keep the section visible. As it currently sits, most users won't use (or find) the cover page template. But, in the customizer, they will see this section along with everything else. 

The theme is currently bordering on having too many customizer options for usability, in accordance with the WordPress philosophy. When users are presented with too many options, they are make more decisions during the customization process. Many of these are highly-technical, increasing the burden. Conditional visibility was introduced in core as one approach to combating this issue. The other option is to simplify the user experience and remove this section of options.

A compromise approach would be to keep the section, but add conditional visibility to all of the controls. Then, add a placeholder control with inverted conditional visibility explaining how to use the cover page template, and that additional options are available here if you navigate to one of those pages.

**Comment by carolinan** [comment]
This is also related to the color settings.
If the text color control is replaced with the automatic text color, and the overlay is the accent color,
then what remains is:

Fixed background
Blend mode
Opacity

**Comment by LittleBigThing** [comment]
I agree with @celloexpressions on the fact that we are making things more complicated by always showing the cover template section. But discovering this feature might be even harder. It is not clear what it does now in the Customizer, but it is not clear either in the editor where there is no preview (yet) of the featured image and the cover template when they are set.

> A compromise approach would be to keep the section, but add conditional visibility to all of the controls. Then, add a placeholder control with inverted conditional visibility explaining how to use the cover page template, and that additional options are available here if you navigate to one of those pages.

This latter seems a great approach to make the Cover Template discoverable and explain how it can be set up.

**Comment by joyously** [comment]
I still think it's better for the user to not have to choose the template in each page or post to get this effect. A theme option for how to treat featured images across the site would be easier and less theme lock-in.

**Comment by carolinan** [comment]
After more discussions we have decided to keep the settings visible at all time, as it is currently.

**Comment by andersnoren** [comment]
We've decided to reopen this issue and encourage more discussions. We want to see if there are improvements to be made before release that can help the cover template be easier to understand when in the Customizer. 

A couple of discussion points we would love some thoughts on:

- Would it be possible (and desired) for the preview to redirect to a page set in the cover template when the "Cover Template" Customizer panel is opened?
- If not, would it be possible to display a message when the page currently displayed isn't using the cover template?
- How should the "Cover Template" panel look when there isn't an existing page or post using the cover template at all? Should we include instructions on how to use the template?

Any and all suggestions (in addition to the points above) are much appreciated.

**Comment by joyously** [comment]
I understand why it's done, but as a user, I really don't like when the Customizer loads a different page for me. So I vote No on trying to switch the preview to show a page that has the template, especially because there could be a case of no page having that template.

I still think that the logic would work better and the user has less to change to use it if the Cover Template isn't a template but it is an option for how featured images are shown. I'm saying that choosing that option would affect all instead of just the ones that have a meta field with that template name. (I much prefer themes to be unifying for the site instead of specific to individual posts or pages.)

**Comment by acosmin** [comment]
I like the idea of previewing/redirecting to a post, I made a PR #812

**Comment by karmatosed** [comment]
I do think most users will be confused seeing a template they aren't using in the customizer.

> How should the "Cover Template" panel look when there isn't an existing page or post using the cover template at all? Should we include instructions on how to use the template?

I don't think there should be a panel until that happens, if possible.
