### ISSUE TITLE
Close icon for search extends outside of mobile view

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#279]
Here's the screen capture showing the X icon on the right side getting cut off

![twentytwenty-mobile-search](https://user-images.githubusercontent.com/1679025/64915226-a51c2d00-d730-11e9-9858-4c893ab50fc8.png)

**Comment by andersnoren** [comment]
Fixed by #280

**Comment by carolinan** [comment]
@okpierre what is your wordpress.org username?
