### ISSUE TITLE
skip-link style

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#28]
It would be better to use the `screen-reader-text` class on the skip-link than to define a separate class of `skip-link`. This is what it is for.

**Comment by carolinan** [comment]
The screen-reader-text _was_ added but has disappeared again ...

**Comment by carolinan** [comment]
I have added the screen-reader-text class, but did not remove the skip-link or faux-button classes.
We need to think about the best placement for the link. The screen-reader-text places the skip link in the top right.

**Comment by joyously** [comment]
Testing again with the latest master, I am not seeing the skip link in the top right. It is full width and scrolls with the page (not sure if it should or not).

![skip-link-style](https://user-images.githubusercontent.com/7957680/65378587-0045a680-dc80-11e9-94d9-0c5b8b5fbc21.gif)

**Comment by carolinan** [comment]
No, I meant that when the skip-link class is removed a per your suggestion, then skip link is shown at the top right.
The screen reader text class places it there.
