### ISSUE TITLE
Change the excerpt more string from: (more...) to Read more

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#288]
The title is kind of self explanatory.
![more](https://user-images.githubusercontent.com/54663751/64925623-c42fc300-d7f3-11e9-8774-3a5429ad151e.png)

**Comment by nielslange** [comment]
@yannickiki How can this be reproduced? I created a post and added the `More` block and the text within the `More` block can be edited:

<table>
<tr>
<td>Editor:
<br><br>

![#288 - editor](https://user-images.githubusercontent.com/3323310/64927661-ab1b1800-d7db-11e9-820d-0ba90e1d540e.png)

</td>
<td>Frontend:
<br><br>

![#288 - frontend](https://user-images.githubusercontent.com/3323310/64927663-ae160880-d7db-11e9-9989-91d52ba457b9.png)

</td>
</tr>
</table>

**Comment by joyously** [comment]
The More block can be edited, but the More tag cannot. In the old days, it is changed with a filter. I'm not sure how that filter affects blocks that have been customized.

**Comment by nielslange** [comment]
@joyously I seem to be unable to trigger the more tag. Are you able to trigger it, and if so how?

**Comment by joyously** [comment]
What do you mean by trigger? The More block is just a More tag surrounded by block comment markers.
Either way, you have to be on an archive page showing full content to see it.

**Comment by nielslange** [comment]
By triggering I meant reproducing. I wasn’t able to see the MORE tag anywhere. I’ll take a closer look later.
