### ISSUE TITLE
Add an option inside the customizer to display the title on the main posts page

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#289]
Currenty the main posts page doesn't display the page title. It would be a nice feature to have the possibility to display the page title like "Blog", "Ideas & thoughts", "Articles"... and would add consistency as all the other pages display the title.

**Comment by joyously** [comment]
My vote is that it's not needed.

**Comment by nielslange** [comment]
Thanks for suggesting this, @yannickiki. I kind of like the idea to show the title on the blog posts page, but would not implement it as part of https://github.com/WordPress/twentytwenty/projects/1.

**Comment by yannickiki** [comment]
@nielslange or maybe instead of an option,  adding a filter in the index.php file could do the trick:
`$archive_title = apply_filters( 'twentytwenty_get_the_archive_title', $archive_title );`

I think it would be a good compromise.

**Comment by nielslange** [comment]
As mentioned before, I like the idea. But given the tuff timeline of the Beta 1 release, I would address this enhancement later.

**Comment by celloexpressions** [comment]
I agree that this is not needed. A filter seems reasonable, but a user-facing option will have more consequences than benefits for usability.

**Comment by dianeco** [comment]
@nielslange I agree with the comments above, a filter would be a nice & reasonable feature. I've created a test site where all the pages have a color banner (home, about, contact, single post, archive) except for the blog index which kind of breaks the consistency of the design. In this case a filter to display the title on the blog page would have been useful.
