### ISSUE TITLE
`async` JavaScript, add ability to `async` and `defer`

### ISSUE THREAD

**Issue by mor10** [WordPress/twentytwenty#29]
The enqueued JavaScript should be set to `async` to improve performance and prevent render blocking. Core ticket [12009](https://core.trac.wordpress.org/ticket/12009) extends `wp_scripts_add_data` to allow `async` and `defer` as options. WP Rig [has a solution](https://github.com/wprig/wprig/blob/master/inc/Base_Support/Component.php#L145-L173) which gracefully steps back if/when core adopts this modern loading practice.

**Comment by joyously** [comment]
Couldn't it just be added in the footer?

**Comment by pattonwebz** [comment]
It could be added to the footer but for some fairly technical reasoning that I do not fully understand I am lead to believe it's much more preferable to have it as easly as possible. Particularly this is a performance improvement when http/2 is enabled.

**Comment by mor10** [comment]
Short answer: using `async` or `defer` is current best-practice. Adding JS in the footer is an old pattern which is now an anti-pattern. 

`async` and `defer` allow for tighter control of when the script loads. In this circumstance, `async` ensures the file is downloaded and read concurrently with HTML rendering and rendering is only stopped during execution. Placing JS in the footer delays loading until after the HTML document is read in full which causes rendering delay.

More info here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#Attributes
