### ISSUE TITLE
Use only CSS and remove javascript to make the page cover full height

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#290]
For the fullscreen page cover: it would be better to use the following CSS code:
`.screen-height {
   min-height: 100vh;
}`

**Comment by fabiankaegy** [comment]
I believe iim already does :) its just uses js to provide a fallback for older browsers that don't support vh units:

https://github.com/WordPress/twentytwenty/blob/6dcf4884d40ae5419b282cc6b914e11857b06b52/style.css#L838

**Comment by joyously** [comment]
Does this account for admin bar? (which has a different height on mobile and desktop)

**Comment by yannickiki** [comment]
Yes indeed, it already uses 100vh. I don't think a fallback is necessary: https://caniuse.com/#feat=viewport-units
and if it's really needed, the script should only targets older browsers.

**Comment by yannickiki** [comment]
#163 has removed the js code for the full height cover.
