### ISSUE TITLE
List Item Style Should Match Edit View

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#294]
Here's a post with image on the left and list item to the right. 

After saving, the list item does not match with the edit view.

### Post view
![twentytwenty-list-item-spacing-post-view](https://user-images.githubusercontent.com/1679025/64928378-8330b200-d7e5-11e9-876b-9bc4c58b243e.png)

### Edit view
![twentytwenty-list-item-spacing-edit-view](https://user-images.githubusercontent.com/1679025/64928379-84fa7580-d7e5-11e9-93b1-6e538bf02d77.png)

It should match the styling of the edit view since it allows for enough spacing

**Comment by joyously** [comment]
You will have this trouble anywhere you have float and a list. It's a really tricky thing that depends on total margins and padding and width.

**Comment by nielslange** [comment]
@joyously I was able to address this issue in https://github.com/WordPress/twentytwenty/pull/296 by increasing the margin of the image, which then pushes the list further to the right.

<table>
<tr>
<td>Before:
<br><br>

![#294 - before](https://user-images.githubusercontent.com/3323310/64931527-10d0c980-d807-11e9-8e2c-70777ccfe9bf.png)

</td>
<td>After:
<br><br>

![#294 - after](https://user-images.githubusercontent.com/3323310/64931530-13cbba00-d807-11e9-8f5e-a26ca19df8bf.png)

</td>
</tr>
</table>

**Comment by joyously** [comment]
You show before and after, but the issue is written on editor and front.

**Comment by nielslange** [comment]
The view in the editor was fine before and after. Only the view in the frontend showed the issue. That's why I only created screenshots of the frontend. I should have mentioned that directly though.

**Comment by okpierre** [comment]
tested fix by @nielslange and it addresses the issue - thanks!

**Comment by nielslange** [comment]
@okpierre Thanks for testing this PR! 😀

@carolinen I see that you’ve added the label `Duplicate` but I cannot see a related issue. Could you point me in the right direction or have you added that label accidentally?

**Comment by carolinan** [comment]
> @okpierre Thanks for testing this PR! 😀
> 
> @carolinan I see that you’ve added the label `Duplicate` but I cannot see a related issue. Could you point me in the right direction or have you added that label accidentally?

I think it must have been https://github.com/WordPress/twentytwenty/issues/215

**Comment by nielslange** [comment]
@carolinan Guess we can remove the `Duplicate` label then, as #215 is a different case.  On the other hand, I just see that this PR is no longer required after @andersnoren added heaps of CSS fixes.
