### ISSUE TITLE
Use core functionality for single navigation

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#300]
Core has a function `the_post_navigation()` to display the navigation to next/previous set of posts. It implements screen reader text for navigation elements.

**Comment by nielslange** [comment]
@yannickiki What's wrong with the current implementation? As far as I know, the `aria-label` in https://github.com/WordPress/twentytwenty/blob/ef21a6df7125a84dcfdcf61bdd4119d6a80331ef/template-parts/navigation.php#L25 is interpreted by screen readers to tell users what element this is. Having said that, I think it's a good idea to adjust that label from `Post` to `Post navigation`. I'll create a PR for that the next minutes.

cc: @afercia

**Comment by yannickiki** [comment]
@nielslange I thought that themes should use core functionalities if they exist.

**Comment by nielslange** [comment]
@yannickiki I created #309 to adjust the `aria-label` and send a PR with https://github.com/WordPress/twentytwenty/pull/310.

**Comment by nielslange** [comment]
> @nielslange I thought that themes should use core functionalities if they exist.

Good point, @yannickiki. That's probably an issue someone from the theme review team can clarify.

cc: @carolinan, @pattonwebz

**Comment by afercia** [comment]
>  I think it's a good idea to adjust that label from Post to Post navigation

Please don't 🙂 Screen readers already announce the `<nav>` element type as "navigation". The aria-label should not contain the word "navigation" again, to avoid it gets repeated unnecessarily:

<img width="1310" alt="Screenshot 2019-09-16 at 18 27 27" src="https://user-images.githubusercontent.com/1682452/64975634-c7888480-d8af-11e9-8309-447d36b6662c.png">

**Comment by nielslange** [comment]
@afercia Do I understand you correctly that screen readers first read the `aria-label` and then the element? Thus, a screen reader would read `Post, navigation` automatically, right?

**Comment by nielslange** [comment]
Closed based on https://github.com/WordPress/twentytwenty/issues/309#issuecomment-531854465

**Comment by afercia** [comment]
@nielslange yes: the order may vary across screen readers and browsers combinations and also depends on the type of element (links, buttons, form fields) but all screen readers announce both the label (aria-label, etc.) and the element type.

**Comment by nielslange** [comment]
Thanks for explaining this to me, @aferica. I’ve already closed the PR that i opened for that.
