### ISSUE TITLE
Fix translations in credits.

### ISSUE THREAD

**Issue by juanfra** [WordPress/twentytwenty#301]
Currently, we're not translating the URL to WordPress but the doc for translators says that.

We should be making the URL to WordPress translatable, so each locale can have their own link. And at the same time being consistent with the doc for translators. Not sure if the usage of `_x()` is correct there.

**Comment by pattonwebz** [comment]
Resolved by: https://github.com/WordPress/twentytwenty/commit/eec0bc0d4d89a5a7ee6aab1509164f516504890a

**Comment by pattonwebz** [comment]
Thanks for pointing this out and for the PR. I merged that in just there so this is now in line with past core themes.

**Comment by juanfra** [comment]
Thank you, William! :)
