### ISSUE TITLE
Line length seems too narrow

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#307]
The line length which is defined by the combination of the text width (58rem) and the font size (2.1rem on desktop) seems too narrow. The number of characters per line is in the low range of the ideal range. Text inside 2 columns is also too narrow (by default the columns block width is set to 58rem). Imho, I think the readability can be improved by increasing the number of characters per line.

Increasing the text width from 58rem to 68rem could improve readability without changing the overall feeling of the theme. I’ve built page layouts using blocks (group, columns, media & text) and I’ve found that the line length of Chaplin is more versatile. 68rem would give a line length quite similar to Chaplin.
  
@andersnoren What do you think?

**Comment by andersnoren** [comment]
Sorry @yannickiki, I appreciate the input but disagree with you that widening the entry content container would improve readability. I think it would be a good idea to reduce the font size within column blocks, but the width of the entry content column stays as it is.

Closes #308 and 307.

**Comment by yannickiki** [comment]
@andersnoren Sorry for the confusion, for some reason I had the Inter font set for the body (which is way bigger). With the serif font, I agree with you! :)

**Comment by andersnoren** [comment]
@yannickiki No worries! I appreciate you creating the issue all the same :)
