### ISSUE TITLE
Consider breaking up CSS to load at component level

### ISSUE THREAD

**Issue by mor10** [WordPress/twentytwenty#31]
Component-level in-body stylesheets can improve performance, especially if certain components only load conditionally, or only load below the fold in the view. 
See https://jakearchibald.com/2016/link-in-body/ and https://github.com/wprig/docs/blob/master/documentation/css.md#progressive-loading-of-css

In-body `<link>` elements and progressive loading of stylesheets is supported in Chrome and Firefox and falls gracefully back all the way to ancient browsers.

This can be wired up to allow for critical loading, conditional template- and component-based loading, and modular loading. WP Rig has existing code which can be ported in whole or in part for this purpose. 

cc @felixarntz

**Comment by joyously** [comment]
Seems like the stylesheet loading on the first page takes the hit and is cached thereafter, so why bother trying to break it up and figure out the pieces for each page? It wouldn't work well for use with plugins that load more content with ajax.

**Comment by mor10** [comment]
Exactly because the first page takes the full hit of loading all CSS when maybe only 25% of that CSS is necessary. Splitting up CSS is a significant performance enhancement and also allows for tighter and clearer modularity during development. It also allows for lighter weight cache updates in case a style rule is modified because the entire sheet doesn't have to be reloaded every time.

**Comment by ianbelanger79** [comment]
We are closing this issue due to time constraints.
