### ISSUE TITLE
Update Author Based On Profile Setting

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#311]
Post author does not change based on profile settings

Here it is set to FirstName but showing up as Nickname

Change to Username. Post displays Nickname
 
### profile settings
![twentytwenty-user-profile](https://user-images.githubusercontent.com/1679025/64992314-a1f47e80-d8a1-11e9-8c6b-95b733dabaf1.png)

### post view
![twentytwenty-by-author-not-changing](https://user-images.githubusercontent.com/1679025/64992412-dbc58500-d8a1-11e9-9d04-ac368861e65d.png)

**Comment by nielslange** [comment]
@okpierre Feel free to test the fix for this issue as created on https://github.com/WordPress/twentytwenty/pull/313

**Comment by okpierre** [comment]
@nielslange Looks good on my end! Thanks!

**Comment by nielslange** [comment]
@okpierre No worries and thanks for helping out! 😀 You can simply open this issue again. 😉
