### ISSUE TITLE
alignleft and alignright are reversed in RTL

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#317]
The alignleft class should always be on the left, and alignright should always be on the right, even in RTL languages.
![alignments-reversed](https://user-images.githubusercontent.com/7957680/65003879-00305a00-d8c0-11e9-8f7a-75942c2d74cf.jpg)

**Comment by joyously** [comment]
See https://rtlcss.com/learn/getting-started/why-rtlcss/#processing-directives

Need `/*rtl:ignore*/` for alignleft and alignright.

(Are the editor style sheets processed for LTR?)

**Comment by nielslange** [comment]
> See https://rtlcss.com/learn/getting-started/why-rtlcss/#processing-directives
> 
> Need `/*rtl:ignore*/` for alignleft and alignright.
> 
> (Are the editor style sheets processed for RTL?)

@joyously Feel free to test my PR for this issue.
