### ISSUE TITLE
Use `wp_body_open` for output of bypass block

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#32]
We should move the skip link to be output via the `wp_body_open` filter instead of coding it directly to the header.

This is the method that I would like to go with for all default themes. We have a ticket ready for commit on twentyeleven for reference: https://core.trac.wordpress.org/ticket/47891

This method of adding skip links avoid the issues which are becoming common in themes that #16 issue notes and #17 resolves.

**Comment by joyously** [comment]
If you do it that way, it should have a higher priority than the default of 10. I mean bigger number so that it is after whatever is added to the hook with the default.

**Comment by joyously** [comment]
I personally would rather see it in the template than in a filter. It makes it easier for users to grok.
My theme has an option to not show the header, so it has to conditionally output the skip-link. I think that's easier to see with it straight in the template file.

**Comment by joyously** [comment]
I think the theme outputs all the HTML, so the new hook is for plugins to get in front with whatever (probably for AMP). It doesn't make sense to me that the theme needs to put anything on that hook.

**Comment by ernilambar** [comment]
Agree with @joyously here. This hook is not supposed to be used to inject HTML like we are doing now. 
 
Ref - https://make.wordpress.org/core/2019/04/24/miscellaneous-developer-updates-in-5-2/

**Usage of this hook should be reserved for output of unseen elements like <script> tags or additional metadata. It should not be used to add arbitrary HTML content to a page that could break layouts or lead to unexpected situations.**

**Comment by pattonwebz** [comment]
I remember writing that guideline... Didn't think it would come back to bite me :p

This is an initally unseen element, added to a location it is convenient via a hook. I think this is fine.
