### ISSUE TITLE
table style : editor versus front end

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#320]
Tables are styled differently in the classic editor stylesheet than in the block editor and the front end.
Which one is matching the design?

Classic editor: (this is a table, not a table block, but it looks the same as a table block)
![classic-editor-table-style](https://user-images.githubusercontent.com/7957680/65005972-52c14480-d8c7-11e9-995e-cb4081a05165.jpg)

Block editor: (this is a table block)
![block-editor-table-style](https://user-images.githubusercontent.com/7957680/65005970-5228ae00-d8c7-11e9-9b7a-d39d29e97870.jpg)

Front end: (this looked the same whether it was a block or not)
![front-end-table-style](https://user-images.githubusercontent.com/7957680/65005971-52c14480-d8c7-11e9-962a-e71fe4ded3b1.jpg)

**Comment by joyously** [comment]
With the latest changes, the Classic Editor now matches the front end. Block editor remains the same as before.
![Edit-table-classic-editor](https://user-images.githubusercontent.com/7957680/65376668-3b3be000-dc68-11e9-9dde-f252f3f6bf4f.jpg)

**Comment by ianbelanger79** [comment]
Possible fix for this #699

**Comment by joyously** [comment]
Mostly the difference is `table-layout: fixed` and the borders, not padding.
