### ISSUE TITLE
Add accent color to next and previous post navigation

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#322]
In the design, the next and previous post navigation use the accent color, so this needs to be updated. 

![author](https://user-images.githubusercontent.com/7422055/65011576-4a432b00-d914-11e9-8754-eb3ec237e829.png)

**Comment by nielslange** [comment]
@carolinan Feel free to test my PR via https://github.com/WordPress/twentytwenty/pull/331 😉
