### ISSUE TITLE
Button block styling

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#332]
This screenshot is of a post that contains button blocks, but it is on WP 4.9.11. The one that should be centered is not centered, and the rounded and outline styles are not rounded or outlined.
![button-styles](https://user-images.githubusercontent.com/7957680/65074193-ee9b9080-d959-11e9-9cde-c60a91eafe14.jpg)

This is the same post in the Classic editor, where the color styles are missing as well.
![buttons-in-classic-editor](https://user-images.githubusercontent.com/7957680/65074192-ee9b9080-d959-11e9-8672-d47de759aca4.jpg)

**Comment by joyously** [comment]
With the latest changes, it is slightly different, but still not correct. This is on WP 4.9.11.
![button-styles-4 9](https://user-images.githubusercontent.com/7957680/65376556-d3d16080-dc66-11e9-8773-ae2ddd60844b.jpg)

But the editor looks better:
![Edit-button-block-classic-editor](https://user-images.githubusercontent.com/7957680/65376564-00857800-dc67-11e9-91e7-322e1f9ae56c.jpg)

**Comment by carolinan** [comment]
I have confirmed that this this is still an issue in 4.9.11.

**Comment by nielslange** [comment]
The buttons should have the styles `Default` and `Outline` now and the button style `Squared` had been removed with https://github.com/WordPress/twentytwenty/pull/577#event-2670403963.

**Comment by carolinan** [comment]
If a button is centered **using** the 4.9 editor, it is centered correctly both in the editor and front
because the style gets added inline.

The left aligned button is still not in the same place on the front and in the 4.9 editor.

The outline button shows correctly in the 4.9 editor, but still has a solid color on the front.
