### ISSUE TITLE
Site title won't display in customizer

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#335]
The logic used to display the site title is based on if `get_the_logo()` returns a value or not.

However `get_the_logo()` always returns a value in the customizer even when no logo is set. This is because a placeholder is needed for selective refresh when logo is added/removed.

This causes the site title to never display in the customizer because the test on `$logo` is always true.

**Comment by ianbelanger79** [comment]
Fixed in #355
