### ISSUE TITLE
$pagination_classes not used on pagination block?

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#338]
Were these lines left as a remnant of a previous way to handle the offsets for when only one of the prev/next items show? When I do add the classes here manually I am not certain they correctly centre the numbers.

https://github.com/WordPress/twentytwenty/blob/0073a94d641706cfac1b956217fdc5ccf503b014/template-parts/pagination.php#L33-L51

**Comment by carolinan** [comment]
See #99
