### ISSUE TITLE
The `Continue Reading` button should be centered in index view

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#344]
![Image of Yaktocat](https://i.imgur.com/Ntni8ld.jpg)

It currently displays like the one on the left side

**Comment by carolinan** [comment]
Centering the (fake)button does not match the design mockup:

![readmore](https://user-images.githubusercontent.com/7422055/65173807-e7ef4500-da4f-11e9-95f0-ef4dbfa950c8.png)

**Comment by acosmin** [comment]
@carolinan It doesn't look that great with the title and post meta center aligned, my 2c 😄

**Comment by andersnoren** [comment]
@acosmin Sorry, disagree with you on this one :) Appreciate you creating the issue though.

**Comment by acosmin** [comment]
no problem 😄 it can always be adjusted with some custom css if the user wants to.
