### ISSUE TITLE
Edge Menu and Search Icons get cutoff on the top

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#349]
![edge-icons-cutoff-top](https://user-images.githubusercontent.com/34601694/65176092-1bb37600-da22-11e9-98c1-7f73efa9baaa.PNG)

It's a small amount, but is noticeable.

**Comment by carolinan** [comment]
The menu icon is OK but the search is still cut off at the top in Edge.
300% zoom in photoshop. Left: Chrome. Right: Edge
![search](https://user-images.githubusercontent.com/7422055/65791249-a3575e00-e161-11e9-9969-4c580e83b480.png)

**Comment by carolinan** [comment]
This has been fixed, closing the issue.
