### ISSUE TITLE
Add build process for linting and code optimization

### ISSUE THREAD

**Issue by mor10** [WordPress/twentytwenty#35]
Related: #19 and #34 

Consider adding a build process with Babel for JS and [PostCSS](https://www.npmjs.com/package/postcss) and [`postcss-preset-env`](https://www.npmjs.com/package/postcss-preset-env) for CSS to streamline and simplify builds. PostCSS includes Autoprefixer. The build process can also automate code linting.

The build process can either be straight-up NPM scripts or a basic Gulp process. I do not recommend Webpack for this as it is primarily for packaging JavaScript bundles which isn't applicable in this context. 

cc @ataylorme

**Comment by senadir** [comment]
why do we need a js build process? also, we can use @wordpress/scripts to handle all of those things to us behind the scenes and be actively developed outside the theme

**Comment by dingo-d** [comment]
> The build process can either be straight-up NPM scripts or a basic Gulp process. I do not recommend Webpack for this as it is primarily for packaging JavaScript bundles which isn't applicable in this context.

While Webpack is a bundler primarily, it's usage is exactly to use things like PostCSS and other tools that can be used for building JS and CSS. Since core uses Webpack, it would be beneficial to use it for the build process, just to get people familiar with it.

**Comment by ataylorme** [comment]
I would like to advocate for using more modern CSS, like custom properties, instead of Sass. Nothing against Sass but I believe the core themes should show what is capable with the CSS spec. Modern browsers support quite a bit and PostCSS can be used to provide support for legacy browsers.

Regarding PostCSS and Webpack, I don’t think it has to be one or the other. There is [a PostCSS loader for Webpack](https://github.com/postcss/postcss-loader).

**Comment by mor10** [comment]
Absolutely for custom properties and modern CSS over Sass. As you well know.

**Comment by dingo-d** [comment]
Can we use custom CSS properties? https://caniuse.com/#feat=css-variables
IE is not supporting them (surprise, surprise! xD)

**Comment by ataylorme** [comment]
> Can we use custom CSS properties? https://caniuse.com/#feat=css-variables
IE is not supporting them (surprise, surprise! xD)

That is _exactly_ what PostCSS is for.

> PostCSS Preset Env lets you convert modern CSS into something most browsers can understand, determining the polyfills you need based on your targeted browsers or runtime environments.

[See the PostCSS preset](https://github.com/csstools/postcss-preset-env#postcss-preset-env-) for an example of conversions done.

The benefit, over Sass or something else, is that modern browsers will use the syntax and features they support. That means, for non-IE browsers custom properties (among many other features).

**Comment by carolinan** [comment]
Linters are in place, closing this, thank you.
