### ISSUE TITLE
JS TypeError when search modal is not enabled

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#357]
If `Show search in header` is not enabled and you click on any actionable item (like the menu toggle), the console will output: `Uncaught TypeError: Cannot read property 'classList' of null at HTMLDocument.<anonymous> (VM6903 index.js:209)`

**Comment by nielslange** [comment]
cc: @fabiankaegy

**Comment by ianbelanger79** [comment]
Was fixed in #356
