### ISSUE TITLE
z-index issue with the search modal and template-cover

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#362]
1. Open a page that has template-cover selected
2. Open the search modal
3. The post meta (title, excerpt) can be selected without closing the modal.

![](https://i.imgur.com/Tcm9jU7.png)

**Comment by acosmin** [comment]
Looks like `.overlay-header #site-header` is overwriting `#site-header`'s z-index.

`.overlay-header #site-header { z-index: 9999 }` should do the trick.

**Comment by nielslange** [comment]
Working on your fix now, @acosmin! 😀

**Comment by nielslange** [comment]
@acosmin With https://github.com/nielslange/twentytwenty/commit/415fdd328c55168c2bb410f00c81fd290fefd4cc I created a fix but used `z-index: 2` instead of `z-index: 9999` as that worked already. Personally, I prefer keeping the z-index numbers as low as possible. 

Feel free to test the PR now. 😉

**Comment by acosmin** [comment]
seems to work, one issue I noticed is that below 1000px, after clicking the mobile menu, the header isn't visible anymore, it's just a white space 😄

**Comment by ianbelanger79** [comment]
It's worth a note that the sub nav menus also end up behind the page title on the cover template, if they are long enough.

**Comment by nielslange** [comment]
@acosmin and @ianbelanger79 Thanks for reporting this. I'll update the PR accordingly.
