### ISSUE TITLE
Sub menu toggles doesn't work on mobile with one menu set to both locations

### ISSUE THREAD

**Issue by andersnoren** [WordPress/twentytwenty#365]
If you set both the "Expanded Menu" and the "Mobile Menu" locations to the same menu, the sub menu toggles doesn't work on mobile. It seems like the sub menu toggles in the mobile menu targets the sub menus in the expanded (desktop) menu.

**Comment by anace** [comment]
Maybe the submenu toggles should have different class names for the two menu locations.

(And I know it is too late for this discussion, but maybe the expanded menu and the mobile menu should share the same menu location).

**Comment by anace** [comment]
I think the best solution is to merge the expanded and the mobile menu locations and simplify the file `modal-menu.php`.

Please tell me what you think.

**Comment by andersnoren** [comment]
We had multiple discussions about the pros and cons of menu structure before ending up with the current one (#164), so I don't think going back on that now is in the cards. 

For this bug, it looks like we just need to make sure that `twentytwenty.toggles.toggle` targets all elements that match the selector set on the toggle element.

**Comment by acosmin** [comment]
We might want to wait for this to be merged :) to avoid conflicts: https://github.com/WordPress/twentytwenty/issues/410

**Comment by ianbelanger79** [comment]
Fixed by #453
