### ISSUE TITLE
Page jumps left/right when opening the search modal on desktop

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#366]
**Steps to reproduce**

1. Open a long page, e.g. a blog posts page
2. Open the search modal

**Expected behaviour**

The underlying page remains on the same spot.

**Current behaviour**

The underlying page moves to the right when the search modal gets opened and back to the left when the search modal gets closed.

https://cld.wthms.co/i3nfbR

It seems I can tackle this issue by adding `overflow: overlay;` to the `body` element. I'll give it a try to see if my assumption works out. 😀

**Comment by acosmin** [comment]
Might be related to this PR and its issue https://github.com/WordPress/twentytwenty/pull/360

**Comment by ianbelanger79** [comment]
This happens when you open the menu modal as well. It's due to the scrollbar being removed when a modal is open. `overflow: overlay;` on the body does not work because opening the modal adds `overflow: hidden;` to the body as inline style

**Comment by nielslange** [comment]
@acosmin Yes, that sounds related to #360 but the page still jumps despite your PR had been merged.

@ianbelanger79 On my end the page does not jump any longer when I add `overflow: overlay;` to the `body` element as that reduces the `body` width resp. ensures that the scrollable sidebar does not push the `body` to the left. Shall I create a quick PR so that you can check out what I mean?

**Comment by joyously** [comment]
[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow) has thumbs-down for `overlay` 
> Only supported in WebKit-based (e.g., Safari) and Blink-based (e.g., Chrome or Opera) browsers.

**Comment by nielslange** [comment]
@joyously Absolutely. I just saw https://developer.mozilla.org/en-US/docs/Web/CSS/overflow. `overflow: overlay;` seems to be the wrong decision to fix this issue.

**Comment by acosmin** [comment]
tried something, needs testing :)

**Comment by nielslange** [comment]
@acosmin Did you tried it in #360?

**Comment by nielslange** [comment]
While I don't like `!important` statements, adding `overflow: auto !important` to the `body` element should also fix the issue.

**Comment by acosmin** [comment]
@nielslange we've added `overflow: hidden` with the purpose of not allowing scrolling 😄 that's against it...

@andersnoren any thoughts on this?

**Comment by nielslange** [comment]
@acosmin Is there any other approach to avoid scrolling without having the page jumping if the modal opens?

**Comment by acosmin** [comment]
@nielslange I tried in #367 - it gets the scrollbar width and adds it as a padding-right, resulting in no jumping 😄

**Comment by nielslange** [comment]
Nice, let me check that PR, @acosmin!

**Comment by acosmin** [comment]
The scrollbar has to eventually show up 😄

**Comment by acosmin** [comment]
there was an issue with the prev PRs if you didn't have the adminbar on :) so sorry for that.

I tried another solution, please try it.

**Comment by acosmin** [comment]
hmm, doesn't work with cover template 😞

**Comment by acosmin** [comment]
@ianbelanger79 @nielslange I recreated the [Chaplin](https://andersnoren.se/themes/chaplin/) version, almost the same style :) if you can test it. Works with the admin bar on my end and cover template.

**Comment by ianbelanger79** [comment]
Fixed by #367

**Comment by nielslange** [comment]
Just came back from Florida and spend a few days with my parents in Germany before I head back to Indonesia. As my parents invited me for a true German dinner I haven’t had time to test your PR on time, @acosmin! I’m glad to hear this issue got fixed so fast though! 😀
