### ISSUE TITLE
missing text domain in page walker

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#372]
This translation needs a text domain.

https://github.com/WordPress/twentytwenty/blob/8e28522319df7bd45433e8a4f04438722e7d4786/classes/class-twentytwenty-walker-page.php#L82

**Comment by acosmin** [comment]
It shouldn't be, it's the [default WP one](https://github.com/WordPress/WordPress/blob/e1996633228749cdc2d92bc04cc535d45367bfa4/wp-includes/class-walker-page.php#L155).

**Comment by nielslange** [comment]
Shouldn't all translations be using text domains, @acosmin?

**Comment by acosmin** [comment]
In this case I assume you would want the translation coming from core, it already has it in multiple languages...
