### ISSUE TITLE
style.css Tags list

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#373]
The Tags list in style.css must accurately reflect what the theme provides.
I suggest this list:
blog, one-column, custom-colors, custom-logo, custom-menu, editor-style, featured-images, footer-widgets, full-width-template, rtl-language-support, theme-options, threaded-comments, translation-ready, block-styles, wide-blocks

Reference: https://make.wordpress.org/themes/handbook/review/required/theme-tags/

**Comment by nielslange** [comment]
@joyously I also added the tag `custom-background` as the Twenty Twenty theme supports that. Feel free to test this PR now. 😀

**Comment by joyously** [comment]
Looking at this again, we need to remove `sticky-post`. The sticky post is not visually different. It just has a small label saying "Sticky post", which in my opinion, is very lame.
@carolinan

**Comment by nielslange** [comment]
What're the criteria for a sticky post label, @joyously? Does it need to be visually different to justify the label? And shouldn't we rather improve the visualisation than removing the label?

**Comment by joyously** [comment]
Yes, it needs to be visually different to use that Tag. (see link mentioned above)
This issue is about making the Tags list match the theme. I didn't suggest any design changes to be able to use another Tag.

**Comment by nielslange** [comment]
Thanks for clarifying this! I should have looked it up, before asking that question. 😀 Do you wanna create another issue, so that I can create a PR to fix this issue, @joyously. Or shall I create another issue?

**Comment by joyously** [comment]
Whatever.
I wrote this issue already, so you can reopen it, or revert the PR or just write another PR to actually fix it, or whatever.
