### ISSUE TITLE
Display the Site Title without the Tagline (unable to display logo with no tagline)

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#389]
Currently if the Logo is set, it replaces the Site Title (which is logical). Therefore the option "Display Site Title and Tagline" is used only for display/hide the Tagline.

If there is no Logo, the option "Display Site Title and Tagline"  has no real use, because a website needs to display either a Logo or a Site Title.

I suggest to change the option "Display Site Title and Tagline" to  "Display Tagline" which would allow to display only the Site Title. Currently the only way to achieve it, is to empty the tagline input which isn't ideal because it removes the tagline from the page <title> tag (search engines).

**Comment by carolinan** [comment]
The tagline is not visible in small screens. Having an option to display something that is hidden anyway is a bit strange.

**Comment by pattonwebz** [comment]
@yannickiki I agree that the option 'Display Site Title and Tagline' is not entirely accurate when you are using a logo and that it's not ideal to have to delete the tagline to display it.

That control comes from core though and if we modify it then that breaks the core provided translations. Perhaps we could add a new option to allow toggle only the description separately but that may get complicated.

Since the behavior here forces you to delete a site tagline if you do not want it visible I think we can consider this a bug.

**Comment by carolinan** [comment]
I am not sure I understand the issue correctly.

The custom logo already has the parameters for the classes that should be hidden when the logo is enabled. 
`'header-text' => array( 'site-title', 'site-description' ),`

So the tagline should not be showing when the logo is visible, and the checkbox option to display it should already be disabled. No additional option should be needed here,
is it only a CSS selector specificity mismatch?

**Comment by joyously** [comment]
I don't think the core code hides title or tagline when using a logo. Are those parameters for hiding?
But then, this theme wasn't using core code for logo -- see #128.

**Comment by carolinan** [comment]
Yes it's for hiding elements when the logo is displayed.

https://developer.wordpress.org/themes/functionality/custom-logo/
https://make.wordpress.org/core/2016/03/10/custom-logo/

**Comment by carolinan** [comment]
@yannickiki I am still not sure I fully understood the problem. Has this been fixed now?

**Comment by carolinan** [comment]
@yannickiki please confirm if this has been solved or what the remaining problem is.

**Comment by yannickiki** [comment]
@carolinan Sorry I didn't see your previous message. I guess there is nothing the theme can do, it's more core territory. I guess we can close this issue. (I don't know if it's up to me to close it 🙂)
