### ISSUE TITLE
Full and wide aligned Pullquote Block p element not positioned correctly 

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentytwenty#39]
When using the Pullquote block and setting alignment to either wide or full, the block moves to the left, but the `p` element does not stay centred or use the available space. the `cite` does.

I believe it might be the case because the `p` element inherits the styles from `.entry-content p` and there is a max width set to that. 

<img width="1920" alt="Screenshot 2019-09-07 at 07 26 09" src="https://user-images.githubusercontent.com/20684594/64470282-1d875a80-d141-11e9-8e6a-7b9cd580313c.png">

**Comment by ianbelanger79** [comment]
This does not appear to be an issue anymore.
