### ISSUE TITLE
Change responsive header layout when search is hidden

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#390]
Currently if we choose to hide the search in the header, the Logo/Site Title is centered with the menu icon at the right.

Maybe it would be better to put the logo to the left.  @andersnoren What do you think?

![menu](https://user-images.githubusercontent.com/54663751/65319388-d3ba5d80-db9f-11e9-8e17-b7ae6f9f3c09.png)

**Comment by nielslange** [comment]
Personally, I prefer the centred title even if the search icon is hidden on mobile.

**Comment by andersnoren** [comment]
@yannickiki Sorry for the late reply. Agreed. It looks odd compared to the default structure of Twenty Twenty, but visitors won't have that prior knowledge and will except it to be displayed to the left on mobile.

**Comment by andersnoren** [comment]
Fixed by #404.
