### ISSUE TITLE
Social Menu display isn’t consistent

### ISSUE THREAD

**Issue by dianeco** [WordPress/twentytwenty#391]
Currently the Social Menu is displayed inside the modal menu and inside the footer only if a Footer Menu is set. Therefore if we don’t set a Desktop Expanded Menu nor a Footer Menu, the Social Menu appears on mobile (inside the modal menu) while it appears nowhere on desktop. 

A solution would be to always display the Social Menu in the footer (without the need to set a Footer Menu).

![footer01](https://user-images.githubusercontent.com/44895380/65321620-f8fd9a80-dba4-11e9-9ce1-ea8afe247696.png)
***
![footer02](https://user-images.githubusercontent.com/44895380/65321624-fa2ec780-dba4-11e9-97b1-5539398666b2.png)
***
```
if ( $has_footer_menu || $has_social_menu ) {
	?>

	<div class="footer-top<?php echo esc_attr( $footer_top_classes ); ?>">
		
```

**Comment by c4rl0sbr4v0** [comment]
I will take this one :-)

**Comment by andersnoren** [comment]
Thumbs up from me. Have you had a chance to get started on this one yet, @c4rl0sbr4v0?

**Comment by c4rl0sbr4v0** [comment]
I'm starting it right now @andersnoren

**Comment by andersnoren** [comment]
@c4rl0sbr4v0 Awesome, thanks!

**Comment by carolinan** [comment]
Is the social menu supposed to be aligned to the left or right when the footer menu is not added?

**Comment by acosmin** [comment]
@carolinan it should probably be centered in that case

**Comment by carolinan** [comment]
It is not centered when there is a footer menu, so centering it would not be consistent.

**Comment by acosmin** [comment]
😄 it could be centered and the buttons bigger, like 2x. My 2c

**Comment by carolinan** [comment]
Ok, since the underlying issue has been fixed, let's close this.
Thank you!
