### ISSUE TITLE
Comments Reply Title seems too big

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#396]
If a post has a long title, I think the comment reply title is a bit overwhelming.

![comment](https://user-images.githubusercontent.com/54663751/65331140-7254b780-dbbc-11e9-88e5-ea1b21de303a.png)

I prefer the original version of the comment where the  `comment-reply-title` was at 4rem and the `comment-notes` "Your email address will not be published Required fields are marked *" at 1.8rem. (imo a helper text should no be larger than the running text)

![comment-original](https://user-images.githubusercontent.com/54663751/65331175-87314b00-dbbc-11e9-8308-2e2d816dacca.png)

**Comment by andersnoren** [comment]
Yeah... I agree with you, @yannickiki. I think it works better centered since it mirrors the layout in the header, but I'll create a PR for reducing the font size and title margins a bit.

Thanks for questioning the design on this stuff, even if I shoot some of your suggestions down :)

**Comment by yannickiki** [comment]
@andersnoren No problem, I know the rule and I’m perfectly fine with you calling the shots. I think you are doing an amazing job! 

(and for the one you shot down I agree with your decision :) )
