### ISSUE TITLE
Make sure that all props are in before Beta 1

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#399]
We need to collect all props before the beta 1 on Monday Sept 23rd. This should include any design feedback or feedback of any kind, issues submitted and PR's submitted.

**Comment by jeffpaul** [comment]
@ianbelanger79 I'll pick this one up, but happy to have others note here folks who should get a prop (with ideally a link to the issue/pr/contribution to confirm).

**Comment by ianbelanger79** [comment]
Thanks @jeffpaul,

Kjell and Alan Cole should both be included, they helped guide us in the beginning

**Comment by ianbelanger79** [comment]
Oh and of course @karmatosed

**Comment by pattonwebz** [comment]
`@senadir` needs added. I forgot to add the name early on when I committed the RTL tooling:  https://github.com/WordPress/twentytwenty/pull/65

**Comment by pattonwebz** [comment]
`@juanfra` | WP Username: `juanfra` https://github.com/WordPress/twentytwenty/pull/177#issuecomment-533829966

**Comment by ianbelanger79** [comment]
Fixed in #464
