### ISSUE TITLE
Concerns with the use of the Inter typeface family

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/twentytwenty#4]
Coming from my comment on the Make post;
https://make.wordpress.org/core/2019/09/06/introducing-twenty-twenty/#comment-36918

One privacy concern here is the use of a CDN hosted font (Inter) as this exposes the user IP to GitHub servers and Cloudflare CDN. It was my understanding that bundled themes would move away from Google Fonts and other hosted font services for privacy and performance reasons. As discussed in the core#46170 ticket;
https://core.trac.wordpress.org/ticket/46170#comment:2
*Would Inter support bundling it with the theme to remove these concerns?

Another concern with the use of Inter is the known readability issues on Chrome (specifically on Windows) for variable fonts as mentioned on their FAQ;

The variable font renders poorly in Chrome
There are some known issues with variable fonts in Chrome, in particular on Microsoft Windows. You may see an effect similar to “ink bleed” where shapes overlap, for instance where the vertical and horizontal stems meet in “+” or “t”. On Windows you may in addition see incorrectly placed glyphs that looks like poor kerning (spacing between characters) and even some glyphs being lower or taller than other glyphs. It is recommended to avoid using variable fonts on Chrome. See the Chromium bug tracker for a list of variable-font related issues.

Reference – https://rsms.me/inter/
Reference (Chromium bug tracker) – https://bugs.chromium.org/p/chromium/issues/list?can=2&q=variable+component%3ABlink%3EFonts

Sorry to be the first to raise a flag I just wanted to have these concerns voiced early so they can be accounted for before work has commenced.

**Comment by andersnoren** [comment]
@garrett-eclipse No apologies needed for raising concerns! Raising concerns is good, and the earlier the better. 

The Inter font files will be included in the theme files themselves, so they won't be loaded from a remote CDN. We probably should have been a bit clearer about that in the Make post.

As for the readability issues with variable fonts in Chrome on Windows, I think we'll have to keep an eye on them as development progresses, discuss how serious they are and see what options we have to address them. If they are serious enough, it would probably be worth considering what options we have to selectively exclude Chrome on PC from loading the variable font version of Inter.

**Comment by garrett-eclipse** [comment]
Thanks @andersnoren I appreciate the follow-up there, and that's great news about bundling the font files into the theme itself definitely removed my concerns with privacy and externally loaded fonts.

As to the readability issues I'm glad you have your eye on them and will leave it in your trusted hands.

All the best
P.S. Would you like me to close this thread, you've addressed my privacy concerns but wasn't sure if I should leave this open to track any testing of the font on Chrome for Windows?

**Comment by andersnoren** [comment]
@garrett-eclipse No problem! I think it's best we leave this issue open for now, so we can use it for discussions about the variable fonts rendering in Chrome on Windows and related Inter-specific topics.

**Comment by garrett-eclipse** [comment]
Thanks @andersnoren sounds like a plan
