### ISSUE TITLE
Fix outstanding WordPress JavaScript Coding Standards

### ISSUE THREAD

**Issue by ntwb** [WordPress/twentytwenty#410]
As part of #363 for the ESLInt lint tests to pass the following issues require resolving:

```shell
/home/travis/build/WordPress/twentytwenty/assets/js/index.js

    5:1   error  Unexpected var, use let or const instead                     no-var

    9:27  error  'NodeList' is not defined                                    no-undef

   10:2   error  'NodeList' is not defined                                    no-undef

   23:15  error  'Event' is not defined                                       no-undef

  103:8   error  'adminBar' is never reassigned. Use 'const' instead          prefer-const

  104:5   error  'newHeight' is defined but never used                        no-unused-vars

  193:2   error  Expected method shorthand                                    object-shorthand

  193:21  error  Unexpected space before function parentheses                 space-before-function-paren

  194:49  error  Unexpected space before function parentheses                 space-before-function-paren

  195:4   error  Unexpected var, use let or const instead                     no-var

  196:4   error  Unexpected var, use let or const instead                     no-var

  197:4   error  Unexpected var, use let or const instead                     no-var

  198:4   error  Unexpected var, use let or const instead                     no-var

  253:50  error  Unexpected mix of '*' and '+'                                no-mixed-operators

  253:58  error  Unexpected mix of '*' and '+'                                no-mixed-operators

  452:7   error  Unexpected var, use let or const instead                     no-var

  554:10  error  'twentytwentyGetQueryStringValue' is defined but never used  no-unused-vars

  671:26  error  'HTMLElement' is not defined                                 no-undef

  690:21  error  Unexpected mix of '*' and '+'                                no-mixed-operators

  690:25  error  Unexpected mix of '*' and '+'                                no-mixed-operators

  693:17  error  Unexpected mix of '*' and '+'                                no-mixed-operators

  693:23  error  Unexpected mix of '*' and '-'                                no-mixed-operators

  693:35  error  Unexpected mix of '*' and '-'                                no-mixed-operators

  693:41  error  Unexpected mix of '*' and '+'                                no-mixed-operators
```

To test `index.js` with ESLint checkout the #363 PR and run the following:

> `npm run lint:js`

cc: @acosmin @fabiankaegy could you both take a look at fixing these issues as you're both familiar with the code here from your work in #163 please 🙇🏼‍♂️

**Comment by acosmin** [comment]
@ntwb did it, but this will not work for IE11 (older browsers) if you don't build it for es5

**Comment by ntwb** [comment]
> @ntwb did it, but this will not work for IE11 (older browsers) if you don't build it for es5

Ouch, I forgot about that, we should be using the ESLint `es5` ruleset, I'll get that fixed tomorrow, per this I'll close this #415 & #417 as we dont want to have to do that, and I suspect there might be a few other issues from the previous PR

Apologies @tm-const and @acosmin and thanks

**Comment by Ismail-elkorchi** [comment]
@acosmin @ntwb Can't we just write the code in ES6 and use the build script in `@wordpress/scripts`  package to transform the code in ES5 syntax ?

**Comment by ianbelanger79** [comment]
We made the decision early on in the building of this theme to stick with ES5 to encourage more people to contribute and we were not planning on using build tools for anything other than linting.

**Comment by Ismail-elkorchi** [comment]
@ianbelanger79 as @afercia says in https://github.com/WordPress/twentytwenty/pull/281#issuecomment-532864231 : building is necessary. 

The Gutenburg team made an incredible job to simplify and abstract all the complexity of a building step to make the code easier to write and to read, and transform it to ES5 code that is compatible with WordPress's minimum target for browser support. 

I don't understand why should we take the difficult road, while there is a much simpler one !  

See : https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/
See : https://make.wordpress.org/core/2019/03/25/building-javascript/

**Comment by joyously** [comment]
What is the target WP version?
And, "easier to write and to read" is a relative thing.

**Comment by Ismail-elkorchi** [comment]
> What is the target WP version?

Building assets has nothing to do with WordPress version, it's about browser support as defined in : https://make.wordpress.org/core/handbook/best-practices/browser-support/

> And, "easier to write and to read" is a relative thing.

It may be, but the WordPress Handbook says the opposite :

> There are a few reasons to use ESNext and the extra step. First, it makes for simpler code that is easier to read and write. Using a transformation step allows for tools to optimize the code to work on the widest variety of browsers.

Source: https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/

**Comment by joyously** [comment]
> Building assets has nothing to do with WordPress version,

Well, no, the tools you are referring were only added in a particular WP version. So if you want to support versions before that, you can't rely on those tools.

> Handbook says the opposite

That's not the opposite, you quoted it already. "Easy" is relative to the developer and what they have learned thus far.

**Comment by Ismail-elkorchi** [comment]
> Well, no, the tools you are referring were only added in a particular WP version. So if you want to support versions before that, you can't rely on those tools.

That is not true ! The build script in the `@wordpress/scripts` package can be used with all the WordPress versions that supports `wp_enqueue_script()`.

> That's not the opposite, you quoted it already. "Easy" is relative to the developer and what they have learned thus far.

What I quoted does not say that easiness and simplicity are relative to what the web developer has learned ; instead, it says that it will make anyone in the WordPress community write and read less code, since the build step will take care of generating the code in the ES5 syntax for older browsers like IE, and that the developers do not need anymore to fix the inconsistencies between the wide variety of browsers that the developer should target, which is not a relative thing.

**Comment by joyously** [comment]
> The build script in the @wordpress/scripts package can be used with all the WordPress versions that supports wp_enqueue_script().

Themes are not allowed to use external resources except Google Fonts.
