### ISSUE TITLE
How to move post_meta to bottom of post in child theme

### ISSUE THREAD

**Issue by maxcady** [WordPress/twentytwenty#414]
The following function won't work
`function twentytwenty_the_post_meta( $post_id = null, $location = 'single-bottom' ) {
		echo twentytwenty_get_post_meta( $post_id, $location ); 
	}`

How can I change the location of post_meta in a child theme?

**Comment by andersnoren** [comment]
@maxcady You can use the following filters to modify which post meta is displayed in which location:

```
twentytwenty_post_meta_location_single_top
twentytwenty_post_meta_location_single_bottom
```

**Comment by maxcady** [comment]
cool, thank you!
