### ISSUE TITLE
Add screenshot

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#43]
Show the beauty of this theme by adding a screenshot:

<img width="417" alt="Screenshot 2019-09-07 at 09 42 54" src="https://user-images.githubusercontent.com/3323310/64471611-0140e900-d154-11e9-8072-ddd5db32b328.png">

**Comment by carolinan** [comment]
A screenshot has been added. Maybe it is a temporary screenshot, but I'm closing this issue.
