### ISSUE TITLE
First look - initial feedback -

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#454]
Hey

I just downloaded the version that is available as of this moment. (Sunday 22nd September.)
I will openly comment on various things that I notice while previewing Twenty Twenty through the customizer.

Site title and tagline sit beside each other on the same line.

<img width="1287" alt="Screen Shot 2019-09-22 at 09 42 58" src="https://user-images.githubusercontent.com/5323259/65384027-9085f900-dd1d-11e9-9ccf-398298eb9dff.png">

It would be nice to have the tagline below the site title. As the tagline to me is the subheading to the site title.

<img width="1287" alt="Screen Shot 2019-09-22 at 09 46 08" src="https://user-images.githubusercontent.com/5323259/65384183-49990300-dd1f-11e9-85d2-908a29bd079c.png">

Search icon is much bigger then the menu text. Is there really need for the word "Search" to be mentioned? As I do believe it has become a common practice to click the magnify glass to search the site.

In the sidebar:
"Uncheck to hide the search in the header." 
This is really telling. Showing is when the user clicks the checkbox and sees the result. I am puzzled why the sentence is there.

"Search results always show the summary."
Then there is an option to click Full text or Summary. What about removing the sentence and having the default to Summary? Then the user can select to change if they want to do so.

My guess that the above helps accessibility. But I am also guessing that this is not needed to show openly but have a accessible "label" with the text instead.

---> What I miss under theme option section is an option to show related internal posts.

**Cover template Section**
My initial feeling without knowing too much about this feature is that creating a page/post in Gutenberg should be able to take care of this feature. 

I am seeing some very huge featured images that cover the full page.

Previous and next post bottom links.
I look at the below and wonder why the // in the bottom and top borderline.
To me it feels like an assumption. I am also seeing the same line on the blog page between the posts.

<img width="1042" alt="Screen Shot 2019-09-22 at 10 10 30" src="https://user-images.githubusercontent.com/5323259/65384324-63d3e080-dd21-11e9-852f-57f3e75990bb.png">

One thing that would be nice to have is a preheader/topbar menu area for social links or anything else.

I am not able to activate and publish the theme at this time.

**Comment by carolinan** [comment]
Hi
Yes the _Show search_ option has a known bug, the option is meant to be enabled (checked) by default.

Text for icons is not only an accessibility feature:
https://www.nngroup.com/articles/icon-usability/
https://axesslab.com/icons-ruining-interfaces/

Did you mean that there is an error preventing you from publishing?

**Comment by paaljoachim** [comment]
Hei Carolina

My concern was all the added extra text. Be it the Search word under the magnify glass and the additional text in the sidebar as I mentioned.

Yes. I see that I am getting an console error. I will create a new issue for it.

**Comment by carolinan** [comment]
I think the only remaining thing is to look over the texts for the customizer options, so I am closing this.
