### ISSUE TITLE
Left aligned text is cut off in full width blocks

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#459]
Left aligned text inside full width blocks are missing a left margin or padding, so the text is cut off:

![half](https://user-images.githubusercontent.com/7422055/65385900-a2bf6180-dd34-11e9-87d5-7334e49c9d69.png)

If I add a background color to the group block, there is a large left padding:

![half2](https://user-images.githubusercontent.com/7422055/65385950-6f310700-dd35-11e9-8231-0ffa0b9ddbce.png)

**Comment by ianbelanger79** [comment]
Fixed in #707
