### ISSUE TITLE
New enhancement - Top/preheader toolbar

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#463]
Hey

It would be nice to have a preheader toolbar area. To add specials, social menu or other things.
Thanks.

**Comment by nielslange** [comment]
Isn't that something that can easily be achieved via child theme or plugin, e.g. https://wordpress.org/plugins/top-bar

**Comment by omhps** [comment]
For cover page there should be an option to chose image overlay color in page.

**Comment by carolinan** [comment]
@omphs are you not able to find the option in the customizer?

It has its own section, it is not under colors.

**Comment by omhps** [comment]
> @omphs are you not able to find the option in the customizer?
> 
> It has its own section, it is not under colors.

yeah i changed the color using customizer. But it's a suggestion that if it could be in every page section then user have more flexibility to generate multi color pages.

**Comment by nielslange** [comment]
@omhps Would you mind creating a separate issue for this as it's not related to `New feature suggestion - Top/preheader toolbar`. 😀

**Comment by omhps** [comment]
> @omhps Would you mind creating a separate issue for this as it's not related to `New feature suggestion - Top/preheader toolbar`. 😀

Sure @nielslange

**Comment by paaljoachim** [comment]
Hey Niels. @nielslange 
Yes. It can be created with a child theme or a plugin. For users who decide on using the new default theme it would be good to go through and notice which features would be helpful to include. If it is supposed to be a bare bones theme then including extras such as a preheader/top bar should not be included. It goes back to the vision for the theme. Hopefully it will be a worthy theme and not one that is rushed and could use more time then it seems to be getting. One could always move the theme to WP 5.4 if that is needed to be sure that it gets the treatment it needs.

**Comment by nielslange** [comment]
@paaljoachim Thanks for your explanation. I see that @pattonwebz already added the label `enhancement` to this issue. Do you like to implement this feature and create a PR for it?

**Comment by paaljoachim** [comment]
Thanks @nielslange 

I would like to but my skills are in the UI/design area not in coding. 
It also looks like it is too late.

**Comment by nielslange** [comment]
@paaljoachim While it's too late for `Beta 1` it should not be too late for `Beta 2`. What about if you create the mockup and write down the requirements and I implement it? ;)

**Comment by paaljoachim** [comment]
The thought is here that we are adding widget areas to where we can place Gutenberg blocks.
That means a preheader could have opening hours, social menu and other things that are needed.  It could use a background color that should be easy to add. 

I am working on a mockup to show how it can look.

**Comment by paaljoachim** [comment]
Here is an example.

![Preheader-mockup](https://user-images.githubusercontent.com/5323259/65504133-a5ea5700-dec6-11e9-91fb-3c1706365285.jpg)

**Comment by andersnoren** [comment]
Sorry guys, but this goes beyond post-beta fixes. I'm not saying having such an area would have been a bad idea, but we would have needed to have added it before the Beta 1 deadline.

**Comment by paaljoachim** [comment]
I would suggest asking for more time to improve the theme. The more I dig into it the more I also see it needs design improvement.

**Comment by nielslange** [comment]
@andersnoren That's why @pattonwebz labelled this issue as `enhancement`.

**Comment by pattonwebz** [comment]
I am happy to reopen this and label it as a tracking issue for the future.

**Comment by pattonwebz** [comment]
I do feel like this kind of change is not something we should focus on during the beta 2 phase and if this is added it's likely to be added much later. Personally I feel like this is an idea child theme feature however let's keep discussions open if people have ideas to share or things to talk about :D

**Comment by paaljoachim** [comment]
Should I close the issue?
