### ISSUE TITLE
For cover page there should be an option to chosse image overlay color from page settings..

### ISSUE THREAD

**Issue by mafzal9** [WordPress/twentytwenty#469]
Hi,

During my testing phase i check that i can change the overlay color from customizer but unable to change in a page setting, User is only able to choose one color for whole website. According to my suggestion if there is an option in every page then user have more power to create multi color cover pages.

**Comment by joyously** [comment]
The theme option makes sense to unify the look of the site. 
The user can already make each page individually colored by using the Cover Block.

**Comment by omhps** [comment]
> The theme option makes sense to unify the look of the site.
> The user can already make each page individually colored by using the Cover Block.

@joyously  yes it's a good method. but my question is if one person having a website of 6 pages and he wants to use different color for different cover pages then what's the solution ?

**Comment by joyously** [comment]
In my opinion, the cover page template should be removed, and the option in the Customizer should be for Featured Images across the site.
If a user wants 6 pages to have the cover image in different colors, they can easily put a Cover block in each page and choose a different color for each. 
Making things specific to pages is the editor's job, and the theme should stay out of it. Making pages unified for the whole site is the theme's job, and the editor should stay out of it.

Just my 2 cents.

**Comment by mafzal9** [comment]
> In my opinion, the cover page template should be removed, and the option in the Customizer should be for Featured Images across the site.
> If a user wants 6 pages to have the cover image in different colors, they can easily put a Cover block in each page and choose a different color for each.
> Making things specific to pages is the editor's job, and the theme should stay out of it. Making pages unified for the whole site is the theme's job, and the editor should stay out of it.
> 
> Just my 2 cents.

Agreed

**Comment by mafzal9** [comment]
@pattonwebz  added suggestion to Design and @ianbelanger79  added it to enhancement.
