### ISSUE TITLE
Editor styling of group block should reflect the style of the block on the page

### ISSUE THREAD

**Issue by fabiankaegy** [WordPress/twentytwenty#47]
In the Editor the content of a full width group block also is full width. But on the page itself they are still centred and the width of the main content. Both places should work the same way.  

<img width="1920" alt="Screenshot 2019-09-07 at 10 23 32" src="https://user-images.githubusercontent.com/20684594/64472115-af02c680-d159-11e9-9534-c182bbbf4ee8.png">
<img width="1920" alt="Screenshot 2019-09-07 at 10 23 46" src="https://user-images.githubusercontent.com/20684594/64472116-af02c680-d159-11e9-9261-7532ff820ff4.png">

**Comment by carolinan** [comment]
This has been fixed, closing. Thank you.
