### ISSUE TITLE
Consider limiting opacity for cover template to under 100%

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwenty#470]
When the Cover Template page/post template is chosen, the featured image is overlayed with a customizable color layer. The color and the opacity of the overlay can be adjusted in the Customizer in a separate Cover Template section (currently).

The color overlay uses the [`mix-blend-mode` CSS property](https://caniuse.com/#feat=mdn-css_properties_mix-blend-mode) to create interesting filter effects for the image. This property is, however, not supported by IE and Edge. This means that the result is quite different in IE and Edge than expected. For example, adjusting the value for the property (for example, from multiply to hue or anything else) will not result in a different effect. This might be mentioned in the description to avoid confusion. Or we could drop the possibility to modify the value for the property.

Moreover, there can be a problem with the visibility of the featured image when the opacity is set to 100%. In this case, the image is completely covered by the color overlay in IE and Edge. The overlay opacity is set to 80% by default (`opacity: 0.8`), so this is less of a problem. To avoid completely covering the image, we could consider limiting the opacity setting to max. 90%.

**Comment by LittleBigThing** [comment]
> Some browsers, like Internet Explorer and Edge, only support the "Normal" mode.

I just noticed that there is already a mention about non-supporting browsers when choosing the blend mode value in the Customizer. This is great and it could be the way to go. Although I did not notice it obviously. :-)

We might consider making 'normal' the default value instead of 'multiply'. This would give us defaults that are supported by all major browsers.

**Comment by pattonwebz** [comment]
It could be cool to do browser support detection. on the frontend and adjust accordingly. We did not add any feature detection scripting to the theme however maybe we could handle it purely via CSS?

**Comment by LittleBigThing** [comment]
Yes, we did something like that for Twenty Nineteen using [`@supports`](https://developer.mozilla.org/en-US/docs/Web/CSS/@supports) in CSS. I am not sure it would help in this case since the user has a lot of freedom choosing the settings.

For Twenty Nineteen, there was a fixed setting with no opacity of the overlays, which resulted in an invisible featured image in IE and Edge. We applied some opacity for browsers not supporting `mix-blend-mode`. You can see it here: https://github.com/WordPress/twentynineteen/blob/b604f127c2cae10bd48bbbec0fbbbff2cd31f957/style.css#L2372
vs.:
https://github.com/WordPress/twentynineteen/blob/b604f127c2cae10bd48bbbec0fbbbff2cd31f957/style.css#L2377
Different effect, but the image was at least visible and the text readable.

The problem here is that the user won't know what (s)he will have on the other browser. When using a non-supporting browser, (s)he won't see the filter effect when setting up the site. And the other way around, when setting it up in a supporting browser (with 100% opacity), (s)he will probably be surprised that the image is not visible at all in IE or Edge. That's why I was suggesting a lower max. opacity than 1 (or 100%) or at least clearer defaults.

> Some browsers, like Internet Explorer and Edge, only support the "Normal" mode.

In this description, it is at least unclear what those browsers do when only supporting 'normal' mode and not the other modes.

**Comment by carolinan** [comment]
We also discussed removing this option completely. I don't recommend doing any more work on this until a decision has been made.

**Comment by ianbelanger79** [comment]
The Twenty twenty team discussed this issue this morning and we have decided that the `blend-mode` option will be removed, but opacity is going to stay. We also want to use range controls from 0 - 90 for the opacity, with increments of 5.

**Comment by LittleBigThing** [comment]
Thanks!
So if I understand correctly, the option to adjust the type of blending will be removed and we keep multiply for mix-blend-mode?

Great decision for the opacity I think.

**Comment by LittleBigThing** [comment]
I have just updated the PR #473 as I understood the decision.

I feel that we would need to add some JS to make the changes for the opacity preview immediate. Otherwise, it is hard to see the difference.
