### ISSUE TITLE
Consider removing support for background-image

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/twentytwenty#480]
Using a background image can make a website less accessible. Considering all the efforts that has been made to keep the content accessible depending on the background colors chosen, I would suggest to remove the option of setting a background image in the Customizer. It would also make the Customizer options more limited. This option can be easily added using a child theme.

We did the same for Twenty Nineteen.

**Comment by jarretc** [comment]
If a website owner is concerned about accessibility they have the option to not use a background image or use one that wouldn't make the design less accessible. However, to completely remove a feature that allows site owners to customize their site they way they see fit doesn't make any sense.

It doesn't hurt anybody leaving the option available.

**Comment by LittleBigThing** [comment]
I certainly agree with that. Therefore, we allow the site owner to customise the site's background color. And we keep the text readable automatically based on the background color. The one thing we would miss when removing the option of a background image is adding subtle background patterns. Or a subtle background image that does not interfere with the text.

We should probably add the label 'needs decision'. :-)

**Comment by ianbelanger79** [comment]
We will be removing the background image option, if someone would like to work on a PR for it.

**Comment by LittleBigThing** [comment]
I’d like to. ☺️
