### ISSUE TITLE
Rename widget areas to "sidebar-1" and "sidebar-2"

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentytwenty#481]
https://github.com/WordPress/twentytwenty/blob/bbfc3702bc621efe71e4b9a22e9911e99ba81c99/functions.php#L331-L353

When switching themes, WordPress tries to map previous widget areas to the new theme, see `wp_map_sidebars_widgets()`. Unfortunately, the current naming ("footer-one" and "footer-two") are preventing this.

**Comment by joyously** [comment]
We discussed this before. There is a mapping for "footer", so that should work. I don't think it should be named sidebar if it's not on the side.

**Comment by pattonwebz** [comment]
In testing this there are quite a lot of themes that contain `footer-one` but there are a lot more themes that have `sidebar-1` as their names.

Personally I feel like the semantics of labelling as the _footer_ areas could be handled by the labels - with names mapped to whatever is deemed most appropriate.

**Comment by pattonwebz** [comment]
OK so after looking at this and doing various searches on the existing directory I found that the best option is to swap the ids of the menus to be `sidebar-1` and `sidebar-2`. 

This is based mostly on the numbers of themes that utilise these exact names. Firstly for core themes there are several million installs where they sync but this pair is also the most common in non-core themes as well.

Some general match numbers on basic searches:
![Screenshot from 2019-09-26 14-23-50](https://user-images.githubusercontent.com/3902039/65691811-6c058600-e069-11e9-9c25-3ce10c40f612.png)

[('|")(sidebar-1|sidebar-2)('|")](https://wpdirectory.net/search/01DNPVH4D3ZNNDSPWY99CJGJ7V)
[('|")(footer-one|footer-two)('|")](https://wpdirectory.net/search/01DNPTPYTN39CXSRQ5YTSJYFFX)
