### ISSUE TITLE
Move tagline below Site title

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#486]
Hey

The tagline is most often used as a subheading to the title. In Twenty Twenty the tagline is on the same line giving the same importance as the site title.

![Screen Shot 2019-09-24 at 08 02 30](https://user-images.githubusercontent.com/5323259/65485344-e388b900-dea1-11e9-953e-a1efd6528e82.png)

New suggestion:
![Twenty-Twenty-Tagline-below-Site-Title](https://user-images.githubusercontent.com/5323259/65485608-9b1dcb00-dea2-11e9-8397-f749835d24da.jpg)

**Comment by andersnoren** [comment]
Hi @paaljoachim,

I appreciate you creating the issue, but I believe the smaller font size, reduced font weight and paler text color helps communicate that it serves as a subheading to the site title.

**Comment by paaljoachim** [comment]
Everything in the header becomes one long line. 

![Screen Shot 2019-09-24 at 09 05 42](https://user-images.githubusercontent.com/5323259/65489008-8e9d7080-deaa-11e9-8f7a-4af3ce8527f4.png)

It could use more depth.
![Twenty-Twenty-Tagline-below-Site-title](https://user-images.githubusercontent.com/5323259/65489451-7da12f00-deab-11e9-9fac-6db36f945026.jpg)

**Comment by paaljoachim** [comment]
Hey @andersnoren 

It would be helpful to add an option in the customizer to move the Tagline below the Site title.

**Comment by joyously** [comment]
I think it's fine the way it is. This design is "decisions, not options".
What does it do when you use a logo?
What does it do when either the title or tagline are very long?
