### ISSUE TITLE
Using Cover template and white background shows white text

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#488]
I notice that a similar issue has earlier been raised and it seems that specific thing has been taken care of.
#44 

Using cover template and changing Image overlay background color to a very light color hides the text. Making it barely visible.

![Screen Shot 2019-09-24 at 08 45 32](https://user-images.githubusercontent.com/5323259/65487734-ce168d80-dea7-11e9-83df-c7afa68e608f.png)

Changing the image overlay background color to for instance grey shows the white text.

![Screen Shot 2019-09-24 at 08 44 36](https://user-images.githubusercontent.com/5323259/65487666-a4f5fd00-dea7-11e9-8a52-944892110c7a.png)

**Comment by carolinan** [comment]
@paaljoachim since there is now a text color option for the cover block, I do not think this is an issue.
Can you test the latest version (from Github)?

**Comment by paaljoachim** [comment]
Hi @carolinan Carolina

That is a good point.

I have testet the latest version and the only issue I have now is that adding a dark background image the default black text is hidden. There is no option in the colors section for text.
