### ISSUE TITLE
Sub menu background colors

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#493]
Hey

It looks like the default background colors in the sub menu is black.
![Screen Shot 2019-09-24 at 09 02 34](https://user-images.githubusercontent.com/5323259/65489750-12a42800-deac-11e9-8d23-4cf68a579369.png)

Can this react to the background image being used so that it harmonizes better with it?
Meaning can the blue background seen above also in some way also be reflected in the submenu background color? So that the black background color automatically switches to a bluish hue that is similar to the blue background.

**Comment by andersnoren** [comment]
I think that could be a nice enhancement to the cover template, but we would need to expand the `twentytwenty_get_customizer_css()` and `twentytwenty_get_elements_array()` to handle it, which might be on the heavy side for a pretty limited use case. I'm leaving this open as an enhancement if someone wants to take it on.

**Comment by carolinan** [comment]
I think these colors should always be white on black or black on white to keep a high enough contrast, depending on the _header background color._

The cover template does not use the _header background color._ and would need to keep the correct contrast against the overlay color.
