### ISSUE TITLE
Add missing documentation to action and filter hooks

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentytwenty#494]
Not all filters are documented, for example https://github.com/WordPress/twentytwenty/blob/bbfc3702bc621efe71e4b9a22e9911e99ba81c99/inc/custom-css.php#L59 or https://github.com/WordPress/twentytwenty/blob/bbfc3702bc621efe71e4b9a22e9911e99ba81c99/template-parts/content-cover.php#L62.

See https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#4-hooks-actions-and-filters for best practices.

**Comment by pattonwebz** [comment]
Closed by : https://github.com/WordPress/twentytwenty/pull/553
