### ISSUE TITLE
Feedback on Theme Options Section

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#495]
I am taking a closer look at the text used in the Theme Options section.

![Screen Shot 2019-09-24 at 09 03 22](https://user-images.githubusercontent.com/5323259/65491282-09688a80-deaf-11e9-8f53-0744460f8dbb.png)

"Settings for this theme"
Why is this there? Just above in the section heading it says Theme Options.

"Show search in header"
"Uncheck to hide the search in the header."
Uncheck and hide becomes in a sense a doble negative. What about "Check to show search in the header."  Or better yet just remove the sentence. It is common practice to click a checkbox to do something. When the user clicks the checkbox they will instantly see the results.

On archive pages, posts show:
"Search results always show the summary." 
This becomes confusing as it mentions the archive pages and posts and suddenly also mentions the search results. The line should just be removed.

Default selection is "Full text" it should be Summary.

Here is an alternative Theme Options section.

![Twenty-Twenty-Theme-Options-Alternative](https://user-images.githubusercontent.com/5323259/65491235-ef2eac80-deae-11e9-88c4-1ec69564dd42.jpg)

**Comment by andersnoren** [comment]
> "Settings for this theme"
> Why is this there? Just above in the section heading it says Theme Options.

I think this text can be improved by changing it to something like "Settings specific to the Twenty Twenty theme". Without prior knowledge, "Theme Options" could be interpreted as options for themes in general, so I don't think a description clarifying the purpose of the panel is out of place here.

> "Show search in header"
> "Uncheck to hide the search in the header."

I agree that the description seems a bit superfluous here.

> "On archive pages, posts show:"
> "Search results always show the summary."

Same on this one. Many users probably interpret archive pages and search results pages as two different things, so the clarification probably isn't needed, and creates more confusion than it prevents.

I disagree that "Summary" should be the default setting though, as almost all themes with a structure similar to Twenty Twenty show "Full text" on archive pages (including previous default themes). Changing that default in Twenty Twenty would create a lot of confusion among users.
