### ISSUE TITLE
Full width template does not show full width

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#497]
I might be misunderstanding this but selecting the Full Width template I see this result with a margin on both sides of the featured image.
![Screen Shot 2019-09-24 at 09 55 29](https://user-images.githubusercontent.com/5323259/65492840-f30ffe00-deb1-11e9-8f35-af5243e7cd92.png)

My thinking is that full width would actually show the featured image with no margin on left or right. Similar to how selecting full width would work with the Gutenberg cover block.

![Screen Shot 2019-09-24 at 10 01 07](https://user-images.githubusercontent.com/5323259/65493050-58fc8580-deb2-11e9-99d3-831b69acaeac.png)

**Comment by LittleBigThing** [comment]
I am wondering whether a full width page template is still as valuable as before since we have support for align-wide and align-full in the block editor? We do not have a sidebar either that would not appear on a full-width page. Maybe just drop the template?

**Comment by joyously** [comment]
I thought it was not about the images, but the text column width. I could be mistaken.

**Comment by amolv** [comment]
![Screen Shot 2019-09-26 at 6 22 07 PM](https://user-images.githubusercontent.com/1611340/65716370-a2b8bc00-e0bc-11e9-995e-b3e326cd1d6a.png)
Instead of using a featured image, full-width block in the editor can be used.

**Comment by paaljoachim** [comment]
I just tested this out and there is hardly any difference in using a full width template with a featured image. 

Here is a zoomed out view of a full width template with a featured image and a cover image using full width.  

![Screen Shot 2019-09-26 at 22 12 09](https://user-images.githubusercontent.com/5323259/65721769-ffab7680-e0aa-11e9-93fc-ee43b2900c5a.png)

From what I see one might as well just remove the full width template.

**Comment by paaljoachim** [comment]
Hey Joy. Content from what I see is the same width using the default template or the full width template.

**Comment by andersnoren** [comment]
Styling for the full-width template (removing the max-width on the entry-content, so it has the same width as the featured image) has been added by #547, so I'm closing this issue.
