### ISSUE TITLE
Adjusting the cover template featured image size?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#498]
The cover template will take the featured image and cover the full page.
What about making it possible to change the height of the featured image?
So that the cover covers parts of the screen and not all of it.

![Screen Shot 2019-09-24 at 10 09 09](https://user-images.githubusercontent.com/5323259/65493780-d5439880-deb3-11e9-93ef-b5f2b4e158c2.png)

![Screen Shot 2019-09-24 at 10 16 46](https://user-images.githubusercontent.com/5323259/65494084-7599bd00-deb4-11e9-86f9-95d2b776e3ed.png)

As it would be nice with the option to have the featured image for instance cover the header area and down into the beginning content area and not the full page.

**Comment by andersnoren** [comment]
I'm leaning towards this being a bit too granular to motivate an option of it's own. The change in behaviour can be accomplished pretty easily with Custom CSS or a child theme. I'm open to counterarguments though.

**Comment by boemedia** [comment]
In commercial theme's it's not uncommon to be able to adjust the height of the hero section. It would be great to have this setting in the customizer, where a height of 25, 50, 75% or full height could be selected, or custom. In the same way the boxed content often can be customized.

I wouldn't assume people using the WP default theme are all familiar with CSS, so I'd be carefull taking that as a starting point.

**Comment by joyously** [comment]
Looks like a header image to me. How often do themes allow different sizes of header images?
I think it's best to keep it simple and leave some room for enhancements in child themes.
