### ISSUE TITLE
Example of the front page of Twenty Twenty theme not using cover template

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#501]
Here is an example of Twenty Twenty theme not using the cover template but the default page template.

Notice the big Front page title and how much space it takes up. The standard page content using a Gutenberg paragraph and an image float has very little space below.

![Twenty-Twenty-Front](https://user-images.githubusercontent.com/5323259/65505773-5017ae00-deca-11e9-8677-a44c96d958bf.jpg)

A new suggestion. After some CSS modifications are added

![Screen Shot 2019-09-24 at 13 08 48](https://user-images.githubusercontent.com/5323259/65506721-83f3d300-decc-11e9-945a-a66b1a94dcf6.png)

It makes the Front page title smaller. It takes up less space below the header. Gutenberg content is wider.

**Comment by andersnoren** [comment]
With the default background colors, the entry header has a bottom padding with the white  background ("Header & Footer Background Color"), and the entry content has a top padding with the beige background color ("Background Color").

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/65579202-94ad5300-df77-11e9-98fd-a9bc68737181.png">

I think it would be a good idea to add a body class when those background color settings are set to the same color, and modify the spacing accordingly. In this scenario, that would mean removing the top padding of the entry content, bringing them closer together (similar to the spacing in the modified image you posted).

There's an issue with Image Blocks with the left and right alignment not being positioned correctly. They should be positioned to the left or right of the entry content column, like in the screenshot below. I'll create a separate issue for that.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/65579606-58c6bd80-df78-11e9-9e3e-33708112be44.png">

As for the `font-size` of the post title, we'll have to agree to disagree :)

**Comment by andersnoren** [comment]
After a discussion in the WordPress design slack, we decided that it would be a good idea to add a class to the `body` when the two background colors are the same, so the layout (especially padding and margins) can be adjusted when the colors are the same. 

Assigning the adding of the body class to @aristath. I can modify the CSS when the class is in place.

**Comment by aristath** [comment]
@andersnoren PR: https://github.com/WordPress/twentytwenty/pull/582
