### ISSUE TITLE
Back to top icon?

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#502]
Hey it would be good to add typical theme options. Such as a back to top icon. As one scrolls further down on the page the back to top icon in the bottom right could show up. Giving the user the option to click it to quickly and smoothly go back to the top of the page.

(Yes I know the beta has shipped.... could be added as an enhancement..:)

**Comment by andersnoren** [comment]
Including this would also require us to include an option for hiding it, and I don't think we would want to enable a sticky element by default, given how divisive they are. I think it's better to leave this functionality to plugins, like [WPFront Scroll Top](https://sv.wordpress.org/plugins/wpfront-scroll-top/).

**Comment by paaljoachim** [comment]
Ok. I will close the issue.
