### ISSUE TITLE
RFC Remove outline from search input field

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#504]
**Steps to reproduce**

Click on the search icon

**Expected behaviour**

Search input field is not outlined.

**Current behaviour**

Search input field is outlined.

---

@andersnoren Is it intended that the search input field is outlined?

@afercia Are there any accessibility or usability issues when hiding the search input outline?

**Comment by ianbelanger79** [comment]
Accessibility told us that the search field had to have a focused state after the search icon was clicked, thus the search input field has the outline. Closing as invalid.

**Comment by nielslange** [comment]
Thanks for clarifying this, @ianbelanger79!

**Comment by afercia** [comment]
(Late reply but yes, what Ian said 🙂Any interactive focusable element must have focus indication, whether it's the native one or a custom CSS one)
