### ISSUE TITLE
Sub-menus are not animating

### ISSUE THREAD

**Issue by sgomes** [WordPress/twentytwenty#513]
Looking at the source JS, there appears to be an intention to animate sub-menu opening and closing with a slide animation. However, they appear to be opening and closing instantly, with no animation (animations at 25% speed in the GIF below).

![ezgif-4-224772654588](https://user-images.githubusercontent.com/409615/65519455-d984ab80-dedd-11e9-94d0-72f37075cbc2.gif)

This should be fixed by either:
1 - Deciding not to animate, and removing the animation code from the JS sources.
2 - Fixing the animation.

I'm happy to implement whichever fix is deemed the best.

**Comment by acosmin** [comment]
Do you know of any pure css slide down/up animations 😄 the only one I know of implies animating the height and it needs to be set at a specific number...

**Comment by joyously** [comment]
You can translateY. 
But I prefer instant menus. The ones with transitions always seem so laggy.

**Comment by acosmin** [comment]
from my own experience translate tends to make text blurry...

**Comment by sgomes** [comment]
There are performant ways to draw slide animations that don't trigger layout nor paint, just composite (which is fast, and usually GPU-accelerated).

It's usually done with a `transform: translate`. It can make the text blurry during the animation, but that usually doesn't matter, unless the animation is so slow that you can actually read it.

**Comment by acosmin** [comment]
@sgomes give it a try 😄 they sure do need some animations...

**Comment by andersnoren** [comment]
What @acosmin said :) It would be great if you could take a look at this one, @sgomes.

**Comment by sgomes** [comment]
No problem, will do! 👍

**Comment by sgomes** [comment]
Added a working animation in #557. It's somewhat complex, as expected, but I added plenty of comments throughout.

**Comment by sgomes** [comment]
> You can translateY.
> But I prefer instant menus. The ones with transitions always seem so laggy.

@joyously I made sure that there is no animation if the user has configured their browser or OS to use reduced animations.

I also kept the existing data property for the duration. `data-toggle-duration="250"` is currently hardcoded in two places in the theme PHP, but if someone who is better at WP than me wants to make that configurable somehow, it'll be picked up by my code on the JS side 🙂

**Comment by joyously** [comment]
> I made sure that there is no animation if the user has configured their browser or OS to use reduced animations.

That's a good thought, thanks. I don't think my dislike is of animations in general; it's of animations in menus specifically. I like instant menus and anything else feels like the computer is working too hard. I like seeing all the other animations, so I can't just turn that off.

I guess this will just be another one of those themes that I don't like, because of slow menus and huge titles and huge images. Oh well.

**Comment by sgomes** [comment]
> That's a good thought, thanks. I don't think my dislike is of animations in general; it's of animations in menus specifically. I like instant menus and anything else feels like the computer is working too hard. I like seeing all the other animations, so I can't just turn that off.

That's some useful background, thank you! It is true that `prefers-reduced-motion` is a bit too heavy-handed.

> I guess this will just be another one of those themes that I don't like, because of slow menus and huge titles and huge images. Oh well.

That's where I hope someone will come in and make it configurable. It sounds like it would be fine if there were some configuration at the theme level that would output a different `data-toggle-duration` value in the HTML. Setting it to "0" would thus disable menu animations.

**Comment by acosmin** [comment]
@sgomes I could make an option for that, should it be between 0 and 250?

**Comment by sgomes** [comment]
> @sgomes I could make an option for that, should it be between 0 and 250?

That would be amazing, thank you so much! 🙇 I love the WP community! 😄 

As for the range, this is measured in milliseconds, so while 0 is definitely the lower value, there isn't really a meaningful upper value. If there needs to be one specified, I think 250 would be fine, yes; there shouldn't be much reason for making it higher than that.

**Comment by acosmin** [comment]
I'll have something put in place tomorrow 👍 hope this PR gets merged today 😄

**Comment by acosmin** [comment]
@sgomes after looking at the code there are only two places where this is used (animation duration). I think in this case we should only add a wp filter (via php) and the user can change it in his child theme. 

Creating an option for this only adds clutter in the Customizer... and can also be confusing if the user doesn't know where to look.

**Comment by sgomes** [comment]
Thanks again, @acosmin ! I'm happy with whatever is deemed the WP-like way of handling things, here 🙂 

It should also be relatively straightforward to override in CSS, if it comes to that.
