### ISSUE TITLE
Twenty Twenty Support page

### ISSUE THREAD

**Issue by rogermedia** [WordPress/twentytwenty#514]
The support page for the new core theme twenty twenty currently is a 404: https://wordpress.org/support/article/twenty-twenty/
![6FC39DB8-F466-4BA6-9F07-D79EE5141083](https://user-images.githubusercontent.com/4269307/65541077-da134700-dec9-11e9-9e50-da868e8516df.png)

I found this link here: https://github.com/WordPress/twentytwenty/

**Comment by joyously** [comment]
It's fine for now. It will be there once it's released.

**Comment by nielslange** [comment]
And I just created a ticket for the Meta team on https://meta.trac.wordpress.org/ticket/4742#ticket

**Comment by ntwb** [comment]
I've created https://wordpress.org/support/article/twenty-twenty/

And added @andersnoren @nielslange & @ianbelanger79 with _edit_ permissions

**Comment by nielslange** [comment]
Fantastic. Thank you so much, @ntwb!

**Comment by ntwb** [comment]
Let me know when WP 5.3 is released and I (or someone) will switch the _Twenty Nineteen_ link in the _Getting Started_ section of https://wordpress.org/support/ to _Twenty Twenty_

**Comment by ntwb** [comment]
Regarding https://codex.wordpress.org/Twenty_Twenty_Theme_Changelog

The Codex is currently in stages of being deprecated, so we should probably ~delete that page~, add a redirect (and never update that codex page) to a new HelpHub Support Article just as WP Core changelog pages are now HelpHub articles, eg [WP Version 5.2.3](https://wordpress.org/support/wordpress-version/version-5-2-3/)

Perhaps https://wordpress.org/support/article/twenty-twenty-changlog and linked from the default https://wordpress.org/support/article/twenty-twenty/ support page?

**Comment by nielslange** [comment]
> The Codex is currently in stages of being deprecated, so we should probably delete that page, add a redirect (and never update that codex page) to a new HelpHub Support Article just as WP Core changelog pages are now HelpHub articles, eg WP Version 5.2.3

> Perhaps https://wordpress.org/support/article/twenty-twenty-changlog and linked from the default https://wordpress.org/support/article/twenty-twenty/ support page?

Souns good, @ntwb. Can you create an empty page and grant me write access so that I can migrate the content from https://codex.wordpress.org/Twenty_Twenty_Theme_Changelog to https://wordpress.org/support/article/twenty-twenty-changlog?

**Comment by ntwb** [comment]
Done,  https://codex.wordpress.org/Twenty_Twenty_Theme_Changelog also now redirects to https://wordpress.org/support/article/twenty-twenty-changlog

**Comment by nielslange** [comment]
Thanks, @ntwb! 🙏

**Comment by nielslange** [comment]
Support page: https://wordpress.org/support/article/twenty-twenty/
Changelog: https://wordpress.org/support/article/twenty-twenty-changelog/

⚠️ The pages have been created as drafts and will be published with the release of WordPress 5.3

cc: @andersnoren, @ntwb, @carolinan, @pattonwebz & @ianbelanger79
