### ISSUE TITLE
Cover Template icon toggle text turns grey under 1000px

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#515]
The search and menu toggle text turn to grey from white when viewing the page under 1000px.

![cover-template-toogle-text](https://user-images.githubusercontent.com/34601694/65541614-ae00c180-dedb-11e9-80bd-5aa0c8109141.PNG)

**Comment by nielslange** [comment]
This issue can be fixed by changing `.toggle-inner .toggle-text` to `body:not(.overlay-header) .toggle-inner .toggle-text` in functions.php:707. (Might be helpful for a first time contributor.)

**Comment by byalextran** [comment]
i can't recreate this bug with the current master branch. when i set a background color in the customizer, it appears the text color is programmatically calculated correctly. 

but i notice your background isn't a solid color. not sure how you're doing that and wondering if that's something triggering the bug?

**Comment by joyously** [comment]
as the title says "Cover Template"

**Comment by byalextran** [comment]
@joyously 🤦🏻‍♂️ duh. submitting a PR shortly.
