### ISSUE TITLE
Show Search In Header Option Not Consistent

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#517]
On the customizing theme options page, there's no checkbox yet it shows search 

### Mobile
![twentytwenty-customizer-search-disabled](https://user-images.githubusercontent.com/1679025/65545511-844b9880-dee3-11e9-9be3-cb6f21a4c27c.png)

### Desktop
![twentytwenty-customizer-search-disabled-desktop](https://user-images.githubusercontent.com/1679025/65545725-f91ed280-dee3-11e9-98b1-deda4c99ff9b.png)

After changing setting it will show the correct update

**Comment by nielslange** [comment]
@okpierre Feel free to test the fix via https://github.com/WordPress/twentytwenty/pull/518 resp. via https://github.com/nielslange/twentytwenty/archive/update/%23517.zip.

**Comment by okpierre** [comment]
@nielslange It seems to work for me. Thanks!

**Comment by nielslange** [comment]
@okpierre: Glad to hear that! 

@ianbelanger79: Guess this one can be merged.
