### ISSUE TITLE
Related posts

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#521]
It would be nice to have the ability to add related posts at the bottom of each post.
Some would say that this is plugin territory others will say that it can easily be added directly to a theme.

**Comment by joyously** [comment]
It does not belong in a default theme, which is used for support : "switch to the default theme and see if your problem goes away". Having another loop in the default theme is not good for that reason.
The default theme needs to be kept as simple and unbuggy as possible because of this.
