### ISSUE TITLE
Author Bio - Customizer option to show or hide

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#524]
As the title says, we should add an option in the Customizer to enable or disable this single view section.

**Comment by karmatosed** [comment]
This could be personal, but I really would encourage less options not more. With regards to turning off / on an author bio, this falls into an extra not needed option.

**Comment by acosmin** [comment]
An extra is also the `Author Bio` section, it's not a core thing and I think having a way to disable it is needed. The only other way you would be able to disable it is to - edit user > remove any `Biographical Info` (this also applies to one user, not for all of them)

**Comment by jarretc** [comment]
Casting my vote for this issue. As somebody that frequents the themes support forum, the more options we give users that allow them to customize their site the better. Extra options don't hurt anybody, plus it gives new theme developers plenty of data to utilize for making their own themes by looking at how the code is implemented in the default themes.
