### ISSUE TITLE
Scope css styles within an appropriate container

### ISSUE THREAD

**Issue by brentjett** [WordPress/twentytwenty#529]
Practically all theme CSS should be scoped within a suitable parent container such as `#site-content` or `.entry-content` to prevent creeping into other components or applications that may exist on the page. 

Currently all `hr` tags are styled very specifically with `hr:not(.is-style-dots):not(.reset-hr)` and this is causing issues with other things that use hr's. A better approach would be to style `.wp-block-separator`, for example, or simply to scope the hr rule within `.entry-content` so that it isn't creeping into unwanted parts of the page.

This is important for all semantic elements, but particularly for `a, button, input, select, textarea, hr, h1-h6, and p`.

**Comment by joyously** [comment]
It's quite the opposite, actually. Themes should style all elements simply : `a, button, input, select, textarea, hr, h1-h6, and p`. And plugins or editors should style everything else as specific so that they don't mess up other unrelated things.

**Comment by brentjett** [comment]
Rules like `hr:not(.is-style-dots):not(.reset-hr)::before, hr:not(.is-style-dots):not(.reset-hr)::after` do not count as "styling simply". It's very specific, and very hard to override.

There are other participants in the page: Plugins like form providers or like Query Monitor, and page builders, all add their UI to the page and because of rules like this, typically have to avoid using semantic elements. There is no way for a plugin to know what every single theme will do with the base elements, so it becomes a game of guessing how overly specific to make rules.

The theme does not own the whole document. Themes should be good citizens just like plugins should be.

**Comment by joyously** [comment]
> The theme does not own the whole document.

Oh, I agree, but I think the theme provides the base for the rest, so it should style the base elements. That selector you quoted shouldn't be _anywhere_.

**Comment by andersnoren** [comment]
@brentjett I agree with you about the `hr` element. For that, we should update the CSS to apply the current styling to `.entry-content hr`, and make it opt-in with a class for elements outside of the entry content. Elements outside of the entry content without that class get a standard border color.

In general though, I agree with @joyously. The targeting in the theme should be as general and flat as possible, to make it easy to overwrite by plugins, child themes and the end user.

**Comment by brentjett** [comment]
I generally agree with the "Style all elements simply" convention. If we can avoid the heavy-handed rules, especially when they are just to achieve something decorative, then I'm good.

In the same vein, adding pseudo elements to every node on the page or disabling animation everywhere is a bit heavy-handed as well.
```
// style.css line 137
*,
*::before,
*::after {
	-webkit-box-sizing: inherit;
	-moz-box-sizing: inherit;
	box-sizing: inherit;
	-webkit-font-smoothing: antialiased;
	word-break: break-word;
	word-wrap: break-word;
}

// style.css line 378
@media ( prefers-reduced-motion: reduce ) {

	* {
		animation-duration: 0s !important;
		transition-duration: 0s !important;
	}
}
```
I'm happy to file separate issues, but in general the stylesheet overall could use a rule review.

**Comment by andersnoren** [comment]
@brentjett Agreed!

The box-sizing reset doesn't add pseudo elements to all elements, since it's missing a `content` property with a value. It just specifies that any pseudos created should inherit the box sizing setting. The word-break and word-wrap can be moved though, since those are inherited by the pseudos by default.

I believe disabling all animations and transitions for users that have set a preference for reducing motion/removing animations in their OS or browser is appropriate for a theme.

**Comment by brentjett** [comment]
Ah, good call on the no `content: ''` property. I didn't see that. 

On the animations: I can see the thought process there, but my gut instinct is that there could be unforeseen outcomes with that. I'm actually working on a piece of UI right now that uses the animation prop to indicate a successful rest response from the server. If I check `prefers-reduced-motion` within my own code, I can do something different to properly indicate success without the animation. If it's simply removed by a theme, then the user is just left without any success indicator. I understand the intention, but it's still dangerous to act upon DOM elements that the theme doesn't produce.
