### ISSUE TITLE
The usage of excerpt text under the page title + as preview text in blog.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#545]
An example:

![Screen Shot 2019-09-25 at 23 37 21](https://user-images.githubusercontent.com/5323259/65641589-80a43880-dfed-11e9-8907-986e9dd01a1b.png)

A question can show up on how to display text below the post title. As it might not be clear that one has to add text to the excerpt to see the text below the post title. Btw the excerpt is also used on the blog preview page to display some of the text of an article. There are two usages in one here.

1. For the text below the post title.
2. For the excerpt preview text used on a blog page.

For 1 one might have just a few words to stand out under the post title. For 2 one might want a few sentences to give a preview of the post. This can cause a conflict of interest in how the excerpt is used.

This is an important issue as it has to do with discoverability in how to add text below the post title and to where one has to add it. + Conflict of interest in having the excerpt used in two very different places.

-----------------

**EDIT:**
Single post. With excerpt as subtitle below the post title.

![Screen Shot 2019-09-26 at 09 46 49](https://user-images.githubusercontent.com/5323259/65668754-9db72680-e042-11e9-98ce-8dfdbe7398f4.png)

Blog page with summary showing the excerpt:

![Screen Shot 2019-09-26 at 09 47 49](https://user-images.githubusercontent.com/5323259/65668860-ce975b80-e042-11e9-840d-1c7b9636e170.png)

**A longer excerpt.**

Adding a excerpt to an article one usually has a few sentences one wants to show in the blog.
Blog page showing excerpt.

![Screen Shot 2019-09-26 at 09 50 43](https://user-images.githubusercontent.com/5323259/65669039-233ad680-e043-11e9-9bba-4a9c27a23534.png)

Single post showing the excerpt below the post title.

![Screen Shot 2019-09-26 at 09 49 58](https://user-images.githubusercontent.com/5323259/65669101-3e0d4b00-e043-11e9-965c-fbc2b3b30541.png)

As I mentioned excerpt is locked into being shown in two places. The subtitle below the post title seems more like a subheading then an area to show the excerpt. The excerpt is usually just seen in the blog page showing the summary of each post.

Joy mentioned this issue: #90
It needs more discussion.

**Comment by amolv** [comment]
@paaljoachim on a single post - all post's info/text is available just below post meta info, why excerpt required again?

**Comment by boemedia** [comment]
I can understand starting with a resume. It's not uncommon in lengthy articles to have a summary or scope of context at the beginning. 

Referring to "1" - this sounds more like a subtitle/text than an excerpt, which will have a different fuction.

To give people an understanding of how the text under the post title is generated, it may be wise to add a placeholder if not there yet, saying - this part displays your excerpt, fill it out to have text here. 

Another solution may be autogenerated text like it already happens in blog overviews.

**Comment by paaljoachim** [comment]
Having an excerpt below the post title as in the blog summary/excerpt is a tie-in of two features in one. We need to have another and easier to discover method of adding text content just below the post title and above the post meta.

**Comment by joyously** [comment]
I agree that it doesn't make sense to use the excerpt when the full content is shown.
But there is not another field to use, if the theme wants to show some text there. (The theme should not be supplying a way to show other content -- **no content creation in themes**.)
But it doesn't really hurt anything to show the manual excerpts only.
