### ISSUE TITLE
Add PHPDocs to template files

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#55]
- [x] https://github.com/WordPress/twentytwenty/blob/master/404.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/comments.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/content.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/footer.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/header.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/index.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/pagination.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/singular.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/template-cover.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/template-full-width.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/modal-menu.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/modal-search.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/page-header.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-comment-walker.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-svg-icons.php
- [x] https://github.com/WordPress/twentytwenty/blob/master/parts/classes/class-theme-customizer.php

**Comment by carolinan** [comment]
This has been fixed for now, closing
