### ISSUE TITLE
Remove old unused code for accent colors

### ISSUE THREAD

**Issue by acosmin** [WordPress/twentytwenty#551]
The code isn't used anymore:

https://github.com/WordPress/twentytwenty/blob/9804427868ad003fd5d8d7695c9e6bb0a5bd465f/classes/class-twentytwenty-customize.php#L157-L185

https://github.com/WordPress/twentytwenty/blob/9804427868ad003fd5d8d7695c9e6bb0a5bd465f/classes/class-twentytwenty-customize.php#L407-L414

https://github.com/WordPress/twentytwenty/blob/9804427868ad003fd5d8d7695c9e6bb0a5bd465f/functions.php#L421-L433

**Comment by tm-const** [comment]
Updated function file here: https://github.com/WordPress/twentytwenty/pull/560

**Comment by andersnoren** [comment]
Fixed by #552.
