### ISSUE TITLE
IE11: Cover template entry header position is incorrect

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#562]
In IE11, the cover template entry header is at the top of the page compared to in other browsers, where it is at the bottom.

![cover-ie](https://user-images.githubusercontent.com/7422055/65710999-5194d200-e094-11e9-96c9-c9e265382e7e.png)

**Comment by ianbelanger79** [comment]
This is due to IE11 not completely supporting `display: flex;`
