### ISSUE TITLE
Page Title Enable/Disable Option.

### ISSUE THREAD

**Issue by mafzal9** [WordPress/twentytwenty#563]
i am designing some test website, where i feel the need to hide the page title. i tried to find the option in customizer but did not got the option. if there is option then please let me know if not available then it's my suggestion please add page title hide/show option in page.

**Comment by karmatosed** [comment]
The setting on/off of a page title for me is something should be done in core, not a theme. There have been some explorations of this and whilst it won't be in for 5.3, I would say 'watch this space' as Gutenberg, for example, moves more into site editing.
