### ISSUE TITLE
Full Width Template and the default template

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#567]
1. Full width template.
Featured image seen in the top. Wide content.
![Screen Shot 2019-09-26 at 23 07 54](https://user-images.githubusercontent.com/5323259/65725274-8021a580-e0b2-11e9-9d87-33fa7f041fa4.png)

2. Default template.
Featured image seen in the top. Narrow content. Images beside content.
![Screen Shot 2019-09-26 at 23 09 14](https://user-images.githubusercontent.com/5323259/65725347-b3643480-e0b2-11e9-954d-9f1aadb4674f.png)

Personally I would prefer to have the Full Width template as the default template because of how the images float better with the text.

What are your thoughts on both these templates?

**Comment by joyously** [comment]
This is part of the design. 
What is the question? Is it should the design be changed? Or is it about the design matching your preference?

**Comment by nielslange** [comment]
@paaljoachim Could you clarify @joyously's question? 😀

**Comment by paaljoachim** [comment]
> What is the question?

There is no question, but there is a comment to what the design looks like at 1020px width and higher. 

> Is it should the design be changed?

Content with 58 rem should be wider. The text becomes too narrow. Images are detached from the content because of the space between content and images.

> Or is it about the design matching your preference?

Every issue/comment I make has to do what I prefer/my own preference. I will share my views and when others do not agree then that is alright. The important part is sharing different view points or how one looks at it. I am sharing how I look at it. 

Have a great Sunday!

I will go ahead and close the issue.
