### ISSUE TITLE
Using featured image in two places.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#568]
When adding a featured image to a post it shows up two places.
1. Below the post title and 2. in a blog page summary.

What if one just wanted a blog page summary with a few sentences and a featured image, but did not want the image to show up above the post content?

What is somewhat difficult here is the locking in of content. If you use featured image it then it will be used in both places. One can not choose the one or the other.

**Comment by joyously** [comment]
Yes, that is part of the design. The user can easily choose a different theme.

**Comment by paaljoachim** [comment]
The issue I have in regards to the featured image is that it is being used for two purposes. One as a featured image in the summary/excerpt of a blog page. The other as a image below the post title. The question also becomes. Do we need to have a huge image below the post title when using the Default Template? The user might as well just add an image in the post layout with a huge image if they want it.

**Comment by joyously** [comment]
That sounds to me like two uses of featured image. It's not two purposes, just two places it's shown.
If the user doesn't like it, they can use another theme.

**Comment by ianbelanger79** [comment]
IMO this how a featured image is intended to be used. Closing this issue as `wontfix` as this could easily be changed in a child theme.
