### ISSUE TITLE
Locking in of content with using excerpt and featured image in two places.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/twentytwenty#570]
I have addressed both of these in their own issues.
https://github.com/WordPress/twentytwenty/issues/545
https://github.com/WordPress/twentytwenty/issues/568

This issue is more in general of tying in features in two places.

Excerpt.
I am a little worried about locking Excerpt to the subtitle below the post title AND as a standard excerpt seen in the blog page summary. Placing two different ways to use content in the same box. One can not change one without it affecting the other.

Featured image.
The featured image when used it seen below the post title AND in the blog page summary as a featured image by the post content. If one only wants a featured image to use in the blog page summary then one will need to use CSS or another piece of code to remove the featured image from below the post title.

Tying/locking in two different features makes it more difficult to make the theme ones own.
I believe this is something that needs a good discussion.

**Comment by joyously** [comment]
For the excerpt, it was already discussed at https://github.com/WordPress/twentytwenty/issues/90

**Comment by karmatosed** [comment]
I wanted to get some perspective on this so forgive me if ask some questions.

- Is the issue using the featured image twice on same page?
- Are you suggesting a new feature because it seems so in excerpt.

@paaljoachim I wonder if keeping discussion on those tickets might help or if I am missing something in a new ticket?

**Comment by paaljoachim** [comment]
> Is the issue using the featured image twice on same page?

The issue I have in regards to the featured image is that it is being used for two purposes. One as a featured image in the summary/excerpt of a blog page. The other as a image below the post title. The question also becomes. Do we need to have a huge image below the post title? The user might as well just add an image in the post layout with a huge image if they want it.

> Are you suggesting a new feature because it seems so in excerpt.

Having an excerpt below the post title as in the blog summary/excerpt is a tie-in of two features in one. So yes we need to have another and easier to discover method of adding text content just below the post title and above the post meta.

I will add additional information to both the issues as well.
