### ISSUE TITLE
Missing Footer Widget Content

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#571]
Content in first footer column: Archive, Calendar
Content in second footer column: Meta, Latest Posts

After updating to latest, Meta and Latest Posts are missing

Content in first footer column: Archive, Calendar
Content in second footer column:

**Comment by joyously** [comment]
The sidebars got renamed.

**Comment by okpierre** [comment]
Should footer position retain their slots going forward?

**Comment by joyously** [comment]
I would think so.

**Comment by okpierre** [comment]
Maybe it's my install? Before updating, I switched to Twenty Nineteen, install the latest Twenty Twenty and clicked on Activate. If I switch to any version of Twenty* and switch back, the widgets has a mind of it's own.

Here's my new test

### Before
![twentytwenty-footer-widgets-before](https://user-images.githubusercontent.com/1679025/65731482-de8b5b80-e093-11e9-9130-8f6360afec2b.png)

### After
![twentytwenty-footer-widgets-after](https://user-images.githubusercontent.com/1679025/65731491-e814c380-e093-11e9-841f-4b4b5e54d124.png)

**Comment by joyously** [comment]
That could be due to Twenty Nineteen having only one sidebar. 
I think the logic is not very good for the reassignments, but I haven't written a ticket on it. It also affects custom widgets provided by the theme, as they always get moved to Inactive.

**Comment by nielslange** [comment]
@okpierre I guess this issue can be closed, right?

**Comment by okpierre** [comment]
@nielslange Maybe? According to @joyously it sounds like it could be a WordPress issue and not something a theme could check or control?

**Comment by carolinan** [comment]
When I switch between another theme that has at least two widget areas it works fine for me.
I am closing this issue.
