### ISSUE TITLE
Remove button style "Squared" from button block

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#573]
The button block comes with the following three styles:

- Default → Rounded button
- Outline → Rounded, outlined button
- Squared → Squared button

With Twenty Twenty we show only squared buttons. Therefore, the `Default` and the `Squared` button styles look identical, which might be confusing for some users. To avoid confusion I suggest removing the `Squared` button style.

**Comment by joyously** [comment]
Maybe someone could convince the editor folks that it makes better sense to have the default be Square, and it doesn't need a separate class?

**Comment by nielslange** [comment]
You could suggest it in https://github.com/WordPress/gutenberg/issues. As for now, don't you think we should remove the `Squared` button style to avoid confusion?
