### ISSUE TITLE
Footer Menu Missing Styling To Match Other Menus

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#574]
Desktop horizontal menu and mobile menu both have underlines when a mouse is over the link

Footer menu is missing the underline (before)
![twentytwenty-footer-menu-before](https://user-images.githubusercontent.com/1679025/65741115-0e008f00-e0b9-11e9-8857-3a04bad32231.png)

To be consistent (after)
![twentytwenty-footer-menu-after](https://user-images.githubusercontent.com/1679025/65741123-12c54300-e0b9-11e9-87e1-f00ccbdb99b2.png)

**Comment by carolinan** [comment]
This has been merged, so I am closing the issue. Thank you!
