### ISSUE TITLE
No way to reset the accent color hue

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwenty#583]
Our colorpicker library support resetting the default colors, so we get that by default, but there's no way to reset the accent color back to the default value. Might be worth considering adding a "default" button, if possible.

**Comment by ianbelanger79** [comment]
@aristath is it possible to have a default reset button for the hue picker?

**Comment by aristath** [comment]
Unfortunately the WP colorpicker doesn't have a reset button/functionality for hue-only pickers.
It's doable, but we'd have to custom-code it... Like for example by injecting a reset button via JS right next to the slider (or above/below it), and then on click reset the control to its initial value.

**Comment by joyously** [comment]
@aristath This is where you whip out your Reset-All button!  (although the one you wrote was for child themes, it would be great to get that into circulation)

**Comment by nielslange** [comment]
I was also looking for the `Reset` button earlier today.

**Comment by karmatosed** [comment]
I would like to add that I just experienced this and wanted a reset. I wonder if there is any option of getting it?

**Comment by aristath** [comment]
> I would like to add that I just experienced this and wanted a reset. I wonder if there is any option of getting it?

We _can_ add it, but it's not something that is normally supported by that control.
So we really only have 3 choices here:
1. Don't do it.
2. Do it in wp-core and add a reset button in hue-only colorpickers
3. Custom-code it in the theme

It's too late for option 2 in WP5.3, so we can either custom-code this in the theme, or just implement it in wp-core in a future release. But it we do custom-code it in the theme then we'll need a mockup.

Or we could just not do it 😄 

--------------

Alternative suggestion: Add a "custom accent color" checkbox. The hue colorpicker will then be hidden by default and only revealed if that checkbox is checked.
If the checkbox is disabled, then just fallback to default.

**Comment by acosmin** [comment]
I made a small prototype in #613 based on aristath's alternative suggestion.

**Comment by ianbelanger79** [comment]
This was fixed in #613
