### ISSUE TITLE
Provide a way to adjust the tagline/meta color

### ISSUE THREAD

**Issue by melchoyce** [WordPress/twentytwenty#584]
I was expecting the tagline and meta colors to be generated by the accent color hue, but that doesn't seem to be the case. If the accent hue is wildly different than the generated tagline/meta colors, the color palette can look a little bit off. Maybe the color could be tied into the accent hue, or another color option could be provided.

**Comment by aristath** [comment]
If I'm not mistaken, the meta color is using the `secondary` color value.
We calculate that based on the background & text colors. To be more precice it's half the saturation of the background, and lightness is calculated as a mix of 57% textcolor-brightness, 43% background-brightness.
The above numbers are a result of the initial design colors where secondary text (including metas) was a perfect match for these values (`#6d6d6d`).

It's not really visible when using white/black/gray backgrounds, but I believe it's easier to visualize if you try various colors for the background... You'll notice that these change color accordingly.
