### ISSUE TITLE
Update print styles

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#588]
The link href need to be hidden, because when printed this way, it can create a text overlap:

![print2](https://user-images.githubusercontent.com/7422055/65795899-a5261f00-e16b-11e9-8996-4ce89118ec68.png)

**Comment by joyously** [comment]
I thought it would be better to hide the interactive stuff like Next/Prev links, pagination, widget areas, menus.

**Comment by nielslange** [comment]
I agree, @joyously. Shall we sit together closer to the RC and create a few screenshots and decide which elements to keep and which ones to remove?

**Comment by joyously** [comment]
Let me know when.

**Comment by nielslange** [comment]
Thanks, @joy!

**Comment by nielslange** [comment]
Thanks, @joyously!

**Comment by carolinan** [comment]
@nielslange @joyously Do you still have time to work on this? :)
