### ISSUE TITLE
Preformatted block doesn't allow for long text

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwenty#591]
I am going through testing for the blocks using the awesome block unit test. As a result, I found this:

![image](https://user-images.githubusercontent.com/253067/65798479-a1919880-e169-11e9-961c-790a19fbb047.png)

**Comment by joyously** [comment]
Can you verify the original text for the poem? Mine has individual paragraphs, which yours is not showing.

```
<!-- wp:preformatted -->
<pre class="wp-block-preformatted">The preformatted block.

The Road Not Taken

Robert Frost 
Two roads diverged in a yellow wood,
And sorry I could not travel both          (\_/)  
And be one traveler, long I stood         (='.'=)  
And looked down one as far as I could     (")_(")  
To where it bent in the undergrowth; 

Then took the other, as just as fair,  
And having perhaps the better claim,          |\_/|  
Because it was grassy and wanted wear;       / @ @ \  
Though as for that the passing there        ( &gt; º &lt; )  
Had worn them really about the same,         `&gt;&gt;x&lt;&lt;´  
                                             /  O  \  
And both that morning equally lay  
In leaves no step had trodden black.  
Oh, I kept the first for another day!  
Yet knowing how way leads on to way,  
I doubted if I should ever come back.  
I shall be telling this with a sigh  
Somewhere ages and ages hence:  
Two roads diverged in a wood, and I—  
I took the one less traveled by,  
And that has made all the difference.  


and here's a line of some really, really, really, really long text, just to see how it is handled and to find out how it overflows;</pre>
<!-- /wp:preformatted -->

```

**Comment by karmatosed** [comment]
It's using the block unit test.

**Comment by joyously** [comment]
Yes, so am I, and my `pre` block looks like the code I pasted above ^.
I got the latest zip and tried it and it looks good in the editor, in the preview, and on the front end. (Reloaded to make sure I had the latest CSS.)
This is front end:

![pre-block](https://user-images.githubusercontent.com/7957680/65804009-1226be00-e146-11e9-942d-b1a5329c2204.jpg)

**Comment by carolinan** [comment]
And it it meant to wrap, not be cut off or create a scroll, correct?

**Comment by ianbelanger79** [comment]
As it is a `<pre>` block, it should scroll and not wrap the text.
