### ISSUE TITLE
CSS reset is more difficult to debug

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#6]
Can we do CSS normalize instead of CSS reset, please? 
It's much better for catching all the cases that might not be tested. And as a default theme, that could be a lot, considering all the legacy content out there.

https://github.com/WordPress/twentytwenty/blob/cf58da76a82071516f91362e8c769d8491d67b97/style.css#L57

**Comment by pattonwebz** [comment]
I wonder if this issue would require any major adjustments to the existing CSS to account for a swap to a different kind of CSS reset/normalize. I am not sure that it does but it's worth trying to verify that if anyone has some time for it.

**Comment by ianbelanger79** [comment]
We have to decided to leave CSS reset intact, due to time constraints.
