### ISSUE TITLE
Consider reducing number of menu locations

### ISSUE THREAD

**Issue by karmatosed** [WordPress/twentytwenty#600]
Right now there are a lot of menu locations:

![image](https://user-images.githubusercontent.com/253067/65799995-4feb0d00-e16d-11e9-943d-fcbaa6e19f66.png)

I worry this is a little of a paradox of choice for people. I would love to know what others think. For me, I would remove mobile menu, I would also because of social links in Gutenberg remove social and then have one desktop menu.

**Comment by joyously** [comment]
Can you read the #core-themes meeting discussion on Slack about this?

**Comment by karmatosed** [comment]
Would you be able to reference that for me @joyously? I'd love a summary to have some context here in issue.

**Comment by joyously** [comment]
Here it is: https://wordpress.slack.com/archives/C02RP4VMP/p1568056939145500

**Comment by andersnoren** [comment]
It was discussed here #164 and here #74 as well.

**Comment by karmatosed** [comment]
Thanks for the context. With the social links block, it feels like we could remove the social menu. What do you think?

**Comment by karmatosed** [comment]
I am going to loop back in a comment here after @andersnoren took some time to explain to me on the social menu. Thank you again for taking time there. Whilst there is a block now, to have this feature for older versions means a menu makes sense. Similarly, the placing is going to cause a lot of issues with styling.

I still do feel considering merge menus or something similar to what Twenty Nineteen does could be an option, but to keep the flow going will close this issue. Thanks everyone.
