### ISSUE TITLE
Content becomes scroll-able with modals open even if page is too short to scroll

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#604]
If a page is short enough not to need a scrollbar one is added when modals open. This causes content to shift slightly when opening/closing modals.

![Peek 2019-09-28 00-05](https://user-images.githubusercontent.com/3902039/65807004-59cc3a80-e184-11e9-8f6c-a17895dee037.gif)

**Comment by okpierre** [comment]
Seeing the same on my end

**Comment by acosmin** [comment]
@pattonwebz I think this one can be closed.

**Comment by pattonwebz** [comment]
Seems like it is resolved by the commit in your PR, thanks for that :D
