### ISSUE TITLE
Horizontal menu: Submenu levels are present but not visible depending on screen width

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#624]
When testing, I used the Theme Unit Test menu called "testing menu" which
has a submenu level of 10.

But only the parent parent menu item to level 6 are visible, even though all levels are present in the markup.

Update: And of course, the narrower screen/window width, the fewer submenu items show.

Consider showing submenus vertically instead of horizontally.

**Comment by acosmin** [comment]
I would limit it to 2-3 levels 😃

**Comment by nielslange** [comment]
To me, going 6 levels deep also doesn't sound like a great approach. However, I would not limit it to 2-3 levels, as there are cases in which deeper navigations are needed. For example, I worked with a customer that offers chip tuning for cars. That's their menu:

BMW → Series 1 → F52 →  118i 6AT

I believe there are quite a few cases where a 2-3 level deep navigation would not work for the user.

**Comment by glauberm** [comment]
In screens smaller than 700px, it shows all levels. Here's a screenshot of a 240x320 screen:

![240x320](https://user-images.githubusercontent.com/3619476/65992067-df8e0580-e464-11e9-8f3f-6c76f2f119cd.png)

On screens bigger than 699px they also appear, but are only styled until the fourth level:

![700x700](https://user-images.githubusercontent.com/3619476/65992357-6e9b1d80-e465-11e9-9cd7-b98161f16d07.png)

When it comes to screens with a minimum 1000px width, not even the third level shows correctly:

![1000x](https://user-images.githubusercontent.com/3619476/65993055-cede8f00-e466-11e9-8a96-fcd0dcb58b41.png)

So I do agree with @carolinan that vertical is the way to go. That will make the menu less limited overall -- limiting it to 3 levels doesn't sound like a good idea to me.

Can I make a PR for this?

**Comment by glauberm** [comment]
#725 and #726 address the issue of the medium size menu. Still waiting on a position about the desktop one.
