### ISSUE TITLE
Styles conflict with the media modal used on the front end

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#639]
The WordPress media modal can be used on the front end by enqueueing the related JavaScript and instantiating a media frame. 

The theme CSS should do its best to not conflict with the media modal UI. Currently, a few elements do have CSS conflicts.

To test:
- easier way: manually install this plugin https://github.com/dbspringer/wp-frontend-media
- create a post and insert the shortcode `[frontend-button]`
- publish and view the post
- click the "Select file" button and the modal opens in the front end

Screenshot:

<img width="1440" alt="Screenshot 2019-09-28 at 17 58 03" src="https://user-images.githubusercontent.com/1682452/65819152-a9a91100-e219-11e9-86e8-7188a3954544.png">

- the Close button inherits styles from the theme buttons
- the search from inherits styles from the form styles
- see also the "deleted permanently" `.button-link`

For the search input, there's some flexbox used for the class `.search-form` so the media modal search input becomes a flex item. The theme should probably better scope the `.search-form` selector. 

Haven't looked in depth the other cases.

**Comment by acosmin** [comment]
This is really an edge case 😃 and it will add clutter to our css and make it more complex.

**Comment by afercia** [comment]
I kindly disagree :) There's a lot of plugins that add the media modal on the front end.

I don't see how a simple additional CSS selector would ever make "your" (the term "our" you used makes me feel a bit uncomfortable) CSS cluttered and more complex.
