### ISSUE TITLE
Prevent CSS parse error from unspecified rule definition

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#643]
An unspecified CSS block is produced like this in the middle of other riles which results in a CSS parse error in markup validation: 
`.comment-reply-link { color: #f5efe0; } { background: #f5efe0; }body,.entry-title a { color: #000000; }`

It should be:
`.comment-reply-link { color: #f5efe0; }body,.entry-title a { color: #000000; }`

This happens because this function always returns a value and that's the value that is tested for existence - so when `$elements` is empty this produces style rules and outputs them still.

Empty array:

https://github.com/WordPress/twentytwenty/blob/7307f845c888d277a45b8239349f78b3f046bed0/functions.php#L633
Outputs unspecified rules because this all still runs:

https://github.com/WordPress/twentytwenty/blob/7307f845c888d277a45b8239349f78b3f046bed0/inc/custom-css.php#L100-L103

**Comment by andersnoren** [comment]
Fixed by #644.
