### ISSUE TITLE
Different styles for the search results

### ISSUE THREAD

**Issue by robertotunon** [WordPress/twentytwenty#666]
Hi there everyone,
it's my first time creating an issue, so... sorry for any kind of inconvenience.

I think that search results list could be more useful if it don't looks exactly the same as a blog list.

Perhaps we could show it as a short list, trying to avoid very long scrolls and making easier to search over the whole list and choose a result.

In other hand, I think it would be useful to show the post type on each result to allow a quickly view of the kind of content each result is.

It could looks something like this:
![image](https://user-images.githubusercontent.com/11837011/65839153-07695600-e30b-11e9-9514-ac3ecf7d30a3.png)

What do you think about it?

**Comment by joyously** [comment]
Hi Roberto!
It already looks different from a blog list, but it is, after all, the same thing.
See #369 and #275 for changes that have already been made to the search page.
