### ISSUE TITLE
Form controls miss a focus style

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#67]
Clear indication of focus is essential for keyboard navigation.

Currently, there's no indication of focus on input fields, textarea, select elements. The current CSS resets native focus style with `outline: none;` and doesn't provide an alternative style.

This affects all form controls displayed on the front end, for example the Search input field or the Comments form.

The caret isn't a sufficient indication of focus. Color alone isn't either. Focus needs to be indicated with a shape. There are two options:

- either remove `outline: none;` and rely on the browsers native focus style
- or provide an alternative focus style which _improves_ the native one

Screenshot of the comments form: tab through the form elements and notice only the checkbox has a focus style:

<img width="733" alt="Screenshot 2019-09-07 at 13 55 13" src="https://user-images.githubusercontent.com/1682452/64474677-6575a400-d178-11e9-8421-340a7f25da64.png">

Screenshot of the search form: no focus style:

<img width="1363" alt="Screenshot 2019-09-07 at 14 04 40" src="https://user-images.githubusercontent.com/1682452/64474698-981f9c80-d178-11e9-9e53-1951b8cf23f8.png">

Of course, this applies also to buttons and any other interactive control but I see there's no `outline: none` there, though the focus style could be improved a bit.

**Comment by joyously** [comment]
This is related to #6. If you use CSS normalize instead of CSS reset, there is much less CSS to fix.
