### ISSUE TITLE
Remove FontAwesome and replace it with an svg solution

### ISSUE THREAD

**Issue by Ismail-elkorchi** [WordPress/twentytwenty#674]
Twenty Nineteen don't use any font icon, instead it has a class that take care of outputting the SVG code of the icons where they are used : https://github.com/WordPress/twentynineteen/blob/master/classes/class-twentynineteen-svg-icons.php

Doing the same will help to reduce the size of the theme ( https://github.com/WordPress/twentytwenty/issues/542 ), and help making the front-end a little faster, since the browser wouldn't have to download the font assets.

**Comment by andersnoren** [comment]
We discussed this issue on the weekly #core-themes Slack meeting earlier this evening, and we've decided to go ahead and replace FontAwesome with an SVG only solution. I'll get started on a PR tomorrow or Wednesday. 

Thanks for creating the issue, @Ismail-elkorchi!

**Comment by ntwb** [comment]
When landing this in core please ensure the `font-awesome` folder is removed from the SVN repo https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwenty/assets/fonts?order=name

See also https://core.trac.wordpress.org/ticket/48163

**Comment by Ismail-elkorchi** [comment]
Thank you @andersnoren, @ianbelanger79 for your great work on this issue !
