### ISSUE TITLE
Horizontal menu: submenus does not always close when another submenu item is focused

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#675]
In the horizontal menu, submenu items are not always closed when you move focus to another parent menu item or another submenu item.

This creates an overlap of open submenus.

![submenu-overlap](https://user-images.githubusercontent.com/7422055/65888706-409fd580-e3a0-11e9-8826-0f76d007e3e5.png)

**Comment by glauberm** [comment]
Hi @carolinan , could you provide more info for me to reproduce this?

**Comment by carolinan** [comment]
Ah, I must have accidentally clicked on the "Menu CSS Class" menu item above which is an # not a complete link.
So, click any menu item that is an **external link** or an #. Then move the mouse.

**Comment by glauberm** [comment]
I see. I think this is a hover issue more than a focus one. The first solution that occurs to me is to remove focus from all other menu items if one of them is hovered. But I'm afraid that would hurt accessibility. What do you think, @carolinan ?

**Comment by carolinan** [comment]
I don't think that clicking on a menu item should open the submenu.
