### ISSUE TITLE
Revise `.alignwide` and `.alignfull` utility classes to respect Gutenberg nesting rules.

### ISSUE THREAD

**Issue by allancole** [WordPress/twentytwenty#676]
Currently, the `.alignwide` and `.alignfull` utility classes on the front end behave differently than they do in the editor when nested. This is because the current solution cannot account for nesting conditions which are now possible with many blocks like Cover, Group, and Column.

In all cases, the top-most block container should always constrain the width of a nested block. It’s tough to explain this without visuals so take a look at this screenshot of the Editor:

![image](https://user-images.githubusercontent.com/709581/65889927-0fa7ac80-e370-11e9-984c-4918ab97c5e3.png)

What you see is a group of nested blocks similar to this nested list:

- **Group Block** - default width and a dark tan background
  - **Group Block** - `.alignwide` width and a red background
    - **Paragraph Block** - placeholder text

Notice how the top-most Group Block restricts the inner `.alignwide` Group Block from being wider than itself? In the editor this works as expected, but on the front end, the inner `.alignwide` Group Block breaks outside of the top-most Group Block and effectively hides it as you can see here: 

![image](https://user-images.githubusercontent.com/709581/65890510-feab6b00-e370-11e9-953c-560108afb1d0.png)

### Solution

Unfortunately, the solution isn’t as easy as adding some extra nested selectors like this: 
`.wp-block .alignwide .alignfull .alignwide { /* wide width */ }`. 

Gutenberg allows for many levels of nesting (maybe infinite) and it’d be impossible for us to write out selectors that cover all possible conditions. Instead, we need to refactor the way that wrappers in `.entry-content` behave and remove any margins or explicit widths from them. Then, instead of treating `.alignfull` and `.alignwide` as special classes we can take advantage of the box-model and say all blocks should be 100% wide by default except when they are not `.alignfull` or `.alignwide`. By reversing the logic this way, we can make sure all width related utility classes respect the constraints that come from _any_ parent element whether that be another Block or the .entry-content wrapper itself. 

I’ll work out a PR that shows this working shortly.

**Comment by joyously** [comment]
There _are_ selectors that can take into account all combinations, like `:matches`, but there isn't good [browser support](https://www.caniuse.com/#feat=css-matches-pseudo).
But you could write the rule for the classes to be 100% width, followed by the special case of it being a direct child of .entry-content (which is the rules you have now with the margins).

Is there a concern that the wide and full classes are applied to images, using 100% width? Or is that okay because the user can see it in the editor (which is not as wide as a desktop window can be)?
