### ISSUE TITLE
Header Search Outline reveals no padding on the input

### ISSUE THREAD

**Issue by dream-encode** [WordPress/twentytwenty#678]
Testing for Beta 2 uncovered this.  Discussed in today's #core-themes meeting for Twenty Twenty, it was advised to open a separate issue for this so it can be tracked.

It was also mentioned by @ianbelanger79 that accessibility should be involved in any decision making here.

![image](https://user-images.githubusercontent.com/1900750/65911249-5b6f4b80-e39a-11e9-95e4-fea739446287.png)

**Comment by pattonwebz** [comment]
In terms of aesthetics I also tend to find the lack of a left padding here feeling somewhat *odd*.

**Comment by acosmin** [comment]
The input search field looks good with the same padding as the `x` button, `padding-left: 2.5rem`.

**Comment by nielslange** [comment]
@acosmin Are you going to implement this or are shall I do that quickly?

**Comment by acosmin** [comment]
@nielslange you can have it 😃
