### ISSUE TITLE
Add non-latin fonts support

### ISSUE THREAD

**Issue by nielslange** [WordPress/twentytwenty#69]
Add non-latin fonts support as mentioned in https://make.wordpress.org/core/2019/09/06/introducing-twenty-twenty/#comment-36932

**Comment by joyously** [comment]
What if the CSS just said `serif` or `sans-serif`? It would use whatever was already chosen by the user in their browser settings, which means it would support all languages.
And then the theme wouldn't be so big, bundling a font.

**Comment by nielslange** [comment]
Closed in favour of #118
