### ISSUE TITLE
Consider re-adding a wrapping div around the posts on archives

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#690]
#456 removed the `.posts` wrapper div so simplify the markup. Since #655 the `.footer-nav-widgets-wrapper` div is included in the bottom of the `<main>` element.
Now the structure of the `<main>` element looks like this:

<img width="803" alt="code" src="https://user-images.githubusercontent.com/54663751/65955826-43a2d080-e449-11e9-8bc8-4ecf07254c5a.png">

I've created a child theme to see how easy it is to change some of the theme styling. With the current structure it is now difficult to change, for example, the blog layout.

I suggest to re-add a `.posts` wrapper div so the structure looks like this:

<img width="804" alt="code2" src="https://user-images.githubusercontent.com/54663751/65956659-2ec73c80-e44b-11e9-9d86-1b762afe6529.png">

**Comment by joyously** [comment]
Whether the wrapper is `main` or `.posts`, it's the same thing.
What would simplify the HTML is to remove the `hr` after each. It could be inside each `article` or simply a CSS border instead of markup.

**Comment by jeherve** [comment]
#704 makes the markup cleaner:

![image](https://user-images.githubusercontent.com/426388/66034069-cfc7fd00-e508-11e9-88ac-c1caa6938526.png)

Maybe this issue can now be closed?
