### ISSUE TITLE
Padding difference in front end and back end for Table block in Gutenberg

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#697]
As shown in the screenshots below.
# In 2020 Theme
Back end Screenshot Url - https://share.getcloudapp.com/E0uPWZGX 
Front end Screenshot Url - https://share.getcloudapp.com/bLup656N

# In 2019 Theme
Back end Screenshot Url - https://share.getcloudapp.com/wbue1Qeq
Front end Screenshot Url - https://share.getcloudapp.com/p9uzdQjd

**Comment by ianbelanger79** [comment]
Duplicate of #320
