### ISSUE TITLE
Ensure contributors list is updated with all names before beta 3 package is bundled

### ISSUE THREAD

**Issue by pattonwebz** [WordPress/twentytwenty#698]
Update the contributors file with the list of all the people that have contributed code as well as people who opened issues and contributed in discussions on them and the PRs.

- [x] maheshwaghmare | mahesh901122 https://github.com/WordPress/twentytwenty/pull/694#issuecomment-537052213
- [x] amolv | amolv https://github.com/WordPress/twentytwenty/pull/687#issuecomment-537482242
- [x] utsavtilava | utsav72640 https://github.com/WordPress/twentytwenty/pull/715
- [x] glauberm | glauberglauber https://github.com/WordPress/twentytwenty/pull/723

**Comment by utsavtilava** [comment]
My WordPress username is @utsav72640.
