### ISSUE TITLE
screenshot.jpg image can be image optimized to reduce the file size

### ISSUE THREAD

**Issue by lukecav** [WordPress/twentytwenty#708]
https://github.com/WordPress/twentytwenty/blob/master/screenshot.jpg

`screenshot.jpg` can be image optimized from 184.9 KB down to 74.7 KB in size.

**Comment by lukecav** [comment]
![screenshot](https://user-images.githubusercontent.com/5797332/65988099-6e3e5a80-e444-11e9-83b2-3bacc03ee89e.jpg)

**Comment by nielslange** [comment]
@lukecav When looking up the optimized screenshot I see some noise around the menu and search and the fonts are less sharp. Would you mind reducing the compression level to avoid these artefacts to appear?

**Comment by lukecav** [comment]
![screenshot](https://user-images.githubusercontent.com/5797332/66048400-b01fdd00-e4e6-11e9-894c-c447747c1ba3.jpg)

**Comment by lukecav** [comment]
@nielslange 

Let me know if you need another version or not.

**Comment by nielslange** [comment]
@lukecav Sorry, I've missed your upload yesterday. Yeah, the image looks much better now. 👍

**Comment by carolinan** [comment]
First, is this the text and image that is meant for a final screenshot?

**Comment by nielslange** [comment]
> First, is this the text and image that is meant for a final screenshot?

@carolinan: @lukecav optimized the screenshot so that the quality remains the same but the file size is smaller.

**Comment by andersnoren** [comment]
@lukecav Thanks for creating the issue – we should definitely shave off every kilobyte we can.

@carolinan I think we might want to revisit it and update it with something less image heavy and more block heavy. I'm planning to take a look at that this weekend.

**Comment by ianbelanger79** [comment]
I think that this should probably wait until the design and starter content are finalized, thus the screenshot will reflect the most updated design.

**Comment by carolinan** [comment]
@lukecav Would you mind taking a look at https://github.com/WordPress/twentytwenty/pull/921

**Comment by lukecav** [comment]
@carolinan 

The new **screenshot.png** looks good to me.
