### ISSUE TITLE
Getting font related error in console while in customizer

### ISSUE THREAD

**Issue by itowhid06** [WordPress/twentytwenty#718]
I am getting getting the following font related error in console while in customizer.
![image](https://user-images.githubusercontent.com/12055657/66036595-73c49f00-e52f-11e9-89fa-ac5d967f3bf7.png)

**Comment by carolinan** [comment]
Hi
Can you show us the actual error, from the log?

This is likely not related to the customizer.
I am seeing the following error on my localhost:
`Syntax error in type map, no ':' in /twentytwenty/assets/fonts/inter/Inter-upright.var.woff2 for header wof2`

This is an issue with the configuration in Apache servers that reads` .var` in the file name of the font as if it was in a different format (a type map):
https://serverfault.com/questions/159152/apache-treating-files-with-var-in-their-names-as-type-maps

**Comment by itowhid06** [comment]
@carolinan, you are right. That was a issue of Apache server configuration. No errors in Nginx server.

**Comment by nielslange** [comment]
> @carolinan, you are right. That was a issue of Apache server configuration. No errors in Nginx server.

@itowhid06 I've close this issue based on your previous comment. 😉

**Comment by carolinan** [comment]
This is still an issue, we will try to rename the font files.
