### ISSUE TITLE
Social Menu icons jump 1px on hover

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#722]
When you mouseover a social menu icon, it jumps 1px to the right and the icon gets blurry.

Before Hover
![fb-icon-no-hover1](https://user-images.githubusercontent.com/34601694/66071502-4113aa00-e521-11e9-8f86-02d3ee9092ba.PNG)

On Hover
![fb-icon-hover](https://user-images.githubusercontent.com/34601694/66071413-19244680-e521-11e9-8d3b-222843d72915.PNG)

**Comment by glauberm** [comment]
Which browser were you testing on? I think this is a issue on how certain browsers handle the `transform: scale` transition. Not sure how to fix it.

**Comment by andersnoren** [comment]
@ianbelanger Can you check if this still happens in #717?

**Comment by ianbelanger79** [comment]
#717 did not fix it @andersnoren. I tested on Windows in Firefox and Chrome and see the issue in both. Surprisingly, IE11 and Edge do not have this issue.

**Comment by glauberm** [comment]
I'm taking a look into that and I believe it's happening due to a mismatch between the paths size and the viewbox attribute. Soon I'll make a PR out of it.

**Comment by glauberm** [comment]
@ianbelanger79 Could you verify if #756 solves the problem?

**Comment by ianbelanger79** [comment]
Fixed by #933
