### ISSUE TITLE
Color issues for the header text on the Cover Template 

### ISSUE THREAD

**Issue by dianeco** [WordPress/twentytwenty#736]
https://github.com/WordPress/twentytwenty/issues/716 was closed by https://github.com/WordPress/twentytwenty/pull/721 but some issues remain, the header text (menu, site title) can be unreadable. 

In `twentytwenty_get_elements_array()`, is there a reason to apply the value of "Header & Footer Background Color" to the overlay header text ` .overlay-header .header-inner`?

https://github.com/WordPress/twentytwenty/blob/303e31c8d979bd24b46c874219211617a7848d33/functions.php#L653-L654

IMO, the overlay header color should be white unless the user specifies a color for "Image Overlay Text Color".
Currently, if we set black for "Header & Footer Background Color", and keep the white default value for "Image Overlay Text Color", the header text is black instead of white.

![color](https://user-images.githubusercontent.com/44895380/66084561-3bdd4c00-e56f-11e9-9c93-d637e8860085.jpg)

**Comment by carolinan** [comment]
The header background color should not affect the cover template.
https://github.com/WordPress/twentytwenty/issues/590

**Comment by andersnoren** [comment]
Sorry @dianeco  – I was too quick in closing that one. I'll create a PR for this in a moment.
