### ISSUE TITLE
Naming suggestions for the menu locations

### ISSUE THREAD

**Issue by andersnoren** [WordPress/twentytwenty#74]
On screen sizes wider than 1000px, the Twenty Twenty design includes a "shortcuts" menu displayed next to the search and main menu toggle in the header.

![twenty-twenty-top-menu-cropped](https://user-images.githubusercontent.com/8181091/64475312-70810200-d181-11e9-9661-c829e85ada5b.jpg)

The intent with the menu location is to provide users with a way to clearly expose a couple of menu items in the header. They can use this menu location in combination with, or instead of, the menu location currently called "Main Menu". The following combinations would be possible on desktop:

- Show the shortcuts menu and the main menu (pictured above)
- Only show the shortcuts menu (like above, but with the navigation toggle removed)
- Only show the main menu (like above, but with the shortcuts menu removed)

In the second scenario, the "shortcuts menu" would practically function as the main menu of the site, making the name "Shortcuts Menu" a very bad fit. Any suggestions on good, easily understood names for the two menus would be much appreciated.

**Comment by nielslange** [comment]
- Full Menu
- Large Menu
- More Menu
- Wide Menu

**Comment by carolinan** [comment]
Horizontal menu (shortcuts)
Sidebar menu, Expanding menu (main)

**Comment by andersnoren** [comment]
I like horizontal menu and expanding menu, but I wonder if we need to get something in both names to communicate that they are only visible on desktop (and landscape tablets, but that's probably not a distinction we need to make in the names).

Maybe:
Horizontal Menu (Desktop)
Expanding Menu (Desktop)

And then simply call the mobile menu "Mobile Menu", since it's the only menu location available on mobile.

**Comment by joyously** [comment]
Is the "Mobile Menu" shown on desktop (adjusting with CSS), or is it only on mobile?
Why would you want them as separate locations? Why would you serve different content (the menu content) to mobile users? What do I get if I like to use narrow windows on desktop?

**Comment by andersnoren** [comment]
The mobile menu would only be shown on mobile. 

The reasoning is that since users have two menu locations available on desktop (the horizontal menu and the expanding menu), they might want to exclude menu items from the expanding menu because they include them in the horizontal menu. If the expanding menu was also the mobile menu, those menu items would not be output at all on mobile.

Basically, by including a separate mobile menu, they can use this structure:

*Mobile Menu*
Home
About
Products
- Product A
- Product B
Contact

*Expanding Menu*
Home
About
Products
Contact

*Horizontal Menu*
Product A
Product B

In the scenario above, if we used the Expanding Menu as the mobile menu, "Product A" and "Product B" wouldn't be displayed.

**Comment by andersnoren** [comment]
Oh, and also, by making the "Mobile Menu" and the "Expanding Menu" separate, we allow the user to not use the "Expanding Menu" on desktop, if they prefer to only display the horizontal menu.

**Comment by joyously** [comment]
Does the Mobile menu use either of the other two as fallback? If not, it sounds like a real hassle.
And if you use names like Main and Primary and Footer and Social, then they are more likely to match up with other themes, so the right menus are used on theme switch (there is code to guess which one is which for a new theme).
Regardless of fallback, it should be made clear to the user which ones appear in only some environments. My thought is that a default theme is a bad place to have this sort of setup conundrum, but then, it might promote a way to do better user documentation or something.

**Comment by pattonwebz** [comment]
The options available for inline help here are pretty limited. We have title and a description only. Could we detail the specifc limitations within those?

**Comment by andersnoren** [comment]
> Does the Mobile menu use either of the other two as fallback? If not, it sounds like a real hassle.

The mobile menu could use either one of them as a fallback, but there might be a scenario where the user would only want to output the horizontal menu on desktop for some reason.

> And if you use names like Main and Primary and Footer and Social, then they are more likely to match up with other themes, so the right menus are used on theme switch (there is code to guess which one is which for a new theme).

We could use the slug `primary` for the expanding menu and `secondary` for the horizontal menu, since that's their primary intended use.

**Comment by KorvinM** [comment]
I think Horizontal Menu could be confusing if a child theme were to alter the layout for any reason. The name is tied to the appearance as opposed to the function.

I suggest
Open Menu ( for Shortcut Menu)
and
Toggled Menu (for Main Menu)

**Comment by KorvinM** [comment]
May we consider retaining the 'Shortcuts' name? On reflection,  it seems to me even in andersnoren's second use case, the name 'Shortcuts Menu' still conveys something of its function - a list of easily-accessible quick links. I'm not sure the name would be such a bad fit even if the user isn't using the toggle menu.

I notice in the code and elsewhere 'modal menu' is used - why not use that? So we could have
'Shortcuts Menu' or 'Open Menu'
'Modal Menu' or 'Toggled Menu'
 
I quite like 'Open' and 'Modal' as a combination

**Comment by KorvinM** [comment]
Just to get into grammatical style issues, I'm not keen on 'Toggled' stylistically. To fit with the word 'open' as an adjective, I'm using the participle of 'toggle' as an adjective. That's OK grammatically in English, but stylistically awkward. I'd prefer just 'Toggle' but it should be paired with another noun in my view. Options using my suggestions:
ADJECTIVAL
'Open Menu' & 'Modal Menu'

NOUNAL
'Shortcuts Menu' &'Toggle Menu'

**Comment by andersnoren** [comment]
Thanks for the comments, @KorvinM! Good point about the shortcuts menu. I may have been a bit hasty in dismissing it altogether.

My concern with both "Modal Menu" and "Toggle Menu" is that I'm not sure how established those terms are among the general public. Anecdotally, I also can't figure out good Swedish translations for either one, whereas "Open Menu" and "Shortcuts Menu" both seem like they would easier to translate, since the words are more common. It would be good with some eyes from the polyglot channel on the suggestions we feel to be the strongest.

Point well made on the mobile menu name.

**Comment by KorvinM** [comment]
Thanks @andersnoren
I take the point about obscurity. Agreed, 'Modal' isn't a widely used word; I think general computer users don't use it, being more likely to say 'window' or 'pop-up' to describe a modal. I think you're right, it's best avoided for the public-facing name of the Menu. And again, it's a bit tied to a specific design pattern as opposed to function.

'Toggle' however, does feel more understood to me. My sense is that the word is used by by general computer users; in consumer electronics generally I think the concept of a 'toggle switch' would be understood by a member of the public of average intelligence. Last night I did a quick bit of anecdotal testing on a friend of mine, who's a craftsman but not much of a computer user, by asking him, without any context, what the word 'toggle' means to him. He felt it meant something to turn something on and off, or switch between two states. In the context of a UI, he suggested you might need a moment's thought about what the word signifies, but he was keen to emphasise that's not necessarily a bad thing.

While 'toggle'  may introduce some cognitive load I'd argue, perhaps controversially, some cognitive load on users isn't necessarily unhealthy, in moderation. I'd modify the mantra "Don't make the user think" to "Make the user think a _little bit, sometimes_".  And in this case I reckon it only really matters at the onboarding stage. Thinking about the user journey, after the first time round setting up the menus, I think the connection is then made between the word and the function. Distinguishing the 'toggle' and 'open/shortcuts' menus then becomes intuitive, once they've established cognitively what the words mean in the context of the menu system. Does that make sense?

I know nothing about Swedish except what I've just googled, but would "strömbrytare" work as a translation of 'toggle'? What word would generally be used to denote an on/off switch, like a light switch?

**Comment by byalextran** [comment]
oop, didn't see this thread before posting [some of my thoughts in an earlier thread](https://github.com/WordPress/twentytwenty/issues/164#issuecomment-530138922). most of which have already been covered in this thread. 

great discussion so far. of everything i've read so far, i'm leaning towards: 

- Shortcuts Menu => Horizontal Menu
- Modal Menu => [Expanded, Extended] Menu
- Mobile Menu => No changes

i like horizontal because it's instantly recognizable where that menu would go. which is also why i prefer it over shortcuts. 

i understand a child theme could change the menu from a horizontal layout to something else, but i believe those odds slim enough that i'd willingly sacrifice that possible disconnect for something clearly understandable for the user. 

and good point about not needing a desktop descriptor because that's implied by having a mobile menu. 

for me, i think naming comes down to what would be the easiest for a user to understand without them having to put menus in different locations to see where they show up on the site.

**Comment by ernilambar** [comment]
While we are at this menu discussion, may be we can also rename the menu location id. Core can map menu location in theme switch if we follow the menu id like `menu-1`, `menu-2`, etc.

**Comment by andersnoren** [comment]
@KorvinM @byalextran First, I super appreciate the time and thought you put into this.

@KorvinM Most people probably would understand "toggle" in this context, true, but I think "Expanded Menu" (as suggested by @byalextran) would be a bit clearer to the average person. It also has the benefit of describing the function the menu has if it's used in combination with the traditional menu – it expands on it with additional menu items. Yes, this would probably only be a problem the first time the user sets up the menus, but for most users, I'm guessing that they only set their menu locations once.

"Strömbrytare" in Swedish would literally be translated to "power switch" in English, but it's not used in an interface context. I'll ask the polyglots channel on Slack for some input on the names in this thread as well.

@byalextran Agreed. The chances of a child theme changing the traditional menu from being horizontal are probably pretty slim, and in that case, the child theme could adjust the name used for the menu to better describe it. I think that's a worthwhile compromise if it makes it more understandable for most users, most of the time.

@ernilambar Those should definitely be updated. The current plan is to give the horizontal menu location the primary id, and the expandable menu location the secondary id. That, in combination with a fallback for the mobile menu that checks the horizontal menu first and the expandable second, should ensure that most users will carry over their existing menus when the theme is activated.

At this point, I'm leaning towards:

- Shortcuts Menu => Horizontal Menu
- Modal Menu => Expanded Menu
- Mobile Menu => No changes

**Comment by tobifjellner** [comment]
Regardless of how we name the menus, would it be possible in the Customizer to clarify under what circumstances a certain menu is shown? 
For instance:
Mobile Menu (shown on window width up to 600px)
Expanded Menu (shown on window width 601px and higher)
Horizontal Menu (shown on window width 1000px and higher)

**Comment by ianbelanger79** [comment]
I think that is a must have

> Regardless of how we name the menus, would it be possible in the Customizer to clarify under what circumstances a certain menu is shown?
> For instance:
> Mobile Menu (shown on window width up to 600px)
> Expanded Menu (shown on window width 601px and higher)
> Horizontal Menu (shown on window width 1000px and higher)

**Comment by andersnoren** [comment]
Thanks for the discussion, everyone – It's been extremely helpful. I wish we could have let it go on for a bit longer, but we're tight on time. I've created a new issue (#246) for implementing the new header structure its menu locations, which are:

* Mobile Menu
* Desktop Horizontal Menu
* Desktop Expanded Menu

I get into it more in both #246 and #164, but in short, I think the names above do a good job of communicating what each menu displays and in which context.
