### ISSUE TITLE
Add back-compat.php?

### ISSUE THREAD

**Issue by ocean90** [WordPress/twentytwenty#743]
It looks like the theme requires at least 5.0.3 after #742. Should a [back-compat.php](https://github.com/WordPress/WordPress/blob/5.2-branch/wp-content/themes/twentynineteen/inc/back-compat.php) file be added to ensure the theme can't be enabled on older WordPress versions?

**Comment by andersnoren** [comment]
@ocean90 I moved too fast when merging that one. I'll create an issue and PR for replacing the current `wp_unique_id` call with a solution similar to the implementation [used in Twenty Seventeen](https://core.trac.wordpress.org/ticket/44883), so we retain support for versions older than 5.0:

```
/**
 * Get unique ID.
 *
 * This is a PHP implementation of Underscore's uniqueId method. A static variable
 * contains an integer that is incremented with each call. This number is returned
 * with the optional prefix. As such the returned value is not universally unique,
 * but it is unique across the life of the PHP process.
 *
 * @since Twenty Seventeen 2.0
 * @see wp_unique_id() Themes requiring WordPress 5.0.3 and greater should use this instead.
 *
 * @staticvar int $id_counter
 *
 * @param string $prefix Prefix for the returned ID.
 * @return string Unique ID.
 */
function twentyseventeen_unique_id( $prefix = '' ) {
	static $id_counter = 0;
	if ( function_exists( 'wp_unique_id' ) ) {
		return wp_unique_id( $prefix );
	}
	return $prefix . (string) ++$id_counter;
}
```
