### ISSUE TITLE
Is "Requires at least" missing from style.css?

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/twentytwenty#747]
I have checked theme Twenty Nineteen and found that in style.css `Requires at least` is defined as below:

```
Requires at least: WordPress 4.9.6
```

Commit: https://github.com/WordPress/twentynineteen/commit/11a2f59ebf6f47f92fbee327d33afdfdeb7345be

Recently it was the `Tested up to`.

So, Is `Requires at least` missing from TwentyTwenty?

**Comment by nielslange** [comment]
@maheshwaghmare While `Tested up to` is used in https://github.com/WordPress/twentytwenty/blob/ed551762647d2e5ad975198b02a709d79aabd188/readme.txt#L4 I'm not sure if it's recommended to add it to `style.css` and `style-rtl.css` as well.

@carolinan, @ianbelanger79 and @pattonwebz Can you clarify if `Tested up to` should be added to `style.css` and `style-rtl.css` or not?

**Comment by carolinan** [comment]
Well is there any background to why it was added to Twenty Nineteen?

As far as I know neither _needs_ to be in style.css.
It is not parsed by the directory or core. It also does not break anything if it is included.

Plugins on the other hand can place it in the readme _or_ the main plugin file.

**Comment by nielslange** [comment]
Personally, I would try to keep information only in places where really needed. Thus, I would remove all entries from `style.css` that are not really needed as well. 

My personal reason is based on maintenance concerns. If something changes, e.g. `Tested up to` and we have that information in several spots, we should update all of them. If we forget to update one spot, we create an inconsistency which might lead to confusion on the end users side.

**Comment by nielslange** [comment]
Personally, I would try to keep information only in places where really needed. Thus, I would remove all entries from `style.css` that are not really needed as well. 

My personal reason is based on maintenance concerns. If something changes, e.g. `Tested up to` and we have that information in several spots, we should update all of them. If we forget to update one spot, we create an inconsistency which might lead to confusion on the end users side.

**Comment by joyously** [comment]
There was a recent discussion from Otto about why the Requires at least got added to the readme instead of the plugin header. I'm not sure if it got changed, but I think it did. There was a ticket to add the check for themes also. Not sure of the status of that either.
The theme readme isn't checked yet, but it will be soon.

**Comment by nielslange** [comment]
@joyously Do you have the link to the discussion with Otto? In this particular ticket, @maheshwaghmare mentioned adding `Requires at least` to `styles.css` and I'm not sure if this is beneficial. In https://github.com/WordPress/twentytwenty/issues/747#issuecomment-538430247 I stated why I have my doubts doing so.

**Comment by joyously** [comment]
See https://meta.trac.wordpress.org/ticket/4514

**Comment by nielslange** [comment]
Thanks, @joyously! 😀

**Comment by ianbelanger79** [comment]
`Tested up to` is not necessary here
