### ISSUE TITLE
Is "@charset "UTF-8";" missing from style.css?

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/twentytwenty#748]
I have checked theme Twenty Nineteen and found that in style.css `@charset "UTF-8";
` is defined at the start of the file.

File: [WordPress/twentynineteen/style.css](https://github.com/WordPress/twentynineteen/blob/master/style.css)

So, Is `@charset "UTF-8";` missing from Twenty Twenty?

**Comment by nielslange** [comment]
@maheshwaghmare As far as I understood adding `@charset "UTF-8";` to `style.css` and `style-rtl.css` is needed when the CSS file also contains Unicode characters, which we don't use currently. However, I don't think it's a bad idea adding it. 

Will you create a PR for it?
