### ISSUE TITLE
RTL issue For Menu - Submenu triangle

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#750]
After switching to the RTL and when we check the submenu then the triangle for submenu is coming doubled we need to handle this case as shown in the screenshot below.

![Image 2019-10-04 at 12 16 40 PM](https://user-images.githubusercontent.com/3323310/66187465-0b043080-e6af-11e9-8073-0eced38b1bb2.png)

**Comment by nielslange** [comment]
@Swapnildhanrale Good catch! Can you provide a fix for this?

**Comment by maheshwaghmare** [comment]
I think we have 3 options:

---

**Option 1:** Using 3rd party lib which converts dynamic CSS into RTL

It comes from dynamically generated CSS from function `twentytwenty_get_elements_array()` internally it uses `twentytwenty_generate_css()`.

So, I think we need to use some library that converts the dynamic CSS for RTL support. 

---

**Option 2:** Modify CSS generation logic from `twentytwenty_generate_css()`

We need to use chnage strings like `left` with `right` and vice versa, `:after` with `:before` with vice versa etc. in function  `twentytwenty_generate_css()`.

E.g.

- `.primary-menu ul ul:after` in RTL - `.primary-menu ul ul:before`
- `.primary-menu ul ul:before` in RTL - `.primary-menu ul ul:after`
- `padding-left` in RTL - `padding-right`
- `padding-right` in RTL - `padding-left`
- etc.

Temporary I have used below code without checking left/right/before/after strings exist in the `$selector` and `$style` like:

![Image](https://maheshwaghmare.files.wordpress.com/2019/10/image-2019-10-04-at-1.13.45-pm.png)

---

**Option 3:** Set different selectors in the function `twentytwenty_get_elements_array()`

We have current selectors like below:

```
'header-footer' => array(
	'text' => array(
		'background' => array(
			'border-bottom-color' => array(
				'body:not(.overlay-header) .primary-menu > li > ul:after'
			),
		)
	)
)
```

This should be as below for RTL support

```
'header-footer' => array(
	'text' => array(
		'background' => array(
			'border-bottom-color' => array(
				'body:not(.overlay-header) .primary-menu > li > ul:after'
			),
			'rtl' => array(
				'border-bottom-color' => array(
					'body:not(.overlay-header) .primary-menu > li > ul:before'
				),
			)
		)
	)
)
```

**Comment by nielslange** [comment]
@andersnoren Your expertise is needed regarding https://github.com/WordPress/twentytwenty/issues/750#issuecomment-538288570. Personally, I would go with `Option 2`, but you might have different thoughts on this. 😀

**Comment by andersnoren** [comment]
@Swapnildhanrale Thanks for creating the issue, and thanks @maheshwaghmare for the comment! In this specific case, we could solve it by changing this:

```
.primary-menu ul ul::after {
	border-bottom-color: transparent;
	border-left-color: #000;
	bottom: auto;
	right: -1.6rem;
	top: 2rem;
}
```

To this:

```
.primary-menu ul ul::after {
	border-bottom-color: transparent;
	/*rtl:ignore*/
	border-left-color: #000;
	bottom: auto;
	right: -1.6rem;
	top: 2rem;
}

.rtl .primary-menu ul ul::after {
	transform: rotate(180deg);
}
```

Which would give us the right the color in the right place on RTL:

<img width="849" alt="image" src="https://user-images.githubusercontent.com/8181091/66255786-40308180-e788-11e9-95cd-32d1b14cd0a1.png">

If there are more cases where having `twentytwenty_get_elements_array()` support RTL specific targeting is needed, then doing so is definitely worthwhile, but if this is the only one, then I think that approach might be a bit on the heavy side.

**Comment by Swapnildhanrale** [comment]
@andersnoren can you add me as a contributor

**Comment by andersnoren** [comment]
@Swapnildhanrale Sure thing! What's your WordPress.org username?

**Comment by Swapnildhanrale** [comment]
Here is my profile @andersnoren Sir - https://profiles.wordpress.org/swapnild/
