### ISSUE TITLE
Update documentation - purpose of this thumbnail

### ISSUE THREAD

**Issue by amolv** [WordPress/twentytwenty#751]
https://github.com/WordPress/twentytwenty/blob/ed551762647d2e5ad975198b02a709d79aabd188/functions.php#L64

**Comment by nielslange** [comment]
@amolv: Are image sizes usually mentioned in the documentation? 🤔

**Comment by amolv** [comment]
@nielslange something like this - `// Used for featured posts if a large-feature doesn't exist.
		add_image_size( 'small-feature', 500, 300 );`
