### ISSUE TITLE
"Retina logo" setting isn't working. Consider replacing it with a "Logo width" setting.

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#752]
- Currently the "Retina logo" option isn't working. It only changes the width and height attributes of the logo <img> tag which doesn't make any change visually. CSS is needed to make it appear half its size.

- Consider renaming the "Retina logo" label as Retina is an Apple trademark

- Currently the goal is to scale the logo to half its uploaded size (x2). However, more and more smartphones and tablets have now higher screen density (x3 / x4). So a x2 logo wouldn't appear sharp on them. As it’s not possible to upload svg, a solution might be to replace the “Retina logo” checkbox by a “Logo width” input number.

**Comment by andersnoren** [comment]
@yannickiki There's a line of CSS included that causes the height and width attributes in the image element to not take effect. I'll add a PR to remove it. When the line of CSS is removed, a 120x90 image will look like this when the setting is disabled:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/8181091/66252646-2ed27f80-e75e-11e9-96ce-ca480d75d181.png">

And like this when it's enabled:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/8181091/66252651-3b56d800-e75e-11e9-9543-1e203e0ccd21.png">

Good point on the name – I'll change it to "High-resolution logo" instead.

I think a 2x logo is still high-resolution enough, even though there are screens with higher resolution nowadays. I think adding a more granular control to this setting (whether it's a setting for the width of the logo or a setting for 1x/2x/3x screen density) would confuse things.

I'll create a PR.

**Comment by yannickiki** [comment]
@andersnoren If the logo is higher than 6rem on mobile or 9rem on tablet (max-height for the logo image defined by the theme), the logo isn't resized proportionally. As a max-height is set for the logo, removing `width: auto` causes this issue.
