### ISSUE TITLE
Accent Color should be color picker similar to Background and Header/Footer Background picker

### ISSUE THREAD

**Issue by amandablum** [WordPress/twentytwenty#754]
Unsure why there's a slider vs letting someone pick custom colors, but from a usability standpoint, that it doesn't allow you to specify a hex is problematic.  Is there a reason we can't use the same picker for all three? 

![2019-10-04_0937](https://user-images.githubusercontent.com/2366499/66224607-29583500-e68b-11e9-8a07-46ab5e1e570a.png)

**Comment by nielslange** [comment]
@amandablum That's a great question and the reasons why it had been implemented in that way is to avoid contrast ratio issues. When providing three color pickers one could pick the identical color for both background, header & footer background and accent color, e.g. black. This would result in having a black text in front of a black background. Which means ... you'ld simply see a black page. The slider, however, allows picking a color on a more granular level and automatically switches the background color, if needed, to ensure a sufficient contrast ratio.

**Comment by amandablum** [comment]
I understand, but that also removes user autonomy, which feels uniquely un
wordpressy, especially for the default theme. a warning would suffice. how
do you implement brand colors w a slider? youre forced to css. if ppl make
bad choices, they'll see it and self correct. or they won't. thats
publishing democracy.

**Comment by joyously** [comment]
Yeah, it's a design choice. If you want exact colors, use a different theme. If you want your colors to meet the a11y guidelines, use something like this.

**Comment by nielslange** [comment]
It's actually the way how to pick color with Twenty Ninteen as well, users can still add custom CSS to overwrite the accent color and no one is forced to use the Twenty Twenty theme in the first place. That what I call democracy. 😉

**Comment by amandablum** [comment]
But that's really not accurate either. you could choose to throw the
contrast in the other direction and would still meet the guidelines. the
reality is that this utilizing from this hue line is not the only way to
meet that standard.

**Comment by nielslange** [comment]
As mentioned before, no one forces you to use the new default theme in the first place and there are many ways in overwriting then accent colors. That's pretty much all I can say here.
