### ISSUE TITLE
Some of my Posts featured images appear as thumbnails on the front-end

### ISSUE THREAD

**Issue by marcustibesar** [WordPress/twentytwenty#757]
Some but not all of my Posts' featured images appear as little thumbnails on the main Blog page as well as on the single Post. 
<img width="1251" alt="Screen Shot 2019-10-04 at 4 43 29 PM" src="https://user-images.githubusercontent.com/55969677/66246284-b8ecfa80-e702-11e9-8934-10a437f774ae.png">

Private website: https://tibesar.com

**Comment by joyously** [comment]
What have you set your Media sizes to? And how big is the actual image?

**Comment by marcustibesar** [comment]
Media sizes are the default (150 x 150; 300 x 300 and 1024 x 1024). The images are usually over 1024 x 1024.

I will run the Regenerate Thumbnails and see if this rids the issue.

Thank you!

**Comment by marcustibesar** [comment]
Running the Regenerate Thumbnails did not resolve the issue. The actual image size is 960 by 688 pixels.

**Comment by nielslange** [comment]
@marcustibesar Thanks for reporting this. I'll analyse this issue now.

**Comment by nielslange** [comment]
@marcustibesar I'm unable to reproduce this issue on my end. Could you post all the plugins that you have currently installed?

**Comment by marcustibesar** [comment]
Amr shortcode any widget

Atomic Blocks - Gutenberg Blocks Collection

BAW Login/Logout menu

BBQ Pro

Code Snippets

Disable XML-RPC

Dynamic Widgets

Favorites

GTranslate

Host Header Injection Fix

Imagify

MB ImageChimp RSS Feed Enhancer

Organize Series

Page Restrict

Regenerate Thumbnails

Remove Dashboard Access

Simple History

Simple User Listing

Tweak Option

User Avatar

WP Crontrol

WP Photo Album Plus

WP Retina 2x Pro

WP Rocket

WPForms

**Comment by acosmin** [comment]
It might be a caching issue :) I haven't used WP Rocket but you should flush/rebuild your cache.

**Comment by marcustibesar** [comment]
After looking for something common between the posts that have featured images appearing as thumbnails on the front-end, it appears that if the actual image size is 960 wide or smaller the featured image appears as a thumbnail on the front-end.

If the actual image size is larger than 960px wide, then the image appears correct on the front-end.

In summary, if the actual featured image size is say 1920px wide it appears correct. If the actual featured image size is say 960px wide it appears as a thumbnail on the front-end...

**Comment by marcustibesar** [comment]
I have cleared WP Rocket cache several times to no avail...

**Comment by marcustibesar** [comment]
I've reviewed many of the Posts that display featured image thumbnails on the front-end. Definitely if the actual featured image size is 960px wide or less (i.e. 720px wide or 640px wide, etc). the theme displays a thumbnail.

**Comment by marcustibesar** [comment]
@nielslange Could you re-test using images that are 960px wide or less?

**Comment by marcustibesar** [comment]
By the way, the new posts using the Gutenberg editor are okay if the actual featured image size is 960px wide or less. The older posts that were created way before WordPress 5 (Gutenberg), is where the problem lies...

**Comment by acosmin** [comment]
for this cases I thin the featured image should have a min-width, 50% would be fine, it represents the content width...

```
.featured-media img {
    margin: 0 auto;
    min-width: 50%;
    height: auto;
}
```

**Comment by marcustibesar** [comment]
That helped. However, these classic Posts featured-images on the front-end are now very blurry. 

https://tibesar.com/blog/page/32/

**Comment by acosmin** [comment]
There's no other way around it 😄 you either set new featured images with a higher width or accept blurry images...

**Comment by nielslange** [comment]
> @nielslange Could you re-test using images that are 960px wide or less?

@marcustibesar I run several tests with an image that is 1200px wide and it worked as expected. I haven't had time to run another test with the plugins that you've mentioned though. I'll do that tomorrow.

**Comment by marcustibesar** [comment]
@nielslange That's correct it works fine with 1200px wide but please try 960px wide - on a Classic post it will publish a thumbnail on the front

**Comment by marcustibesar** [comment]
@acosmin It seems it should display the largest image and not a thumbnail. 

Can't this be coded somehow? If classic and image less than or equal to 960px wide publish full image...

**Comment by marcustibesar** [comment]
I have over 900 classic Posts so changing out images is not an option. Twenty twenty should display the largest version of the image - not its thumbnail...

**Comment by joyously** [comment]
Is your site running WP 5.2.3 or the 5.3 beta?  (the beta has new code that affects image sizes)
Is the problem only in older posts? (the way the featured image is marked _could_ have changed?)

Are you aware that the theme doesn't dictate which image is used? The theme calls a function to get the featured image and WP retrieves it. Can you install [Health Check](https://wordpress.org/plugins/health-check/) plugin and use Troubleshoot mode to disable all plugins (it won't affect other site visitors, just you) and see if a plugin is affecting this?

**Comment by acosmin** [comment]
I don't see where the problem can be... 2020 has just a simple `the_post_thumbnail()` and it doesn't change any filters...

**Comment by marcustibesar** [comment]
@joyously I am running WP 5.2.3.

The problem is with the older posts (before Gutenberg).

I'll install Health Check, disable the plugins and report back.

Thank you!

**Comment by marcustibesar** [comment]
Health Check advised me to install the default theme to determine if the problem is with the theme. I installed the twenty-nineteen theme. Now, the old posts featured images look correct.

**Comment by marcustibesar** [comment]
I will revert to twenty-twenty within the Troubleshooting mode and disable all plugins. And report back...

**Comment by marcustibesar** [comment]
I changed back to twenty-twenty and disabled ALL plugins in Troubleshooting mode.  The old posts featured-images appear as thumbnails on the frontend. Disabling all plugins did not resolve the issue.

**Comment by marcustibesar** [comment]
I have done further testing. ALL posts (Gutenberg and Classic) will display tiny featured image thumbnails on the front-end if the actual featured image size is 960 pixels wide or less! This really needs to be fixed, please!

**Comment by joyously** [comment]
So if the theme calls `set_post_thumbnail_size( 1200, 9999 );` and the original image is less than 960, what happens?

**Comment by marcustibesar** [comment]
I don't know how to answer the question. 

Here is an example: [https://tibesar.com/2018/01/28/oregon-state-football-adds-tim-tibesar-as-defensive-coordinator/](https://tibesar.com/2018/01/28/oregon-state-football-adds-tim-tibesar-as-defensive-coordinator/)

The featured image on this page is 960px x 640px

**Comment by marcustibesar** [comment]
Here is another example. On this page all of the year 2010 posts except one have actual featured images less than or equal to 960px wide. 

[https://tibesar.com/blog/page/122/](url)
