### ISSUE TITLE
Search not usable on small screens

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#77]
On small screens (media query is 700px), it is possible to open both the menu and the search at the same time:

<img width="866" alt="Screenshot 2019-09-07 at 15 37 06" src="https://user-images.githubusercontent.com/1682452/64475653-a9bb7100-d185-11e9-8582-3d3b7b14bda6.png">

Please note that this can be done also on large screens by using the keyboard:
[Edit:] **Clarification:** actually, I used a screen reader to navigate away from the Menu and open the Search.

![Screenshot 2019-09-07 at 15 40 27](https://user-images.githubusercontent.com/1682452/64475685-0cad0800-d186-11e9-9fe3-c69293b44f5c.png)

In this scenario, clicking on the Search input field doesn't appear to do anything.

Under the hoods, there's some JavaScript that moves focus to the menu close `.nav-toggle` element each time the search field is clicked. As focus is continuously moved, it is not possible to use the search.

**Comment by carolinan** [comment]
This seems to have been partially fixed.

All sizes: 
If the search is opened first, then the focus stays within the search modal and the menu cannot be opened.

Small screens:
If the menu is opened first, the search can still be opened. When both modals show, the focus stays within the search modal. The search modal is visually on top of the menu.

Wide screens;
If the menu is opened first, the search can still be opened. When both modals show, the focus stays within the search modal. The search works, but the menu is visually on top of the search, so you can't actually see the submit or close buttons.

Focus still needs to be contained within the expanded menu when it is opened. https://github.com/WordPress/twentytwenty/issues/354

**Comment by karmatosed** [comment]
I can confirm I can use both, although not sure one shouldn't cancel out the other. For me, it feels like if one opens the other should close. What do you think?

**Comment by carolinan** [comment]
With https://github.com/WordPress/twentytwenty/pull/628, the search and menu 
are no longer open at the same time.  
With my limited experience of using screen readers, I have confirmed that the search is usable with NVDA.
