### ISSUE TITLE
block inserter disappears

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#772]
**With a left aligned pullquote, the inserter for the paragraph above it disappears.**
The + icon appears at the bottom of the selected paragraph block, but when I try to click it, it disappears before I get there. The one time I was able to click it, it did nothing.
I first thought this was an editor problem, but I tried it with my theme that does not style the editor and Twenty Fifteen, and it worked just fine on both.

![disappearing-inserter](https://user-images.githubusercontent.com/7957680/66261366-86d6a980-e791-11e9-8abf-14a3da5341ca.gif)

**Comment by andersnoren** [comment]
@joyously Which version of WordPress (or the Gutenberg plugin) are you running? This works fine for me in Safari, Chrome, IE11 and Firefox on WordPress 5.2.3 with and without the Gutenberg plugin active.

**Comment by joyously** [comment]
I was using WP 5.3 beta2.
I noticed that if I made the window wider, it doesn't happen. My typical window width is around 1030px.
I figure it's just some margin overlap or z-index problem.

**Comment by ianbelanger79** [comment]
@joyously did you try testing this using another theme? 2019 for instance?

**Comment by joyously** [comment]
> I first thought this was an editor problem, but I tried it with my theme that does not style the editor and Twenty Fifteen, and it worked just fine on both.

I tried ones I knew didn't have extensive CSS for the block editor.
It could be that the font size of the different themes make the quote block just enough different size so it doesn't overlap.
