### ISSUE TITLE
Unable to access a submenu item of the Desktop Horizontal Menu on tablet (>1000px) 

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#790]
On a tablet (1024px for an iPad or 1366px for an iPad Pro for example) when the user clicks on the menu item (or on its icon) which has a submenu, it always loads the parent page. The submenu appears briefly but it's impossible to click on a submenu item.

The submenu works well inside the modal as the user can click on the icon to open the submenu.

**Comment by carolinan** [comment]
Does the parent menu item have an actual working link, or just a hashtag?
With parent page, do you mean the current page, or the page that the parent menu item leads to?

**Comment by yannickiki** [comment]
@carolinan 

> Does the parent menu item have an actual working link, or just a hashtag?

It does work when the parent menu has a hastag. It doesn't work when the parent menu has an actual working link. 

> With parent page, do you mean the current page, or the page that the parent menu item leads to?

I mean the page that the parent menu item leads to.

**Comment by acosmin** [comment]
what is the expected interaction? Only clicking on the icon would make the submenu visible or clicking on the entire menu item?

**Comment by joyously** [comment]
I would expect that clicking on a menu item would navigate to that link.

**Comment by yannickiki** [comment]
I would expect that:
- when the user clicks on a menu item it would navigate to that link
- when the user clicks on the icon it would make the submenu visible

This solution is consistent with the behaviour of the modal submenu.

**Comment by acosmin** [comment]
I tried something in #800

**Comment by carolinan** [comment]
I don't think that this is related to the width?

**Comment by yannickiki** [comment]
@carolinan Below 1000px the desktop horizontal menu is hidden and is replaced by the modal menu which has no problem with submenus.

**Comment by carolinan** [comment]
It seems to behave differently on Ipads with different iOS versions.
Using 13.1.2 I can't reproduce this. Tapping once shows the sub menu, -and it stays visible and clickable, -tapping twice takes you to the link.
It works for me in Safari, firefox, chrome.

**Comment by carolinan** [comment]
Using an asus android tablet with Safari, the first tap takes me to the parent menu item link and there is no way to use the sub menu.

**Comment by westonruter** [comment]
The fix seems to have been incomplete. Another take: #971.
