### ISSUE TITLE
Long post title breaks the design of the post navigation

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#793]
![postnavigation](https://user-images.githubusercontent.com/54663751/66336447-5c295400-e93d-11e9-888f-9b1effe5710f.png)

I think a max-width should be set for the nav link. Something like `calc(50% - 16px)` to make the title aligned with the separator.

I don't know if this issue should be fixed by #710 .

**Comment by jarretc** [comment]
I ran across this issue the other day while testing as well. Though if you increase the title length of the "I love design" post, you'll see the longer title doesn't necessarily break anything. They both are allowed to fit within the space.

It is just that the longer title spans across what would be the "section" defined by the hr rules.

**Comment by okpierre** [comment]
Would something like this be an improvement?

### landscape view
![twentytwenty-navigation-landscape](https://user-images.githubusercontent.com/1679025/66707256-aaf33700-ed0b-11e9-8058-91b77bb47f17.png)

### landscape view with shorter titles
![twentytwenty-navigation-landscape-shorter-titles](https://user-images.githubusercontent.com/1679025/66707294-35d43180-ed0c-11e9-836b-915d89b03e35.png)

### portrait view
![twentytwenty-navigation-portrait](https://user-images.githubusercontent.com/1679025/66707259-b5153580-ed0b-11e9-9b76-7e7451fcbecd.png)

**Comment by okpierre** [comment]
I've submitted PR. You can view screenshots in my previous post above for reference
