### ISSUE TITLE
Search & Menu togle text can break the design in some languages

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#795]
For example in French "Search" is translated by "Recherche" which is longer and breaks the design. (I'm pretty sure other languages have longer word for "search" which would display the end of the word outside the screen)

![search](https://user-images.githubusercontent.com/54663751/66338654-dcea4f00-e941-11e9-801e-0cc0b3d9bcd5.png)

**Comment by andersnoren** [comment]
@yannickiki Thanks for creating the issue!

I don't mind the text extending wider than the icon, honestly, even if it means that the search text extends beyond the gutter of the site (the righthand 40px line in your image). I don't think there's a good way around that, other than displaying the toggle text next to the icon (which would have other ramifications). 

I would like to restructure the toggle text elements to not use `position: absolute` though, so the toggle width can grow to accommodate the width of the text. That would make it more flexible.
