### ISSUE TITLE
Use "font-display: swap;" on web font

### ISSUE THREAD

**Issue by josephscott** [WordPress/twentytwenty#804]
The web font file is really large, and even self hosting it means that it can take awhile for it to load ( relative to everything else on the page ).  On a default WordPress 5.2.3 with TwentyTwenty activated, font files are 83% of the bytes that go over the wire.

We can speed up the text rendering process by using `font-display: swap;` in the `font-face` block.  To get an idea of what the difference looks like, check out this [before/after comparison in WebPageTest](https://www.webpagetest.org/video/compare.php?tests=191008_RX_39f5decde79d6469238df9bd8b386594%2C191008_2P_00d678f7f46b38ca5ef17522360e3b88&thumbSize=200&ival=100&end=visual#).  The over all experience is much better.

A few references if you aren't familiar with `font-display`:

- `font-display` [possible values](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display), `swap`: "Gives the font face an extremely small block period and an infinite swap period."
- https://caniuse.com/#feat=css-font-rendering-controls

**Comment by joyously** [comment]
When Weston first brought this up (perhaps it was in Slack) a few months ago, I looked at adding it to my theme. I chose not to because of the side effects. (but I'm not remembering the whole thought process now)

**Comment by josephscott** [comment]
The WPT filmstrip I linked to - https://www.webpagetest.org/video/compare.php?tests=191008_RX_39f5decde79d6469238df9bd8b386594%2C191008_2P_00d678f7f46b38ca5ef17522360e3b88&thumbSize=200&ival=100&end=visual# - does a good job of illustrating the trade offs.  On these slower mobile connections and devices Chrome already does a font swap after 2 seconds ( you can see that in the filmstrip ), so you still get a font shift at the end ( after the font finishes loading ).

This changes drops the wait period to a very small amount, enabling the page to show text much earlier in the rendering process.

**Comment by andersnoren** [comment]
Given the size of the font files in Twenty Twenty, I'm in favor of merging this. PR looks good.

**Comment by andersnoren** [comment]
Fixed by #807.
