### ISSUE TITLE
When closing the modals, focus should be moved back to the "opener" element

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#81]
See https://github.com/WordPress/twentytwenty/issues/80

When the Menu and the Search "modals" get closed (by clicking on the close button or pressing Escape or clicking outside of them etc.) focus should be moved back to the element that opened them.

Without focus management, there's a focus loss i.e.: there's no focused element within the page.

Although modern browsers try to be smart and keep track of the so called sequential [focus navigation starting point](https://bugs.chromium.org/p/chromium/issues/detail?id=454172), that's not guaranteed to work with assistive technologies. Certainly doesn't work for IE 11 and potentially for other user agents.

To avoid focus losses, there's the need to move focus back to where the user was before opening the "modals", so they don't get lost.

There are several implementation of this kind of focus management in core and in Gutenberg. It is as simple as:
- get the `document.activeElement` when a "modal" opens
- store its reference somewhere
- when a "modal" closes, move focus back to the stored reference (assuming it's still within the page)
- optionally provide a fallback i.e. a focusable element to move focus to in the (hopefully rare) case the referenced element was removed from the page

**Comment by acosmin** [comment]
My PR seems to work, I didn't need the `activeElement` because it's already defined as `element` in the event.
