### ISSUE TITLE
WordPress JavaScript Coding Standards need to be fixed

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/twentytwenty#822]
There are numerous places within `index.js` that do not meet the WordPress JavaScript Coding Standards.

**Comment by glauberm** [comment]
You'll be taking a look into that? I can do it if you like. We should be using [@wordpress/eslint-plugin](https://www.npmjs.com/package/@wordpress/eslint-plugin), right?

**Comment by ianbelanger79** [comment]
Thanks for the offer @glauberm, could you test and review my PR? We are using linting for JS, these errors are not in the rule-set for this repo or for core.

**Comment by ntwb** [comment]
> these errors are not in the rule-set for this repo or for core.

Are you saying these coding standards are not currently in core? Or they are but the ESLint check doesnt detect them?

**Comment by ianbelanger79** [comment]
They are not checked by ESLint in core, but they are mentioned in the handbook, although the wording in the handbook is not entirely clear. They were brought up during the beta 3 release, so I decided to fix them in order to squash any concerns/complaints.
