### ISSUE TITLE
Search button is not visible

### ISSUE THREAD

**Issue by maheshwaghmare** [WordPress/twentytwenty#824]
If open the search then the search button is not visible.

If we press the `tab` key from the keyboard then it is displayed.

Intentionally hide the search button and showing it with keyboard access?

Or 

This is a bug which should be fixed by adding `right: 0` to the `.search-modal .search-submit`.

![Search Button](https://d2ddoduugvun08.cloudfront.net/items/292j1B0f0D3X0V0X0K3y/Image%202019-10-10%20at%203.56.25%20PM.png?X-CloudApp-Visitor-Id=3364001&v=67abba11)

Watch the video: https://cl.ly/1a3438c46a94
[![Watch the video](https://d2ddoduugvun08.cloudfront.net/items/133R0m2i1O1q3811071q/Image%202019-10-10%20at%203.55.05%20PM.png?X-CloudApp-Visitor-Id=3364001&v=f57e4b24)](https://cl.ly/1a3438c46a94)

**Comment by acosmin** [comment]
it's not a bug :) the tab part is for a11y.

**Comment by maheshwaghmare** [comment]
Okay. The search button is only visible through the keyboard. So, closing the issue.
