### ISSUE TITLE
Desktop Expanded Menu vanishes on smaller screen replaced by Desktop Horizontal Menu

### ISSUE THREAD

**Issue by garretthyder** [WordPress/twentytwenty#828]
Hello,

While testing starter content I noticed that on desktop we see 'Contact' visible form the Desktop Horizontal Menu and if we toggle the menu we see the 'Home', 'About' and 'Blog' from the Desktop Expanded Menu.

But when we reduce the screensize and the menu adapts for mobile there's no menu items visible and when you toggle the menu only 'Contact' from the Desktop Horizontal Menu is available and we've completely lost the Desktop Expanded Menu (Home/About/Blog).

![bc2e953900abf95176c57c362997161f](https://user-images.githubusercontent.com/8726005/66592695-6c624e80-eb4a-11e9-962f-65bda5c22700.gif)

On mobile could we preserve the Desktop Expanded Menu and simply append the Desktop Horizontal Menu to the bottom of it?

Thanks

**Comment by carolinan** [comment]
Would that not defeat the purpose of having a mobile menu?

**Comment by garrett-eclipse** [comment]
Thanks @carolinan if the goal is to have a mobile specific menu shouldn't there be a dedicated menu location for it?

Currently, it seems odd why we wouldn't just use the expanded menu for the mobile menu so the contents of that menu are consistent across all devices. Swapping the menu contents for the horizontal menu also seems limiting as you'd most likely only place a few important links there and have your full menu in the expanded menu.

**Comment by joyously** [comment]
You can read through the menu discussion on Slack, back in September, where we hashed all this out.
The mobile menu does have its own menu location. But it uses the main menu as a fallback if it's empty.
I'm not sure I understand it well enough to explain further.

**Comment by garrett-eclipse** [comment]
Thanks @joyously using the Mobile menu location on a new menu works nicely and clears things up. SO I guess my qualm is more with when nothing is using the mobile location it currently defaults to use the menu set to the Desktop Horizontal Menu when I feel it would make more sense to default to the Desktop Expanded Menu when the Mobile menu location isn't set.

**Comment by andersnoren** [comment]
Hi @garrett-eclipse,

Since the horizontal menu is the more traditional one, the decision was made to make that one the default menu location in the theme. If a user switches to Twenty Twenty from a different theme, any menu set to one of the following menu locations in their previous theme will automatically be moved to the `primary` menu location (Desktop Horizontal Menu) in Twenty Twenty:

```
array( 'primary', 'menu-1', 'main', 'header', 'navigation', 'top' )
```

There's no similar matching done for the "Desktop Expanded Menu", which means that the expanded menu is only used if the user manually sets a menu to it. Because of this, it's more likely that the "Desktop Horizontal Menu" will have a menu set, which is why it's used as the primary fallback for the mobile menu. The "Desktop Expanded Menu" is used as the secondary fallback, followed by a `wp_list_pages()` fallback as the catch-all.

— Anders

**Comment by garrett-eclipse** [comment]
Thanks @andersnoren I appreciate the explanation.

It sounds like the issue resides more in the starter_content setup and it's menu use. In many cases, new users will simply update the content of starter pages but leave the menu setup as is. For these users, the existing setup means their menu containing 'Home', 'About' and 'Blog' will vanish without them realizing. As such I setup PR #876 which moves the starter_content pages into the primary menu and drops the use of the 'Desktop Expanded Menu'. I understand we want to showcase all functionality but feel with the current setup we disservice many bloggers who just install and run with WordPress.
*The other option is to move it all into the 'Desktop Expanded Menu' and drop the primary so the secondary fallback is used. This may provide a more uniform experience across devices for users.

With the starter content item address I also just wanted to flag the disconnect caused when a user does use both desktop menus without setting a mobile as those users will find the contents of the more menu changes between desktop and mobile. In that case, the same toggle ('Menu' w/ three dots) reveals completely different content on mobile vs desktop. And we lose what's there on desktop when we move to mobile. I'm still unsure how to deal with that case, maybe documentation to indicate this nuance to users so they aren't surprised when they find access to certain pages is lost unless they specifically setup a mobile menu or assign it to the mobile menu location. 

All the best
