### ISSUE TITLE
On mobile labels for Search and Menu aren't aligned with icons

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/twentytwenty#829]
Hello,

On desktop the labels under the icons for search and menu are aligned nicely;
<img width="320" alt="Screen Shot 2019-10-10 at 10 42 01 AM" src="https://user-images.githubusercontent.com/8726005/66592852-b5b29e00-eb4a-11e9-912c-ed0a021c809b.png">

But once we get to mobile they're a little off-kilter;
<img width="89" alt="Screen Shot 2019-10-10 at 10 42 06 AM" src="https://user-images.githubusercontent.com/8726005/66592880-c3682380-eb4a-11e9-829f-50a049b8105d.png">
<img width="70" alt="Screen Shot 2019-10-10 at 10 42 10 AM" src="https://user-images.githubusercontent.com/8726005/66592881-c3682380-eb4a-11e9-9064-23b02b3b9768.png">

Thanks

**Comment by okpierre** [comment]
@garrett-eclipse it looks good during my test using the latest theme version and Wordpress 5.2.3. which browser are you using?

![twentytwenty-mobile-menu-alignment](https://user-images.githubusercontent.com/1679025/66623512-06adab00-ebba-11e9-824f-aa639d02fd16.png)

**Comment by garrett-eclipse** [comment]
Thanks @okpierre seeing it on smaller mobile I understand why the alignment change occurs so the search and menu are aligned with their respective sides. I was testing while resizing the chrome browser and didn't initially realize why the alignment changed during resize to smaller view. 

Closing this out
