### ISSUE TITLE
SVG icons are focusable on Webkit browsers, breaking keyboard navigation

### ISSUE THREAD

**Issue by afercia** [WordPress/twentytwenty#83]
To better illustrate the problem, please see the animated GIF below. I used an additional CSS red outline to highlight the focused elements.

Can reproduce on latest Chrome, Safari, and Opera on macOS. Haven't tested on Windows.

![svg focus](https://user-images.githubusercontent.com/1682452/64476434-bb554680-d18e-11e9-82bb-046d3b622c1e.gif)

Simply pressing the tab key to navigate through the focusable element within the page, the SVG icons receive focus even when they're within other focusable elements e.g. links.

This makes keyboard navigation almost unusable, as it's completely unexpected and confusing. It also forces users to press the Tab key multiple times to get through an element.

Quickly looking at the code, noticed a couple things:

Attaching a `focus` event to _all_ the elements via the universal selector seems to trigger this behavior in webkit:

https://github.com/WordPress/twentytwenty/blob/a803344b70d915c48e1a85745153f5827c442d87/assets/js/construct.js#L762-L774

Doesn't seem the best option to me in the first place, because this code literally attaches a focus event to _any_ element within a page.

To my understanding, this code is meant to constrain Tab navigation within the Menu and Search "modals". However, the implementation should be reviewed to avoid serious side effects like the one above.

Also noticed the SVG icons get a `tabindex="-1"` attribute: 
https://github.com/WordPress/twentytwenty/blob/a803344b70d915c48e1a85745153f5827c442d87/parts/classes/class-svg-icons.php#L20

Not sure what the original intent is. Usually, `tabindex="-1"` is used to make an element  programmatically focusable via JavaScript. However, SVG icons shouldn't be focusable.

In the same way, `tabindex` shouldn't be allowed on the SVG elements:
https://github.com/WordPress/twentytwenty/blob/a803344b70d915c48e1a85745153f5827c442d87/functions.php#L394-L420

**Comment by andersnoren** [comment]
@afercia I've included a temporary fix for the focus issue in #71, until the jQuery is rewritten to native JS and a better solution can be found for managing the modal focus. That PR also removes tabindex from `TwentyTwenty_SVG_Icons::get_svg()` and `twentytwenty_get_theme_svg()`.

**Comment by joyously** [comment]
> Not sure what the original intent is. Usually, `tabindex="-1"` is used to make an element programmatically focusable via JavaScript. 

No, the `tabindex="-1"` is so that something that is usually focusable is not a stopping point for the tab key. (the tab key would skip that element when it would normally stop there)
But it also has the effect of allowing a non-focusable element to be focused with JS.

**Comment by afercia** [comment]
> No, the tabindex="-1" is so that something that is usually focusable is not a stopping point for the tab key. (the tab key would skip that element when it would normally stop there)

This issue is about SVG images, which are _not focusable_ so my previous comment relates to elements that are non-natively focusable: `tabindex="-1"` makes them programmatically focusable.

Instead, when used on elements that are natively focusable, things change. By using `tabindex="-1"` this way, the element won't be in the tab order so it won't be usable for _some_ users. However, _other_ users can still use that element. Basically, this pattern introduces an inconsistent experience between different groups of users. 

Although it's not "tabbable", a natively interactive element with `tabindex="-1"` is still reachable using assistive technologies and thus can still be activated. For example, with a screen reader navigation through content is operated mainly via Arrow keys. The Tab key is typically used only within forms and on some ARIA widgets. Not to mention there's literally a multitude of ways to still get to that element. Besides arrow keys, there are shortcuts to jump through links, buttons, form fields, etc.

One more example: with speech recognition software it's possible to click interactive elements even if they have a `tabindex="-1"` attribute.

There are cases where the usage of `tabindex="-1"` is legitimate. For example some ARIA widgets (menuts, toolbars) implement their own focus management system and set `tabindex="-1"` on the inactive items. It is also used to implement arrows navigation on some widgets. But in these cases, the interaction is the same for all users.

In most of the other cases, the usage of `tabindex="-1"` on normal links, buttons, etc. should be considered with care and generally avoided.

**Comment by andersnoren** [comment]
Fixed by #71
