### ISSUE TITLE
Mix of EN and EM dash in 'Find Us' starter widget content

### ISSUE THREAD

**Issue by garrett-eclipse** [WordPress/twentytwenty#830]
Hello,

In the Find Us widget there's a mix of EM and EN dashes when it comes to the seperator between days of the week vs the times. The one between Monday-Friday is a EM Dash while the ones between the times are EN dash.

Cheers

**Comment by nielslange** [comment]
@garrett-eclipse I'm unable to find that part in both `master` and `update/starter-content`. Can you tell me in which file and in which line this issue occurs?

**Comment by garrett-eclipse** [comment]
Sorry @nielslange appears this is part of WP core;
https://github.com/WordPress/wordpress-develop/blob/7a682e690e4915411777080ebc2999da69ad3a39/src/wp-includes/theme.php#L2058

Closing here

**Comment by garrett-eclipse** [comment]
Moved ticket here - https://core.trac.wordpress.org/ticket/48286#ticket
