### ISSUE TITLE
The mobile menu does not constrain focus when a fallback is used.

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#832]
**When no menu is assigned:**
**Desktop:** A one level fall back menu is used. No issues found.
**Mobile:**
The menu can be opened with keyboard.
Items can be navigated through with keyboard.
However, the focus is not constrained within the menu modal. When you tab forwards from the last menu item, an item on the page below the menu is targeted. You can't see the focus because the page is covered by the open menu.
-It is possible to tab backwards to close the menu using the button, but it is not intuitive.

**Comment by acosmin** [comment]
@c4rl0sbr4v0 yes, please do 👍

**Comment by andersnoren** [comment]
It looks like none of the modal menus (mobile or desktop, fallback or not fallback) constrain focus currently. Could [this conditional](https://github.com/WordPress/twentytwenty/blob/master/assets/js/index.js#L444) in `goBackToCloseButton` be causing it?

```
mobileMenu = document.querySelector( '.mobile-menu' );

if ( mobileMenu ) {
	return false;
}
```

There's always an element with the `.mobile-menu` class output, so I think that conditional always returns false.

**Comment by acosmin** [comment]
@andersnoren wow :) that's a huge type, sorry for that, I meant for it to be `if( ! mobile...`

**Comment by andersnoren** [comment]
@acosmin No worries, it happens 🙂
