### ISSUE TITLE
After closing modals, aria-expanded is still set to true

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#833]
When closing the search modal, the aria-expanded of the _search-toggle mobile-search-toggle_
remains set to true, it needs to be set back to false.

When closing the the expanded menu or the mobile menu (both assigned and fallback)
the aria-expanded of the _nav-toggle mobile-nav-toggle_ remains set to true, it needs to be set back to false.

**Comment by carolinan** [comment]
If I understand this correctly, it is because the toggles are only pressed once, they are not used to close the modals.  Similarly, the close buttons will only be pressed once. 
So using the JS toggle attribute will not work here. 
https://github.com/WordPress/twentytwenty/blob/master/assets/js/index.js#L646
https://github.com/WordPress/twentytwenty/blob/master/assets/js/index.js#L771

**Comment by ianbelanger79** [comment]
Looks like this was fixed by #835
