### ISSUE TITLE
Link Hover For Categories Have Delay

### ISSUE THREAD

**Issue by okpierre** [WordPress/twentytwenty#840]
Noticed a slight delay for the link hover style for categories

![twentytwenty-link-hover-category](https://user-images.githubusercontent.com/1679025/66687641-52f7fa00-ec51-11e9-96a6-69d33a958fe1.gif)

entry title, site title, menus, etc. do not have this

edit:
created PR for style.css and also style-rtl.css
added screenshot to show delay

**Comment by andersnoren** [comment]
Hi @okpierre,

The transition on those links is deliberate, so I'm closing this issue and the PRs. The reason for the lack of a transition on the other links is because `text-decoration: underline` doesn't support transitions.
