### ISSUE TITLE
Post-date links have incorrect permalink value

### ISSUE THREAD

**Issue by aen3as** [WordPress/twentytwenty#843]
Post-date links have incorrect href value in blog archive entries. I think the post-date tag should link to the day/month/year archive, but the href value is generated with `the_permalink()` function: /twentytwenty/inc/template-tags.php, line 363.

**Comment by joyously** [comment]
No, this is standard practice, so that there is always a link to the single post page, even if it doesn't have a title.

**Comment by andersnoren** [comment]
Closing this issue for the reason given by @joyously.
