### ISSUE TITLE
Consider using WordPress core social icons svg paths to fix current issues

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#848]
Currently there are issues with the social icons #722 trying to be fixed with #756.
A quick win would be to use the social icons svg paths which are now in core (that came with the upcoming block social icons). This solution has no licence issue. Moreover It would be more consistent (the block and the theme will share the same icons).

https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/social-link.php

**Comment by carolinan** [comment]
It would not be backwards compatible.

**Comment by yannickiki** [comment]
I meant to only use the svg paths and not the block. Would that be ok?

**Comment by acosmin** [comment]
The problem is that file isn't available in WP v5.2 or lower. It would be compatible only with 5.3.

**Comment by yannickiki** [comment]
> The problem is that file isn't available in WP v5.2 or lower. It would be compatible only with 5.3.

What I meant was to simply copy the svg paths from core to replace the current svg paths (Socicon) inside `class-twentytwenty-svg-icons.php`. There wouldn't be any backwards compatibility issues.

**Comment by acosmin** [comment]
yes, I think that can be done :)

**Comment by carolinan** [comment]
There is no license issue with the current icons or the PR that edits them. We only need a note that they have been altered.

**Comment by yannickiki** [comment]
> Moreover It would be more consistent (the block and the theme will share the same icons).

For example currently the Facebook icon used inside the theme isn't the official one (https://en.facebookbrand.com/) whereas the block use it. Once the social block will be merged there will be inconsistencies if the user inserts the social icon block inside a page and displays the theme social icons inside the footer.

**Comment by carolinan** [comment]
And do we know where these icons are from?
I don't see any license information for the icons in Gutenberg.
@karmatosed Do you know anything more about the license?

**Comment by acosmin** [comment]
@carolinan I think https://github.com/Automattic/social-logos - GPLv2
