### ISSUE TITLE
button (text and background) color issue in cover block

### ISSUE THREAD

**Issue by kevIN-kovaDIA** [WordPress/twentytwenty#851]
Namaste,

great work team 2020.

i found one issue, i am using cover block. i had chosen pink theme colour as a background. and then add title and description in white colour. after that, i add button block, wherein backend i can see properly that background colour is white and text colour is a pink colour as shown in attached images. but, when i see on the front end, there is some error. this error specifically on the cover block. after that, i tried button block without cover block, and it works fine.  

Kindly do needful. 5.3 & theme 2020 are awsome.

![Screenshot from 2019-10-14 19-47-10](https://user-images.githubusercontent.com/38972017/66762486-b4270400-eec3-11e9-9605-bd8a9f2dddce.png)
![Screenshot from 2019-10-14 19-47-22](https://user-images.githubusercontent.com/38972017/66762740-2d265b80-eec4-11e9-9f6e-336af5a32075.png)

**Comment by brentswisher** [comment]
@kevIN-kovaDIA I tried to recreate this with the latest copy of twentytwenty and the 5.3 RC2 and I was unable to recreate it, just to verify the steps you are taking:

1. Create a new Post
2. Add a Cover Block (Set to full width)
3. Set the background color to pink
4. Add a title
5. Add a line of text
6. Add a button block (while still in the cover block)
7. Set the background of the button to white and the text to pink

Doing that I get this: 
<img width="1268" alt="test_–_WordPress_Develop" src="https://user-images.githubusercontent.com/6653970/67348174-17dbad80-f512-11e9-93b8-03163f3d1cb8.png">

If you update to the latest version of the theme and RC2 are you still seeing the issue?

**Comment by kevIN-kovaDIA** [comment]
yes, after updating the theme to the latest version, th issue is solved now. thanks for the reply and correction. waiting for the 12th of November 2019.
![Screenshot from 2019-10-26 16-13-27](https://user-images.githubusercontent.com/38972017/67618331-a6e70f00-f80b-11e9-91ec-4716b658552b.png)

**Comment by andersnoren** [comment]
Thanks for the confirmation @kevIN-kovaDIA! Closing this as fixed.
