### ISSUE TITLE
Editor width ignores full-width template

### ISSUE THREAD

**Issue by TimothyBJacobs** [WordPress/twentytwenty#856]
When editing a page that is using the full width template, the editable area is the same size as the standard page width.

I'd expect that the editable area inside the editor would get larger. This would especially be helpful when trying to use columns. The editor makes it seem like there really isn't enough room, when in fact there is plenty of space on the front-end.

![Screen Shot 2019-10-15 at 3 16 47 PM](https://user-images.githubusercontent.com/3460448/66862628-4e885580-ef5f-11e9-8292-7e0fd32cbfea.png)
![Screen Shot 2019-10-15 at 3 20 17 PM](https://user-images.githubusercontent.com/3460448/66862652-547e3680-ef5f-11e9-96e5-9af179c36773.png)

**Comment by pattonwebz** [comment]
Yup I agree the width should better update to reflect the template chosen and how it looks front end.

What flags do we get added to the editor that we can use to detect this? Maybe editor adds a special template specific class on the wrapper?
