### ISSUE TITLE
Preview vs. Published - Layout inconsistency

### ISSUE THREAD

**Issue by RickorDD** [WordPress/twentytwenty#859]
Preview vs. Published

<img width="446" alt="Bildschirmfoto 2019-10-16 um 10 50 18" src="https://user-images.githubusercontent.com/6922544/66905519-4c2d0680-f006-11e9-90a8-3a84e9fdcd96.png">

**Comment by RickorDD** [comment]
I just saw that this was fixed in 5.3-RC1-46560

**Comment by carolinan** [comment]
Great, if it's fixed lets close it.
