### ISSUE TITLE
big tag, code tag, small tag - size - and quote tag italics

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#88]
The `<big>` tag is not big.
The `<code>` tag is _too_ big.
The `<small>` tag is not small.
The `<q>` tag is italic. (but it can have nested `<em>`)

Legacy content can have deprecated HTML, but they should still be styled.
This is all related to #6.

![big-and-code-size](https://user-images.githubusercontent.com/7957680/64477215-5f72c980-d15e-11e9-868f-04959537276e.jpg)

![quote-and-small](https://user-images.githubusercontent.com/7957680/64477301-7534be80-d15f-11e9-942c-5bae8f6c88d3.jpg)

**Comment by ZebulanStanphill** [comment]
In case anyone is confused, the `<small>` element is *not* deprecated (much to my surprise when I first found out about it); it has a semantic meaning in HTML5:

"The `<small>` element represents side comments such as small print."

"The `<small>` element should not be used for extended spans of text, such as multiple paragraphs, lists, or sections of text. It is only intended for short runs of text. The text of a page listing terms of use, for instance, would not be a suitable candidate for the `<small>` element: in such a case, the text is not a side comment, it is the main content of the page."

https://www.w3.org/TR/html53/textlevel-semantics.html#the-small-element

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small

So technically, it doesn't have to be literally smaller than other text, but it should have some suitable stylistic distinction, and making it's text content be smaller than the surrounding text is probably the simplest way to accomplish that.
