### ISSUE TITLE
Button block without alignment is missing vertical margin

### ISSUE THREAD

**Issue by andersnoren** [WordPress/twentytwenty#887]
Since the block base margin refactoring, button blocks without alignment is missing vertical margins.

Current | Expected
------------ | -------------
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/67140917-35352100-f25f-11e9-8419-7562298ead3b.png"> | 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/8181091/67140939-4c740e80-f25f-11e9-9aa3-0d6874931897.png">

**Comment by joyously** [comment]
Is there a separate issue for the Rounded button not being rounded?

**Comment by andersnoren** [comment]
The theme only includes the "Fill" (default) and "Outline" button styles, so it doesn't have a rounded style. The style also isn't called rounded in the block editor – the default block styles just styles "Standard" as rounded.

**Comment by joyously** [comment]
I see. I always thought it odd that the default required a style to achieve it.
