### ISSUE TITLE
next and previous post navigation shows underline on arrows

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#899]
When you focus or hover on the next and previous post link, the arrow is underlined:

![nav](https://user-images.githubusercontent.com/7422055/67162193-15d2ec80-f362-11e9-8b29-22fa97de16a4.png)

**Comment by joyously** [comment]
Isn't that a good thing? It shows it is part of the link.

**Comment by carolinan** [comment]
To me it looks more like the arrow symbol is distorted.

**Comment by Aurorum** [comment]
PR in #907 :)

<img width="346" alt="Screenshot 2019-10-21 at 20 31 31" src="https://user-images.githubusercontent.com/43215253/67236959-2c507500-f442-11e9-86d8-7ed37fff64a9.png">
