### ISSUE TITLE
Remove the byline/date on pages

### ISSUE THREAD

**Issue by kraftbj** [WordPress/twentytwenty#9]
On a static page, I'd love to not have the author or the date listed. It doesn't really matter that my about page is 9 years old (screenshot below).

At least as an option if there's a desired decision to keep it.
![2019-09-06 at 16 08](https://user-images.githubusercontent.com/88897/64460691-add18b00-d0c0-11e9-9815-9cc84abb37e3.jpg)

**Comment by joyously** [comment]
Yes, that information should not be shown on static Pages. It's part of the definition of the post type.

**Comment by carolinan** [comment]
Fixed and merged with https://github.com/WordPress/twentytwenty/pull/20
