### ISSUE TITLE
Why show excerpt with full content?

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#90]
Posts with manual excerpts show the excerpt in the archive list and also on the single post page. This is followed by the full content. It makes no sense to show both.

The excerpt is also centered, which makes it difficult to read and since manual excerpts can have HTML tags, it can look really bad such as an ordered list.

**Comment by carolinan** [comment]
I assume that is meant as a lead text. 
I personally like it but perhaps it should be an option that is disabled by default.

**Comment by ZebulanStanphill** [comment]
@carolinan Doesn't the "more" tag/block already allow someone to set the first few sentences of a post as a lead?

**Comment by andersnoren** [comment]
@ZebulanStanphill It does, but that would display it as part of the `post_content` output. The idea with the manual excerpt in Twenty Twenty is to enable users to display a summary of the post in the post header, separate from the main content area. 

That being said, I agree with @carolinan that it's probably a good idea to make this an opt-in setting in the Customizer.

**Comment by ZebulanStanphill** [comment]
@andersnoren Ah, I see. So like this, then?

![lead-example](https://user-images.githubusercontent.com/19592990/64492968-ecda1a80-d23f-11e9-8bfe-e2111226dd33.png)

Semantically, I don't think the excerpt field should be used for that... it seems like something that belongs in a separate field, e.g. https://wordpress.org/plugins/wp-subtitle/ )

**Comment by brentlogan** [comment]
I agree about the semantics but there's precedence for doing this: twenty sixteen did the same thing.

**Comment by carolinan** [comment]
Considering "decisions not options", should we leave this as it is now?

**Comment by ianbelanger79** [comment]
We are leaving this as is for now
