### ISSUE TITLE
Automatic Darkmode

### ISSUE THREAD

**Issue by RickorDD** [WordPress/twentytwenty#902]
i tested the Automatic Darkmode in **Twenty Nineteen** with Additional CSS, thats run perfect.

But in **Twenty Twenty** Background Color not change.

![Bildschirmfoto 2019-10-21 um 13 53 04](https://user-images.githubusercontent.com/6922544/67203001-3fdfe980-f40a-11e9-971b-a04242bb7237.png)

**Comment by carolinan** [comment]
Would the background color option not be sufficient?  You have already changed it to blue.

**Comment by RickorDD** [comment]
ok

**Comment by carolinan** [comment]
This is still valid :) I just did not understand you at first.
