### ISSUE TITLE
Font Inter-upright-var.woff2 file not loading, giving 404 error.

### ISSUE THREAD

**Issue by debabratakarfa** [WordPress/twentytwenty#903]
/themes/twentytwenty/assets/fonts/inter/Inter-upright-var.woff2 not loading, is this problem for VVV or theme label issue.

**Comment by carolinan** [comment]
Hi
Can you provide any more information? There are two font files, is the other one working?
is there a line number and file name?

**Comment by debabratakarfa** [comment]
<img width="1512" alt="Screenshot 2019-10-22 08 17 05" src="https://user-images.githubusercontent.com/2614495/67256382-59357400-f4a4-11e9-9f6e-b47fc79ac2dd.png">

**Comment by carolinan** [comment]
Is this the RC 1 version? We think it might be from packing RC1..  What happens if you download the latest from Github?

**Comment by debabratakarfa** [comment]
Oh, might be ... Actually I am downloading it from SVN ... which it bundles with 5.3

**Comment by ianbelanger79** [comment]
This should be fixed in 5.3 RC2
