### ISSUE TITLE
New Enhancement - Add link color option 

### ISSUE THREAD

**Issue by RobSteele** [WordPress/twentytwenty#905]
Would be nice to be able to change the default pink link color from the color menu in customization

**Comment by carolinan** [comment]
@RobSteele You change the link colors by selecting the custom option under Primary color.

![colors](https://user-images.githubusercontent.com/7422055/67260024-52edca80-f499-11e9-9248-14565364d60c.png)

**Comment by RobSteele** [comment]
Oh wow, so easy yet so hidden. Is there a reason it is a radial button vs looking and feeling like the color options above ?
![image](https://user-images.githubusercontent.com/8963126/67278231-94c94180-f496-11e9-90d9-3dc97c927cf6.png)
Thanks for pointing out the option :)

**Comment by Aetles** [comment]
Also: the slider makes it impossible to choose black as primary color. But that's by design maybe?

**Comment by carolinan** [comment]
You can always add the colors with the custom css option but I would recommend that you keep the colors accessible since it will enable more people to use your website.
