### ISSUE TITLE
Add basic print styles

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#91]
When I use Print Preview, it shows down to the page title on a blank page, then the content, navigation links, comments, comment form, and widget areas on subsequent pages. This all takes many pages.

There should be some print styles to reduce the font size, hide the interactive elements such as menu, nav links, comment form, widget areas, and get the content on the same print page as the title. 

![print-page-1](https://user-images.githubusercontent.com/7957680/64477816-900a3180-d165-11e9-88d0-89c669935cc1.png)

![print-page-2](https://user-images.githubusercontent.com/7957680/64477815-900a3180-d165-11e9-8641-5dc2c91a6a2d.png)

**Comment by joyously** [comment]
Can't we just merge this and then fix stuff?

**Comment by nielslange** [comment]
@joyously I've just pushed an updated version of this PR.

@carolinan, @pattonwebz or @pattonwebz Can we merge this PR, as suggested by @joyously in https://github.com/WordPress/twentytwenty/issues/91#issuecomment-533826413 and then iterate toward the final version?
