### ISSUE TITLE
Themes are required to be child theme friendly

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#910]
After #683, the theme is less child theme friendly than before.
Imagine these scenarios.
1. Child theme has style.css only.
 - child style.css is loaded, using 'twentytwenty-style-css' id and child version number
 - generated styles loaded
 - print style is loaded using 'twentytwenty-print-style-css' id and child version number
 - **parent style is not loaded**
2. RTL mode: Child theme has style.css only.
 - child style-rtl.css is loaded, using 'twentytwenty-style-rtl-css' id and child version number
 - generated styles loaded
 - print style is loaded using 'twentytwenty-print-style-css' id and child version number
 - **parent style is not loaded**
3. Child theme has style.css and a functions.php which enqueues parent style (copy code from parent). `$theme_version = wp_get_theme()->get( 'Version' );
	wp_enqueue_style( 'twentytwenty-style', get_template_directory_uri() . '/style.css', array(), $theme_version );`
 - parent style.css is loaded using  'twentytwenty-style-css' id and child version number
 - generated styles loaded
 - print style is loaded using 'twentytwenty-print-style-css' id and child version number
 - **child style is not loaded**
4. RTL mode: Child theme has style.css and a functions.php which enqueues parent style (copy code from parent). `$theme_version = wp_get_theme()->get( 'Version' );
	wp_enqueue_style( 'twentytwenty-style', get_template_directory_uri() . '/style.css', array(), $theme_version );`
 - parent style-rtl.css is loaded using  'twentytwenty-style-rtl-css' id and child version number
 - generated styles loaded
 - print style is loaded using 'twentytwenty-print-style-css' id and child version number
 - **child style is not loaded**

I could list two more cases of the child theme loading the parent style and the child style, each using the correct handle and version number, but that is not at all child theme friendly. This checking and loading belongs in the parent theme, so that the child theme doesn't have to do much.

The parent theme should always load the parent styles, with the correct parent handle and parent version number.
Optionally, the parent theme can load the child styles with the child version number, so the child theme doesn't have to. Using `get_stylesheet_uri()` for parent styles causes a mismatch of handle and version number.
The reason that the confusion comes in is that the first call to `wp_enqueue_style` for a handle wins, and subsequent calls for that handle are ignored. The child is loaded before the parent.
See https://github.com/WordPress/twentytwenty/issues/682#issuecomment-537203124 for one way to code it to get the correct results in all the above cases.
(That 682 issue had an incorrect Expected Result, causing unwanted changes.)

**Comment by joyously** [comment]
I forgot to mention the case in which the child functions.php enqueues only the child style with the child handle and the child version number. (This is the Expected responsibility for a child theme.) 
In this case, the child style would be loaded twice with two different ids, and the parent style is not loaded.

**Comment by aristath** [comment]
To me these look more like cases where the child-theme author doesn't know how to enqueue styles. The theme _is_ child-theme friendly, as long as one knows how to build child-themes.
If someone just wants to add some styles there's the custom-css field in the customizer. That is not what child-themes are for.

**Comment by joyously** [comment]
Yes, that is the standard: parent themes make it as easy to build a child theme as possible. Most people don't understand how to build a child theme, and get very confused about loading style sheets.
The expected result of a simple child theme is that it looks like the parent with minor changes. The current actual result of a simple child theme is that the parent styles are not loaded.

**Comment by nielslange** [comment]
The child-theme logic of Twenty Twenty behaves identical the child-theme logic of Twenty Nineteen, Twenty Seventeen, Twenty Sixteen, Twenty Fourteen, Twenty Thirteen, Twenty Twelve, Twenty Eleven and Twenty Ten. Only exception if the child-theme logic of Twenty Fifteen, which seems to be broken.

IMHO changing the logic leads to more confusion than keeping the current logic. Also, _"Most people don't understand how to build a child theme"_ is not a strong statement in my opinion. There are enough resources out that that show how to create a child theme.

**Comment by joyously** [comment]
So they are all broken, that doesn't mean this theme should copy that.
If you don't like the title of this issue (about it being a requirement), perhaps you could focus on the facts for the current code:
- the wrong handle is associated with the style sheet
- the wrong version number is associated with the style sheet
- the child theme does not know the dependencies to associate with the style sheet
- in some cases, (the simplest case), the styles aren't loaded at all

The burden of doing it correctly should be on the parent theme, not the child.
All of the bundled themes should be fixed, but it would be more difficult to fix the older ones since they already have child themes made for them. This theme should start out correct, because it's harder to fix it later.

**Comment by pattonwebz** [comment]
While this might actually just complicate things even farther this is how I would view an ideal loading scenario:

- Parent theme loads it's own styles, with it's own handle and it's own version string.
- Child loads it's own styles, with it's own handle and it's own version string.

That's it really. I don't want the parent to load the child styles and I don't want the child to load the parent styles - but child should be able to dequeue parent styles from child. And for record this is my personal opinion of it after seeing hundreds (thousands maybe?? lol) of themes for .org distribution - it's not necessarily an official stance of any kind.

**Comment by joyously** [comment]
I can agree to that. But I think most themes don't get the correct version number in the parent. (If you use the `get( 'Version' )` plain, it will give you the child version.)

Because the child is loaded first, it can only dequeue the parent by running the action at a different priority. But instead, all it has to do is load a null sheet for the parent handle, because the first one wins (second one does not overwrite).

**Comment by joyously** [comment]
@pattonwebz 
Please don't put this as "Future"! It needs to be in 5.3 with the parent styles being loaded, or it will be difficult to change later (like all the other default themes).
