### ISSUE TITLE
Logo Doesn't Show Up in Normal Mode - Only Shows Up In Mobiles

### ISSUE THREAD

**Issue by saiftheboss7** [WordPress/twentytwenty#915]
Logo uploaded but the logo only shows from the mobile view. By default - the website doesn't show the logo.

Also, no option to show **The Logo** only.  It is possible to show the logo only when The Site Title and Tagline is enabled. 

Test website: saifhassan.info

**Comment by okpierre** [comment]
@saiftheboss7 logo works for me both with and without title/tagline on WP 5.2.4
