### ISSUE TITLE
Gutenberg issue with full width layout

### ISSUE THREAD

**Issue by Swapnildhanrale** [WordPress/twentytwenty#916]
Not able to drag-drop block in the case given below.
Steps:
1. Take a column of three in Gutenberg block
2. Make that block full width
3. Add images in each column and make that image also a full width.
4. Then again try to edit that image you can see the issue that as shown in the screenshot below.

As shown in the screenshot below.
Screenshot Url - https://cl.ly/1cc5ab0cc03d

**Comment by Swapnildhanrale** [comment]
It's simple controls for the drag drop are going beside to the editor
settings

**Comment by mikeyarce** [comment]
This is not an issue with TwentyTwenty but an issue with the Gutenberg Editor.
Tested with a variety of other themes and it's the same.

**Comment by nielslange** [comment]
Close issue based on https://github.com/WordPress/twentytwenty/issues/916#issuecomment-547573890
