### ISSUE TITLE
aligned button in Cover block is cut off

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#917]
Put a button aligned right into a Cover block. The `overflow: hidden` which makes the Cover block work cuts off the button because of the margin on `alignright` that pushes it outside the usual width.
This screenshot is from WP 5.3-RC2.

![button-cut-off-in-cover-block](https://user-images.githubusercontent.com/7957680/67403886-2f4d8180-f578-11e9-9f39-972a3f082183.jpg)

**Comment by Aurorum** [comment]
PR in #919 :)

<img width="374" alt="Screenshot 2019-10-23 at 18 08 34" src="https://user-images.githubusercontent.com/43215253/67417541-f1288000-f5c0-11e9-9e1d-78e745db1084.png">
