### ISSUE TITLE
separators for post navigation are inconsistent

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#918]
I customized some colors and noticed that the separators on the post navigation are not always the same.
Here, I thought it was because there is only one link, but apparently there is a rendering bug in SeaMonkey, because even the screenshot from the browser extension did not show the problem. This screenshot is cut from the desktop view, and shows the bottom line is thicker than the top line. I'm not too concerned about this since it did not show in Firefox or even in the Dev Tools (always showing the properties of both `hr`s the same). But it really makes it look like the `//` is not the same color as the line.
![post-nav-SeaMonkey](https://user-images.githubusercontent.com/7957680/67412338-b56fc500-f584-11e9-80d3-4986f28290aa.jpg)

Once it caught my eye, I looked at other posts, and they mostly looked like they should:
![post-nav-two-links](https://user-images.githubusercontent.com/7957680/67412418-ddf7bf00-f584-11e9-9b09-38cf80e377a6.jpg)

But when checking the other end of the posts, to get only one link, I see this which has the bottom `//` cut off. Is something overlapping? This is the only one I grabbed that didn't have a comment box, so that could be relevant. It showed the same in Firefox.
![post-nav-overlap](https://user-images.githubusercontent.com/7957680/67412605-375fee00-f585-11e9-9102-6f3603276be8.jpg)

**Comment by Swapnildhanrale** [comment]
@joyously My PR fixes this - #924
