### ISSUE TITLE
Impossible to add new twentytwenty_get_theme_svg icons

### ISSUE THREAD

**Issue by SGr33n** [WordPress/twentytwenty#925]
Hi, I suppose there should be a filter that allows child theme developers to add new icons to render via the twentytwenty_get_theme_svg function, both for ui and social icons.

[svg-icons-filters.zip](https://github.com/WordPress/twentytwenty/files/3773038/svg-icons-filters.zip)

In this patch i added two filters:
twentytwenty_theme_ui_svg_icons
twentytwenty_theme_social_svg_icons

**Comment by andersnoren** [comment]
Hi @SGr33n,

Thanks for the patch! A PR has been created for this, but it has been marked for "Future Consideration" since we're in bug-fix only territory. You can find the PR here: https://github.com/WordPress/twentytwenty/pull/770
