### ISSUE TITLE
Horizontal scrollbar on menu modal

### ISSUE THREAD

**Issue by SGr33n** [WordPress/twentytwenty#926]
Hi, looks lilke an horizontal scrollbar appears when menu modal is visible on screens under 680px width.

My diff patch attached.

![horizontal](https://user-images.githubusercontent.com/882463/67591478-d63f4280-f75d-11e9-9a7f-f3df4af7520a.JPG)

[modal-menu-scrollbar.zip](https://github.com/WordPress/twentytwenty/files/3773135/modal-menu-scrollbar.zip)

**Comment by Adhitya03** [comment]
Hi, I want to work on this issue but I cannot reproduce the issue, All works fine from my side, can you help me reproduce the issue ?

![926](https://user-images.githubusercontent.com/9330604/67803993-b04cd180-fac0-11e9-904b-cd254075ed4f.png)
