### ISSUE TITLE
comment reply link doesn't work right

### ISSUE THREAD

**Issue by joyously** [WordPress/twentytwenty#927]
(Mentioned in today's accessibility bug scrub)
On a post with several comments, click the Reply links.

**Expected result:** either the page is scrolled to the comment form at the bottom, or the form appears at the comment where Reply was clicked.

**Actual result:** the page is scrolled to a random-seeming location and the comment form may or may not be visible.

**Comment by joyously** [comment]
My test was on WP 5.3 RC2. (I tried my own theme and it worked fine.)
When I try this test on WP 4.9.12, the Reply links work correctly.

**Comment by afercia** [comment]
Animated Gif to illustrate the problem. The GIF rate makes the scrolling appear a bit sluggish but you fet the idea. 

![comments-scroll](https://user-images.githubusercontent.com/1682452/67618106-df2a2580-f7ea-11e9-8790-c55f1877aac1.gif)

**Comment by afercia** [comment]
I'd strongly recommend to set this issue to a high priority and fix it for the 5.3 release. WordPress 5.3 is in Release Candidate but this bug makes the comments barely usable. /Cc @ianbelanger79 

Could also be fixed directly in core. The fix appears super simple:

https://github.com/WordPress/twentytwenty/blob/cf6d8d439d927d2e1376b1704efbb2922a4bc677/assets/js/index.js#L335-L340

1. remove the dot from `element.classList.contains( '.do-not-scroll' )`
2. it needs to filter also the "Cancel reply" link `#cancel-comment-reply-link`

I'd do it myself if I had the permissions, but I can't even set labels on this repository and I'm not going to fork and send a PR request.
