### ISSUE TITLE
Add IE skip link focus fix

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#935]
When using the skip link in IE, it will scroll you to the content, but focus does not change.
Background: https://github.com/Automattic/_s/pull/136

Solution: Include the skip-link-focus-fix.js from Twenty Nineteen.
https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentynineteen/functions.php?rev=46347#L239

And the non minified source:
https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentynineteen/js/skip-link-focus-fix.js?rev=46347

**Comment by byalextran** [comment]
@carolinan thanks for highlighting the solution. i took a stab at it.
