### ISSUE TITLE
"Read More" tag does nothing on click

### ISSUE THREAD

**Issue by gravityrail** [WordPress/twentytwenty#945]
https://github.com/WordPress/twentytwenty/blob/41b4bf3f5969d2c581099240b8b44e2536226b44/functions.php#L568

This swallows the attributes of the link and outputs it as a span, which does not link to anything.

A solution would be to reinstate a call to `get_permalink( get_the_ID() )` as per the deleted code in [this PR](https://github.com/WordPress/twentytwenty/pull/815) that introduced the bug, or simply not to swallow the anchor tag in its entirety.

https://github.com/WordPress/twentytwenty/pull/815

**Comment by joyously** [comment]
So, this is like #791 again?

**Comment by okpierre** [comment]
I'm experience the same issue @joyously and it may be due merge from https://github.com/WordPress/twentytwenty/pull/911 ? Maybe @ianbelanger79 can confirm?

**Comment by byalextran** [comment]
this has been fixed/merged in https://github.com/WordPress/twentytwenty/pull/952.

**Comment by desrosj** [comment]
Thanks, @byalextran!
