### ISSUE TITLE
Issue in front end display.

### ISSUE THREAD

**Issue by mafzal9** [WordPress/twentytwenty#948]
Hi,

When i try to scroll the theme suddenly a horizontal line show up. attached is a image which is showing every thing. or you can also view at https://babyhoster.com/dev/

<img width="1440" alt="Screen Shot 2019-11-04 at 6 11 37 PM" src="https://user-images.githubusercontent.com/5222380/68123495-e231be00-ff2e-11e9-8fa1-fd87cdaa668a.png">

**Comment by carolinan** [comment]
Hi!
Can you give us any more details of what version of the theme you are using (Latest RC?) 
and which browser. 
Do you have any plugins installed that affects the widget area?

**Comment by mafzal9** [comment]
Yeah i am using latest version but on WordPress 5.2 Version. this error only comes when you try to use Cover Page Layout.
