### ISSUE TITLE
Adding a section before the sticky header

### ISSUE THREAD

**Issue by lchongv** [WordPress/twentytwenty#95]
This is only an idea, please if this is not the way to canalize it, delete it.

There is a way to adapt the theme to adding a section before the header section? At least in the front-page or cover page template. In Chaplin it begins in header, and i wish there are a way to put a section before the header. I tried to do it but the lots of js working made it difficult.

Thanks in advance.

**Comment by carolinan** [comment]
Hi, perhaps a mockup showing what you mean with this section would help us understand the suggestion better?

**Comment by lchongv** [comment]
In my primitive try of see the viability of this, i've found this video with the idea https://www.youtube.com/watch?v=5C_p7BDSL5I

**Comment by carolinan** [comment]
Thank you for the suggestion.

We will not be adding this, the header is already complex with the different menus and the search modals. There is also the cover template which adds a different style to the header.
