### ISSUE TITLE
Fixed Background Image on Cover template bugs on iPad

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#956]
In the Customizer, if the user selects the "Fixed Background Image" option for the Cover template (which is activated by default), the cover image on an iPad (iOS 13) is blown-up.

iPad | Correct View
-- | --
![fixed](https://user-images.githubusercontent.com/54663751/68325121-1ccf5e00-00c9-11ea-9c44-7085f3a9948c.jpg) | ![no-fixed](https://user-images.githubusercontent.com/54663751/68325137-22c53f00-00c9-11ea-8bb8-c9373e5bb6a4.jpg)

**Comment by joyously** [comment]
I have seen other image issues reported for iOS 13. Could this be one?
Fixed background doesn't work well on any mobile device because of the viewport.

**Comment by ianbelanger79** [comment]
Moved to trac https://core.trac.wordpress.org/ticket/48802
