### ISSUE TITLE
Cover block bug: setting an Overlay Color preset breaks the image background-size

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#957]
For the Cover block, if the user selects an overlay color preset the background image is repeated instead of stretched.

![cover](https://user-images.githubusercontent.com/54663751/68325353-7b94d780-00c9-11ea-8157-cf689e97f8e3.png)

**Comment by carolinan** [comment]
I am getting a different result. My image is not being repeated but more like zoomed in.

This needs to be tested further, selecting a preset color as overlay should not behave differently from selecting a custom color and it should reflect what is seen in the editor.

**Comment by andersnoren** [comment]
This is caused by the custom colors CSS using the `background` property shorthand rather than `background-color`, resulting in the non-color attributes of `background` being reset to their default values. I'll create a PR for replacing the `background` property with `background-color`.
