### ISSUE TITLE
The default font size setting for the Paragraph block displays a wrong and misleading value

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#958]
Currently, every time the user inserts a new paragraph block, it shows that the font size is set to `Small` which is not true (it's actually `Regular`). 

It's very confusing for the user:

**If the user wants a Regular text**
The user might try to change the value from `Small` to `Regular` and there won't be any visible change (it only adds an unnecessary `has-regular-font-size` class)

**If the user wants a Small text**
The user must first change the value from `Small` to `Regular`and then change it back from `Regular`to `Small`.

This bug has been tackled in previous issues and PR but the result is IMO the most confusing solution.

A solution (without affecting the string freeze) is to display the `Regular` option first in the dropdown.

**Comment by carolinan** [comment]
There are already 2 issues regarding this.

**Comment by pattonwebz** [comment]
I merged a change which results in the `Regular` size being displayed first in the dropdown by changing the slug to `normal` which means alphanumeric sorting handles the placement where it needs to be for now. Merged in #989
