### ISSUE TITLE
Starter Content showcases wrong use of blocks

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#959]
The "The New UMoMA Opens its Doors" page is supposed to showcase what the user can do with the blocks (and how to do it) and be used as a starting point. Currently, a part of this page has a bad structure that can lead the users to use the block editor in a wrong manner.

![starter](https://user-images.githubusercontent.com/54663751/68325713-4472f600-00ca-11ea-86fe-2b3a39b399db.jpg)

- This kind of layout should be built using 2 Columns blocks instead of one. The content for "Theatre of Operations" and "From Signac to Matisse" should be placed inside a second Columns block.

- With a proper structure, it isn't necessary to use Group blocks inside Column block.

- The Image block shouldn't be set to Full Width

As a result the design is off, there is way too much spacing between a title and its image. With a proper structure, it should look like http://2020.wordpress.net/

**Comment by carolinan** [comment]
While I dont agree with the notion that there is a right or wrong way to use the editor,
whenever markup can be simplified, it should.

**Comment by ianbelanger79** [comment]
Moved to trac https://core.trac.wordpress.org/ticket/48801
