### ISSUE TITLE
Full Width Columns are missing horizontal spacing

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#961]
If the user inserts a full width Columns block, there's no spacing between the text and the edges of the screen. For devices that have a scrollbar, the edges of the content are outside the screen.

![fullwidthcolumns](https://user-images.githubusercontent.com/54663751/68326355-90726a80-00cb-11ea-96ff-e32371e65a53.png)

**Comment by carolinan** [comment]
This was supposedly fixed with #707. To reproduce, did you just change the width of the starter content, or?

**Comment by andersnoren** [comment]
I'll include a fix for this as part of the fix for #963. Currently, only paragraphs get the horizontal padding on the first and last items, which results in the spacing being uneven (described in #963) and the full-width columns block as a whole missing a horizontal padding.
