### ISSUE TITLE
Custom Column widths are not responsive

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#962]
If the user changes the width of the Column block, or use a preset with unequal columns, the layout doesn't display properly for medium devices (600-781px).

Example using the "Two columns; two-thirds, one-third split" preset:

782px + | 600-781px
-- | --
![782](https://user-images.githubusercontent.com/54663751/68326629-18f10b00-00cc-11ea-955f-cacd3036da9e.png) | ![781](https://user-images.githubusercontent.com/54663751/68326642-1d1d2880-00cc-11ea-8091-db999a9c8754.png)

**Comment by andersnoren** [comment]
@yannickiki Thanks for creating the issue! This seems to be a problem with the block styles included in Core. I get the same issue in Twenty Nineteen, and it also seems to happen when I remove all styles but the ones in `block-styles.css` (the Core block stylesheet). Can you confirm?

**Comment by yannickiki** [comment]
Hi @andersnoren . Yes you're right. I'll ask on core-editor channel if this issue can be fixed on their side for 5.3. If not, maybe Twenty Twenty can fixed it.
