### ISSUE TITLE
Selecting a Background Color preset for the Group block should automatically change the text color

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#964]
Some blocks don't have text color settings (Quote, List, Table...). If the user adds one of these blocks inside a group and selects the Primary, Accent or Secondary Color as the Background Color, the text is unreadable (and not AA compliant). It also doesn't work with custom colors.

Like Twenty Nineteen, Twenty Twenty should at least define the text color in accordance with the background color presets.

Group without Background Color | Group with Primary Background Color
-- | --
![no-background](https://user-images.githubusercontent.com/54663751/68327150-17741280-00cd-11ea-8df2-0f5b2c750acc.png) | ![background](https://user-images.githubusercontent.com/54663751/68327176-21961100-00cd-11ea-9a7d-a6f21d9c1fa8.png)

**Comment by pattonwebz** [comment]
Hey @yannickiki I merged some code which I think resolves this as best as we can right now. If other issues are noted could we report them via trac so we can work on them after release. Thank you!
