### ISSUE TITLE
Full Width Group & Cover blocks are unusable as they don’t respect Gutenberg nesting rules

### ISSUE THREAD

**Issue by yannickiki** [WordPress/twentytwenty#965]
I've created this issue to highlight the current problems with Group & Cover blocks as it's a critical issue that prevents to create "beautiful web pages and advanced layouts". A PR by @allancole is currently in progress (#701).

As stated in the WP 5.3 About page, "the new Group block lets you easily divide your page into colorful sections". Currently, this isn't the case as Twenty Twenty is breaking Gutenberg nesting rules:
Paragraphs, Headings, Lists, Quotes and default aligned blocks lose their widths and are stretched to full width (readability and design issues).

It should be easy for the user to replicate inside a group what it's possible to do outside a group.
The current solution to restore the text width is to insert a group inside the full width group. Users won't discover this solution because it doesn't make any sense, and users who build on a small screen (e.g. mac 13" at 1280px) might no see that the text is actually expanded to full width on a large screen (e.g 2560px and more). Even if the user discovers this solution, it's overcomplicated and adds unnecessary nested groups.

Contrary to Twenty Nineteen which respects Gutenberg nesting rules, Twenty Twenty would create a bad precedent on how users create layouts with Gutenberg blocks.

![group](https://user-images.githubusercontent.com/54663751/68327540-d7f9f600-00cd-11ea-837e-0f33118ea63b.png)

Same issue with the full width Cover block that doesn't work out of the box. A group must be inserted inside the cover to constrain the text.

**Comment by allancole** [comment]
Yup, looks like this will get fixed in #701 :-) 

**Before:**
![image](https://user-images.githubusercontent.com/709581/68429890-f9fe8180-017c-11ea-9596-4653d2fe9470.png)

**After:**
![image](https://user-images.githubusercontent.com/709581/68429794-c7ed1f80-017c-11ea-9f81-57b32053963f.png)
