### ISSUE TITLE
Update style.css to include `Requires at least` and `Requires PHP` headers.

### ISSUE THREAD

**Issue by afragen** [WordPress/twentytwenty#966]
Per discussion in https://core.trac.wordpress.org/ticket/48515 and https://core.trac.wordpress.org/ticket/48517, we need to add these headers and data to the `style.css` file.

Thanks.

**Comment by afragen** [comment]
FWIW this also needs to be done in every default theme. ☹️

**Comment by joyously** [comment]
It's not _needed_ since it will default just fine. (like all the thousands of other themes out there)

**Comment by pattonwebz** [comment]
I will make a PR with these tomorrow if someone else doesn't get to it before me. Our min php is 5.6 and min wp version I think is 5.0 (but will need to do feature checks to confirm that).

**Comment by afragen** [comment]
@joyously if we don't set an example with the default themes how can we expect others to use this and moreover how can we expect to test themes for compatibility with a user's server?

**Comment by joyously** [comment]
@pattonwebz Use http://wpseek.com/pluginfilecheck/ for finding min WP version. We were not targeting 5.0. I've been testing this whole time with 4.9.

@afragen I'm not saying they shouldn't be changed. I'm saying it's not _needed_, as in everything should work fine without it, and most themes will be without the headers. It's a progressive enhancement, not essential or urgent. (and the default themes are doing a lot of other things that aren't great at the same time)

**Comment by afragen** [comment]
I believe 8d9725e13f16604c35a6c1e31d5c6412b0efd953 closes this issue.
