### ISSUE TITLE
Input fields have no visible focus in multiple browsers

### ISSUE THREAD

**Issue by carolinan** [WordPress/twentytwenty#975]
Users need to be able to see when an input field is selected.
Both to be able to use the fields and to navigate past them, they need to be able to see where they are on the page.

On Windows: 
Below is the comment field when no fields are selected:
(Chrome)

![comment-no-focus](https://user-images.githubusercontent.com/7422055/68528421-baf23c80-02f2-11ea-900e-3758559ffa25.png)

Below is when the comment text area is select, in Chrome:
![comment-selected-chrome](https://user-images.githubusercontent.com/7422055/68528434-f68d0680-02f2-11ea-87a1-c93b49ab34e7.png)

In Firefox, there is no visible outline or similar change:
![comment-selected-firefox](https://user-images.githubusercontent.com/7422055/68528472-68655000-02f3-11ea-9591-bb08384c86e1.png)

In Edge, there is no visible outline or similar change:
![comment-selected-edge](https://user-images.githubusercontent.com/7422055/68528523-1113af80-02f4-11ea-9d32-da0a821eaf49.png)

In IE 11, there is no visible outline or similar change:
![comment-selected-ie11](https://user-images.githubusercontent.com/7422055/68528556-ae6ee380-02f4-11ea-8b4c-4faefb134370.png)

**Comment by andersnoren** [comment]
Fixed by #976.
